// Modul 6: Ekologie - 100 otázek
const MODULE6_QUESTIONS = {
    module6_level1: [
        { question: "Co je ekologické zemědělství?", type: "multiple_choice", options: [{ text: "Hospodaření bez syntetické chemie", icon: "🌿", isCorrect: true }, { text: "Pouze velké farmy", icon: "🏭", isCorrect: false }, { text: "Pouze malé zahrádky", icon: "🏡", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Bio zemědělství nepoužívá syntetické pesticidy a hnojiva." },
        { question: "Bio certifikace v EU:", type: "multiple_choice", options: [{ text: "Má jednotná pravidla a logo", icon: "🌱", isCorrect: true }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Je dobrovolná", icon: "🤷", isCorrect: false }, { text: "Pouze pro ovoce", icon: "🍎", isCorrect: false }], explanation: "EU bio logo garantuje dodržování ekologických standardů." },
        { question: "Přechodné období na bio je:", type: "multiple_choice", options: [{ text: "2-3 roky podle plodiny", icon: "📅", isCorrect: true }, { text: "1 týden", icon: "📆", isCorrect: false }, { text: "10 let", icon: "📅", isCorrect: false }, { text: "Není potřeba", icon: "❌", isCorrect: false }], explanation: "Půda musí být očištěna od reziduí před certifikací." },
        { question: "V bio zemědělství je zakázáno:", type: "multiple_choice", options: [{ text: "GMO a syntetické pesticidy", icon: "⛔", isCorrect: true }, { text: "Kompost", icon: "♻️", isCorrect: false }, { text: "Střídání plodin", icon: "🔄", isCorrect: false }, { text: "Ruční práce", icon: "✋", isCorrect: false }], explanation: "Bio standardy vylučují GMO, syntetické chemikálie." },
        { question: "Biodiverzita znamená:", type: "multiple_choice", options: [{ text: "Rozmanitost živých organismů", icon: "🦋", isCorrect: true }, { text: "Pouze bio produkty", icon: "🌿", isCorrect: false }, { text: "Typ hnojiva", icon: "🧪", isCorrect: false }, { text: "Druh plodiny", icon: "🌾", isCorrect: false }], explanation: "Biodiverzita je základem zdravých ekosystémů." },
        { question: "Opylovači jsou důležití pro:", type: "multiple_choice", options: [{ text: "Opylení rostlin a tvorbu plodů", icon: "🐝", isCorrect: true }, { text: "Pouze med", icon: "🍯", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze krásu", icon: "🎨", isCorrect: false }], explanation: "Bez opylovačů by mnoho plodin netvořilo plody." },
        { question: "Užiteční predátoři v sadech:", type: "multiple_choice", options: [{ text: "Slunéčka, zlatoočky, lumci", icon: "🐞", isCorrect: true }, { text: "Pouze ptáci", icon: "🐦", isCorrect: false }, { text: "Žádní", icon: "❌", isCorrect: false }, { text: "Pouze pavouci", icon: "🕷️", isCorrect: false }], explanation: "Přirození nepřátelé pomáhají regulovat škůdce." },
        { question: "Agroekologie studuje:", type: "multiple_choice", options: [{ text: "Ekologické procesy v zemědělství", icon: "🔬", isCorrect: true }, { text: "Pouze ekonomiku", icon: "💰", isCorrect: false }, { text: "Pouze počasí", icon: "🌤️", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Agroekologie hledá udržitelné způsoby hospodaření." },
        { question: "Ekosystémové služby zahrnují:", type: "multiple_choice", options: [{ text: "Opylení, čištění vody, půdotvorbu", icon: "🌍", isCorrect: true }, { text: "Pouze produkci", icon: "🌾", isCorrect: false }, { text: "Pouze krásu", icon: "🎨", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Příroda poskytuje služby, které bychom jinak museli platit." },
        { question: "Krajinné prvky podporují:", type: "multiple_choice", options: [{ text: "Biodiverzitu a přírodní nepřátele", icon: "🌳", isCorrect: true }, { text: "Pouze estetiku", icon: "🎨", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Škůdce", icon: "🐛", isCorrect: false }], explanation: "Meze, remízky a mokřady jsou refugia užitečných organismů." }
    ],
    module6_level2: [
        { question: "Uhlíková stopa zemědělství:", type: "multiple_choice", options: [{ text: "Zahrnuje emise z výroby a dopravy", icon: "👣", isCorrect: true }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Je vždy nulová", icon: "0️⃣", isCorrect: false }, { text: "Pouze z traktorů", icon: "🚜", isCorrect: false }], explanation: "Zemědělství přispívá k emisím CO2, CH4 a N2O." },
        { question: "Sekvestrace uhlíku v půdě:", type: "multiple_choice", options: [{ text: "Ukládání uhlíku z atmosféry", icon: "⬇️", isCorrect: true }, { text: "Uvolňování CO2", icon: "⬆️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Spalování", icon: "🔥", isCorrect: false }], explanation: "Zdravá půda může být významným úložištěm uhlíku." },
        { question: "Metan v zemědělství pochází z:", type: "multiple_choice", options: [{ text: "Chovu přežvýkavců a rýžových polí", icon: "🐄", isCorrect: true }, { text: "Pouze traktorů", icon: "🚜", isCorrect: false }, { text: "Pouze ze slunce", icon: "☀️", isCorrect: false }, { text: "Nikde", icon: "❌", isCorrect: false }], explanation: "Přežvýkavci produkují metan při trávení." },
        { question: "Oxid dusný vzniká při:", type: "multiple_choice", options: [{ text: "Aplikaci dusíkatých hnojiv", icon: "🧪", isCorrect: true }, { text: "Orbě", icon: "🚜", isCorrect: false }, { text: "Sklizni", icon: "🌾", isCorrect: false }, { text: "Nevzniká", icon: "❌", isCorrect: false }], explanation: "N2O je silný skleníkový plyn z hnojiv a statkových hnojiv." },
        { question: "Regenerativní zemědělství:", type: "multiple_choice", options: [{ text: "Obnovuje zdraví půdy a biodiverzitu", icon: "♻️", isCorrect: true }, { text: "Ničí půdu", icon: "❌", isCorrect: false }, { text: "Používá více chemie", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "⛔", isCorrect: false }], explanation: "Regenerativní přístupy aktivně zlepšují ekosystém." },
        { question: "Cover crops (pokryvné plodiny):", type: "multiple_choice", options: [{ text: "Chrání půdu a vážou uhlík", icon: "🌱", isCorrect: true }, { text: "Jsou plevele", icon: "🌿", isCorrect: false }, { text: "Škodí", icon: "❌", isCorrect: false }, { text: "Pouze pro krásu", icon: "🎨", isCorrect: false }], explanation: "Pokryvné plodiny chrání půdu a přidávají organickou hmotu." },
        { question: "No-till farming:", type: "multiple_choice", options: [{ text: "Hospodaření bez orby", icon: "🚫", isCorrect: true }, { text: "Intenzivní orba", icon: "🚜", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze v zimě", icon: "❄️", isCorrect: false }], explanation: "Bezorebné hospodaření chrání strukturu půdy a život v ní." },
        { question: "Agrolesnictví kombinuje:", type: "multiple_choice", options: [{ text: "Stromy s plodinami nebo zvířaty", icon: "🌳", isCorrect: true }, { text: "Pouze stromy", icon: "🌲", isCorrect: false }, { text: "Pouze plodiny", icon: "🌾", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Stromy na poli poskytují stín, biomasu a diverzitu." },
        { question: "Uhlíkové kredity:", type: "multiple_choice", options: [{ text: "Odměna za ukládání uhlíku", icon: "💰", isCorrect: true }, { text: "Daň", icon: "📋", isCorrect: false }, { text: "Hnojivo", icon: "🧪", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Farmáři mohou získat příjem za klimaticky pozitivní postupy." },
        { question: "LCA (Life Cycle Assessment):", type: "multiple_choice", options: [{ text: "Hodnocení dopadu v celém životním cyklu", icon: "🔄", isCorrect: true }, { text: "Pouze cena", icon: "💰", isCorrect: false }, { text: "Pouze výnos", icon: "🌾", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "LCA měří environmentální dopad od pole po talíř." }
    ],
    module6_level3: [
        { question: "Eroze půdy je:", type: "multiple_choice", options: [{ text: "Odnos půdy vodou nebo větrem", icon: "💨", isCorrect: true }, { text: "Obohacení půdy", icon: "📈", isCorrect: false }, { text: "Růst rostlin", icon: "🌱", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Eroze je vážný problém, ztráta půdy je téměř nevratná." },
        { question: "Protierozní opatření zahrnují:", type: "multiple_choice", options: [{ text: "Zasakovací pásy, meze, zatravnění", icon: "🌾", isCorrect: true }, { text: "Více orby", icon: "🚜", isCorrect: false }, { text: "Odstranění vegetace", icon: "✂️", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Vegetace a technická opatření zpomalují odtok vody." },
        { question: "DZES jsou:", type: "multiple_choice", options: [{ text: "Dobré zemědělské a environmentální podmínky", icon: "📋", isCorrect: true }, { text: "Druh hnojiva", icon: "🧪", isCorrect: false }, { text: "Typ traktoru", icon: "🚜", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "DZES jsou povinné standardy pro příjem dotací." },
        { question: "Kontaminace vod ze zemědělství:", type: "multiple_choice", options: [{ text: "Dusičnany, fosfor, pesticidy", icon: "💧", isCorrect: true }, { text: "Pouze voda", icon: "💧", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze sůl", icon: "🧂", isCorrect: false }], explanation: "Splachy z polí mohou kontaminovat vodní zdroje." },
        { question: "Nitrátová směrnice EU:", type: "multiple_choice", options: [{ text: "Omezuje aplikaci dusíku", icon: "📋", isCorrect: true }, { text: "Podporuje více hnojení", icon: "📈", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze pro rýži", icon: "🍚", isCorrect: false }], explanation: "Směrnice chrání vody před znečištěním dusičnany." },
        { question: "Zranitelné oblasti jsou:", type: "multiple_choice", options: [{ text: "Oblasti s rizikem znečištění vod", icon: "⚠️", isCorrect: true }, { text: "Bezpečné oblasti", icon: "✅", isCorrect: false }, { text: "Pouze pouště", icon: "🏜️", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "V ZOD platí přísnější pravidla pro hnojení." },
        { question: "Břehové porosty:", type: "multiple_choice", options: [{ text: "Chrání vodní toky před splachy", icon: "🌿", isCorrect: true }, { text: "Škodí", icon: "❌", isCorrect: false }, { text: "Jsou zakázány", icon: "⛔", isCorrect: false }, { text: "Pouze pro krásu", icon: "🎨", isCorrect: false }], explanation: "Vegetace podél toků zachycuje živiny a sedimenty." },
        { question: "Mokřady v krajině:", type: "multiple_choice", options: [{ text: "Čistí vodu a podporují biodiverzitu", icon: "🦆", isCorrect: true }, { text: "Jsou zbytečné", icon: "❌", isCorrect: false }, { text: "Pouze překážejí", icon: "⛔", isCorrect: false }, { text: "Šíří choroby", icon: "🦠", isCorrect: false }], explanation: "Mokřady jsou cenné ekosystémy s mnoha funkcemi." },
        { question: "Precizní hnojení snižuje:", type: "multiple_choice", options: [{ text: "Ztráty živin do prostředí", icon: "📉", isCorrect: true }, { text: "Výnosy", icon: "🌾", isCorrect: false }, { text: "Kvalitu", icon: "⭐", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Přesná aplikace minimalizuje přebytky a ztráty." },
        { question: "Udržitelná intenzifikace:", type: "multiple_choice", options: [{ text: "Více produkce s menším dopadem", icon: "🎯", isCorrect: true }, { text: "Více chemie", icon: "🧪", isCorrect: false }, { text: "Méně produkce", icon: "📉", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Cílem je zvýšit efektivitu při ochraně prostředí." }
    ],
    module6_level4: [
        { question: "Organické hnojení:", type: "multiple_choice", options: [{ text: "Kompost, hnůj, zelené hnojení", icon: "♻️", isCorrect: true }, { text: "Syntetická hnojiva", icon: "🧪", isCorrect: false }, { text: "Pesticidy", icon: "💦", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Organická hnojiva dodávají živiny a zlepšují půdu." },
        { question: "Zelené hnojení je:", type: "multiple_choice", options: [{ text: "Zaorání rostlin pro obohacení půdy", icon: "🌿", isCorrect: true }, { text: "Zelená barva hnojiva", icon: "🎨", isCorrect: false }, { text: "Syntetické hnojivo", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Zelené hnojení přidává organickou hmotu a živiny." },
        { question: "Luskoviny fixují:", type: "multiple_choice", options: [{ text: "Vzdušný dusík do půdy", icon: "🌿", isCorrect: true }, { text: "Pouze fosfor", icon: "🧪", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Oxid uhličitý", icon: "☁️", isCorrect: false }], explanation: "Symbióza s rhizobii váže dusík z atmosféry." },
        { question: "Kompostování je:", type: "multiple_choice", options: [{ text: "Řízený rozklad organické hmoty", icon: "♻️", isCorrect: true }, { text: "Spalování odpadu", icon: "🔥", isCorrect: false }, { text: "Skládkování", icon: "🗑️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Kompost je cenné hnojivo a zlepšovač půdy." },
        { question: "Vermikompost je:", type: "multiple_choice", options: [{ text: "Kompost vytvořený žížalami", icon: "🪱", isCorrect: true }, { text: "Syntetické hnojivo", icon: "🧪", isCorrect: false }, { text: "Pesticid", icon: "💦", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Žížalí trus je vysoce kvalitní organické hnojivo." },
        { question: "Biopreparáty jsou:", type: "multiple_choice", options: [{ text: "Přípravky z živých organismů", icon: "🦠", isCorrect: true }, { text: "Syntetická chemie", icon: "🧪", isCorrect: false }, { text: "Pesticidy", icon: "💦", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Biopreparáty obsahují prospěšné mikroorganismy nebo extrakty." },
        { question: "Mikrobní inokulanty:", type: "multiple_choice", options: [{ text: "Prospěšné mikroorganismy pro půdu", icon: "🦠", isCorrect: true }, { text: "Patogeny", icon: "☠️", isCorrect: false }, { text: "Pesticidy", icon: "💦", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Inokulanty zlepšují zdraví půdy a rostlin." },
        { question: "Biologická ochrana využívá:", type: "multiple_choice", options: [{ text: "Přirozené nepřátele škůdců", icon: "🐞", isCorrect: true }, { text: "Více chemie", icon: "🧪", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze postřiky", icon: "💦", isCorrect: false }], explanation: "Predátoři a parazitoidi regulují populace škůdců." },
        { question: "Feromonové lapáky:", type: "multiple_choice", options: [{ text: "Monitorují nebo lapají hmyz", icon: "🪤", isCorrect: true }, { text: "Zabíjejí vše", icon: "☠️", isCorrect: false }, { text: "Hnojí", icon: "🧪", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Feromony lákají specifické druhy hmyzu." },
        { question: "Mulčování v bio:", type: "multiple_choice", options: [{ text: "Potlačuje plevele a chrání půdu", icon: "🍂", isCorrect: true }, { text: "Škodí rostlinám", icon: "❌", isCorrect: false }, { text: "Je zakázáno", icon: "⛔", isCorrect: false }, { text: "Nic nedělá", icon: "🤷", isCorrect: false }], explanation: "Mulč je důležitý nástroj ekologického hospodaření." }
    ],
    module6_level5: [
        { question: "Welfare zvířat v bio:", type: "multiple_choice", options: [{ text: "Vyšší standardy pohody", icon: "🐄", isCorrect: true }, { text: "Žádné požadavky", icon: "❌", isCorrect: false }, { text: "Nižší standardy", icon: "📉", isCorrect: false }, { text: "Pouze pro drůbež", icon: "🐔", isCorrect: false }], explanation: "Bio chov vyžaduje přístup ven, prostor, přirozené chování." },
        { question: "Výběh pro bio slepice:", type: "multiple_choice", options: [{ text: "Je povinný", icon: "✅", isCorrect: true }, { text: "Je zakázán", icon: "⛔", isCorrect: false }, { text: "Je dobrovolný", icon: "🤷", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Bio drůbež musí mít přístup k venkovnímu výběhu." },
        { question: "Antibiotika v bio chovu:", type: "multiple_choice", options: [{ text: "Omezena, pouze léčebně", icon: "💊", isCorrect: true }, { text: "Volně používaná", icon: "✅", isCorrect: false }, { text: "Zakázána úplně", icon: "⛔", isCorrect: false }, { text: "Povinná", icon: "📋", isCorrect: false }], explanation: "Bio přednost má prevence, ATB jen jako krajní léčba." },
        { question: "Krmivo pro bio zvířata:", type: "multiple_choice", options: [{ text: "Musí být bio původu", icon: "🌿", isCorrect: true }, { text: "Může být jakékoliv", icon: "🤷", isCorrect: false }, { text: "Musí být GMO", icon: "🧬", isCorrect: false }, { text: "Pouze seno", icon: "🌾", isCorrect: false }], explanation: "Bio zvířata dostávají bio krmiva bez GMO." },
        { question: "Pastevní chov:", type: "multiple_choice", options: [{ text: "Zvířata se pasou na travních porostech", icon: "🐄", isCorrect: true }, { text: "Zvířata jsou uvnitř", icon: "🏠", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze pro ovce", icon: "🐑", isCorrect: false }], explanation: "Pastva je přirozený způsob chovu přežvýkavců." },
        { question: "Extenzivní chov:", type: "multiple_choice", options: [{ text: "Nízká intenzita, velký prostor", icon: "🌳", isCorrect: true }, { text: "Vysoká intenzita", icon: "📈", isCorrect: false }, { text: "Bez prostoru", icon: "📦", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Extenzivní chov dává zvířatům více prostoru a volnosti." },
        { question: "Lokální plemena:", type: "multiple_choice", options: [{ text: "Lépe přizpůsobena místním podmínkám", icon: "🐄", isCorrect: true }, { text: "Vždy horší", icon: "📉", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Pouze pro výstavy", icon: "🏆", isCorrect: false }], explanation: "Tradiční plemena jsou odolnější a udržitelnější." },
        { question: "Silvopasture je:", type: "multiple_choice", options: [{ text: "Pastva pod stromy", icon: "🌳", isCorrect: true }, { text: "Lesní hospodaření", icon: "🌲", isCorrect: false }, { text: "Pěstování hub", icon: "🍄", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Kombinace stromů a pastvy poskytuje stín a krmivo." },
        { question: "Rotační pastva:", type: "multiple_choice", options: [{ text: "Střídání pastevních ploch", icon: "🔄", isCorrect: true }, { text: "Stálá pastva", icon: "📍", isCorrect: false }, { text: "Žádná pastva", icon: "⛔", isCorrect: false }, { text: "Pouze v létě", icon: "☀️", isCorrect: false }], explanation: "Rotace umožňuje regeneraci travních porostů." },
        { question: "Mob grazing:", type: "multiple_choice", options: [{ text: "Intenzivní krátkodobá pastva", icon: "🐄", isCorrect: true }, { text: "Celoroční pastva", icon: "📅", isCorrect: false }, { text: "Bez zvířat", icon: "❌", isCorrect: false }, { text: "Neexistuje", icon: "⛔", isCorrect: false }], explanation: "Vysoká hustota na krátkou dobu napodobuje přirozené stádo." }
    ],
    module6_level6: [
        { question: "GMO v EU je:", type: "multiple_choice", options: [{ text: "Přísně regulováno", icon: "📋", isCorrect: true }, { text: "Zcela zakázáno", icon: "⛔", isCorrect: false }, { text: "Bez omezení", icon: "✅", isCorrect: false }, { text: "Pouze pro výzkum", icon: "🔬", isCorrect: false }], explanation: "EU má nejpřísnější pravidla pro GMO na světě." },
        { question: "Cisgenetika:", type: "multiple_choice", options: [{ text: "Přenos genů v rámci druhu", icon: "🧬", isCorrect: true }, { text: "Přenos mezi druhy", icon: "🔄", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Je zakázána", icon: "⛔", isCorrect: false }], explanation: "Cisgenetika využívá geny z příbuzných druhů." },
        { question: "CRISPR v šlechtění:", type: "multiple_choice", options: [{ text: "Přesná editace genů", icon: "✂️", isCorrect: true }, { text: "Je zakázán", icon: "⛔", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze pro léky", icon: "💊", isCorrect: false }], explanation: "CRISPR umožňuje cílené změny bez vkládání cizích genů." },
        { question: "Koexistence GMO a bio:", type: "multiple_choice", options: [{ text: "Vyžaduje ochranná opatření", icon: "🛡️", isCorrect: true }, { text: "Je nemožná", icon: "❌", isCorrect: false }, { text: "Nevyžaduje nic", icon: "🤷", isCorrect: false }, { text: "Je povinná", icon: "📋", isCorrect: false }], explanation: "Pravidla minimalizují kontaminaci bio produkce GMO." },
        { question: "Marker-assisted selection:", type: "multiple_choice", options: [{ text: "Šlechtění pomocí genetických markerů", icon: "🔬", isCorrect: true }, { text: "Ruční výběr", icon: "✋", isCorrect: false }, { text: "GMO", icon: "🧬", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "MAS urychluje šlechtění bez GMO technologií." },
        { question: "Odrůdy pro bio:", type: "multiple_choice", options: [{ text: "Odolné, přizpůsobené nízkým vstupům", icon: "🌱", isCorrect: true }, { text: "Vysoký výnos za každou cenu", icon: "📈", isCorrect: false }, { text: "Pouze GMO", icon: "🧬", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Bio vyžaduje odrůdy odolné vůči chorobám a konkurenční vůči plevelům." },
        { question: "Participatory breeding:", type: "multiple_choice", options: [{ text: "Zapojení farmářů do šlechtění", icon: "👨‍🌾", isCorrect: true }, { text: "Pouze vědci", icon: "🔬", isCorrect: false }, { text: "Pouze firmy", icon: "🏢", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Farmáři pomáhají vybírat odrůdy vhodné pro jejich podmínky." },
        { question: "Uchování genetických zdrojů:", type: "multiple_choice", options: [{ text: "Genové banky a on-farm conservation", icon: "🏦", isCorrect: true }, { text: "Není důležité", icon: "❌", isCorrect: false }, { text: "Pouze v muzeích", icon: "🏛️", isCorrect: false }, { text: "Pouze v přírodě", icon: "🌳", isCorrect: false }], explanation: "Genetická diverzita je pojistka pro budoucnost." },
        { question: "Landraces jsou:", type: "multiple_choice", options: [{ text: "Tradiční lokální odrůdy", icon: "🌾", isCorrect: true }, { text: "Moderní hybridy", icon: "🧬", isCorrect: false }, { text: "GMO odrůdy", icon: "🧬", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Krajové odrůdy jsou adaptované na místní podmínky." },
        { question: "Heterózní efekt:", type: "multiple_choice", options: [{ text: "Zvýšená životnost hybridů", icon: "💪", isCorrect: true }, { text: "Snížení výnosů", icon: "📉", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze u GMO", icon: "🧬", isCorrect: false }], explanation: "Křížení různých linií dává vitálnější potomstvo." }
    ],
    module6_level7: [
        { question: "Certifikace bio v ČR zajišťuje:", type: "multiple_choice", options: [{ text: "Akreditované kontrolní organizace", icon: "✅", isCorrect: true }, { text: "Farmář sám", icon: "👨‍🌾", isCorrect: false }, { text: "Nikdo", icon: "❌", isCorrect: false }, { text: "Supermarkety", icon: "🛒", isCorrect: false }], explanation: "KEZ, Biokont, ABCERT kontrolují dodržování pravidel." },
        { question: "EU bio logo je:", type: "multiple_choice", options: [{ text: "Povinné na bio výrobcích", icon: "🌿", isCorrect: true }, { text: "Dobrovolné", icon: "🤷", isCorrect: false }, { text: "Zakázané", icon: "⛔", isCorrect: false }, { text: "Pouze v ČR", icon: "🇨🇿", isCorrect: false }], explanation: "Zelený list je jednotné logo pro bio produkty v EU." },
        { question: "Demeter je:", type: "multiple_choice", options: [{ text: "Značka biodynamického zemědělství", icon: "🌙", isCorrect: true }, { text: "Hnojivo", icon: "🧪", isCorrect: false }, { text: "Pesticid", icon: "💦", isCorrect: false }, { text: "Traktor", icon: "🚜", isCorrect: false }], explanation: "Demeter má přísnější pravidla než běžné bio." },
        { question: "Biodynamické zemědělství:", type: "multiple_choice", options: [{ text: "Pracuje s kosmickými rytmy", icon: "🌙", isCorrect: true }, { text: "Používá více chemie", icon: "🧪", isCorrect: false }, { text: "Je zakázané", icon: "⛔", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Biodynamika vychází z učení Rudolfa Steinera." },
        { question: "Permakultura:", type: "multiple_choice", options: [{ text: "Trvalé udržitelné systémy", icon: "♾️", isCorrect: true }, { text: "Pouze zahradničení", icon: "🌷", isCorrect: false }, { text: "Intenzivní zemědělství", icon: "🏭", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Permakultura napodobuje přírodní ekosystémy." },
        { question: "Přírodní zemědělství (Fukuoka):", type: "multiple_choice", options: [{ text: "Minimální zásahy do přírody", icon: "🍃", isCorrect: true }, { text: "Intenzivní orba", icon: "🚜", isCorrect: false }, { text: "Hodně chemie", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Masanobu Fukuoka propagoval hospodaření bez orby a chemie." },
        { question: "Lesní zahrady:", type: "multiple_choice", options: [{ text: "Vícepatrové pěstební systémy", icon: "🌳", isCorrect: true }, { text: "Pouze les", icon: "🌲", isCorrect: false }, { text: "Pouze zahrada", icon: "🌷", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Lesní zahrady kombinují stromy, keře a byliny." },
        { question: "Syntropic agriculture:", type: "multiple_choice", options: [{ text: "Budování komplexních ekosystémů", icon: "🌿", isCorrect: true }, { text: "Monokultury", icon: "🌾", isCorrect: false }, { text: "Ničení přírody", icon: "❌", isCorrect: false }, { text: "Neexistuje", icon: "⛔", isCorrect: false }], explanation: "Ernst Götsch vyvinul systém regenerace degradovaných půd." },
        { question: "Holistic management:", type: "multiple_choice", options: [{ text: "Celostní přístup k řízení farem", icon: "🔄", isCorrect: true }, { text: "Pouze finance", icon: "💰", isCorrect: false }, { text: "Pouze zvířata", icon: "🐄", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Allan Savory vyvinul systém pro regeneraci krajiny pastvou." },
        { question: "Community Supported Agriculture:", type: "multiple_choice", options: [{ text: "Přímé partnerství farmářů a spotřebitelů", icon: "🤝", isCorrect: true }, { text: "Supermarket", icon: "🛒", isCorrect: false }, { text: "Vývoz", icon: "✈️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "CSA sdílí rizika a přínosy mezi farmáře a odběratele." }
    ],
    module6_level8: [
        { question: "Natura 2000 je:", type: "multiple_choice", options: [{ text: "Síť chráněných území EU", icon: "🌍", isCorrect: true }, { text: "Hnojivo", icon: "🧪", isCorrect: false }, { text: "Odrůda", icon: "🌱", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Natura 2000 chrání cenné biotopy a druhy." },
        { question: "AEKO opatření jsou:", type: "multiple_choice", options: [{ text: "Agroenvironmentální platby", icon: "💶", isCorrect: true }, { text: "Pesticidy", icon: "💦", isCorrect: false }, { text: "Hnojiva", icon: "🧪", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "AEKO odměňuje farmáře za environmentální služby." },
        { question: "Ekologické úhory jsou:", type: "multiple_choice", options: [{ text: "Plochy ponechané bez produkce", icon: "🌿", isCorrect: true }, { text: "Intenzivně využívané", icon: "🏭", isCorrect: false }, { text: "Zakázané", icon: "⛔", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Úhory poskytují úkryt a potravu pro volně žijící druhy." },
        { question: "Biopásy jsou:", type: "multiple_choice", options: [{ text: "Pásy s kvetoucími rostlinami", icon: "🌸", isCorrect: true }, { text: "Asfaltové cesty", icon: "🛣️", isCorrect: false }, { text: "Ploty", icon: "🚧", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Biopásy podporují opylovače a přirozené nepřátele." },
        { question: "Extenzivní louky:", type: "multiple_choice", options: [{ text: "Málo hnojené, druhově bohaté", icon: "🌼", isCorrect: true }, { text: "Intenzivně hnojené", icon: "🧪", isCorrect: false }, { text: "Bez rostlin", icon: "🏜️", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Extenzivní louky jsou refugia biodiverzity." },
        { question: "Remízky v krajině:", type: "multiple_choice", options: [{ text: "Ostrůvky keřů a stromů", icon: "🌳", isCorrect: true }, { text: "Pole obilí", icon: "🌾", isCorrect: false }, { text: "Skládky", icon: "🗑️", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Remízky poskytují úkryt zvěři a ptákům." },
        { question: "Zemědělství vysoké přírodní hodnoty:", type: "multiple_choice", options: [{ text: "HNV - hospodaření podporující biodiverzitu", icon: "🦋", isCorrect: true }, { text: "Intenzivní farmy", icon: "🏭", isCorrect: false }, { text: "Skleníky", icon: "🏠", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "HNV systémy jsou klíčové pro zachování biodiverzity." },
        { question: "Druhy vázané na zemědělství:", type: "multiple_choice", options: [{ text: "Koroptev, skřivan, čejka", icon: "🐦", isCorrect: true }, { text: "Pouze domácí zvířata", icon: "🐄", isCorrect: false }, { text: "Pouze škůdci", icon: "🐛", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Mnoho druhů závisí na tradičním hospodaření." },
        { question: "Intenzifikace ohrožuje:", type: "multiple_choice", options: [{ text: "Biodiverzitu a krajinný ráz", icon: "⚠️", isCorrect: true }, { text: "Nic", icon: "✅", isCorrect: false }, { text: "Pouze škůdce", icon: "🐛", isCorrect: false }, { text: "Pouze ekonomiku", icon: "💰", isCorrect: false }], explanation: "Jednotvárná krajina bez mezí ztrácí druhovou rozmanitost." },
        { question: "Rewilding je:", type: "multiple_choice", options: [{ text: "Návrat přírody do krajiny", icon: "🐺", isCorrect: true }, { text: "Intenzifikace", icon: "📈", isCorrect: false }, { text: "Urbanizace", icon: "🏙️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Rewilding obnovuje přírodní procesy a velké býložravce." }
    ],
    module6_level9: [
        { question: "Farm to Fork strategie EU:", type: "multiple_choice", options: [{ text: "Cesta k udržitelnému potravinovému systému", icon: "🍴", isCorrect: true }, { text: "Nový fast food", icon: "🍔", isCorrect: false }, { text: "Dopravní firma", icon: "🚛", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "F2F je součást Zelené dohody pro Evropu." },
        { question: "Green Deal cílí na:", type: "multiple_choice", options: [{ text: "Klimatickou neutralitu do 2050", icon: "🌍", isCorrect: true }, { text: "Více emisí", icon: "☁️", isCorrect: false }, { text: "Více chemie", icon: "🧪", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Zelená dohoda transformuje ekonomiku EU na udržitelnou." },
        { question: "Cíl 25% bio ploch do 2030:", type: "multiple_choice", options: [{ text: "Je součástí Farm to Fork", icon: "🌿", isCorrect: true }, { text: "Je nereálný", icon: "❌", isCorrect: false }, { text: "Byl zrušen", icon: "⛔", isCorrect: false }, { text: "Neexistuje", icon: "🤷", isCorrect: false }], explanation: "EU chce výrazně rozšířit ekologické zemědělství." },
        { question: "Snížení pesticidů o 50%:", type: "multiple_choice", options: [{ text: "Cíl EU do 2030", icon: "📉", isCorrect: true }, { text: "Zvýšení", icon: "📈", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze doporučení", icon: "🤷", isCorrect: false }], explanation: "EU plánuje dramaticky snížit používání pesticidů." },
        { question: "Taxonomie EU:", type: "multiple_choice", options: [{ text: "Klasifikace udržitelných aktivit", icon: "📋", isCorrect: true }, { text: "Daň", icon: "💰", isCorrect: false }, { text: "Hnojivo", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Taxonomie definuje, co je považováno za zelené investice." },
        { question: "CAP (Common Agricultural Policy):", type: "multiple_choice", options: [{ text: "Společná zemědělská politika EU", icon: "🇪🇺", isCorrect: true }, { text: "Typ klobouku", icon: "🧢", isCorrect: false }, { text: "Americká politika", icon: "🇺🇸", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "CAP rozděluje zemědělské dotace v EU." },
        { question: "Eco-schemes v nové CAP:", type: "multiple_choice", options: [{ text: "Dobrovolné ekologické závazky", icon: "🌿", isCorrect: true }, { text: "Povinné chemie", icon: "🧪", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Pouze pro bio", icon: "🌱", isCorrect: false }], explanation: "Eco-schemes odměňují farmáře za klimatická a environmentální opatření." },
        { question: "Conditionality v CAP:", type: "multiple_choice", options: [{ text: "Podmínky pro příjem dotací", icon: "📋", isCorrect: true }, { text: "Klimatizace", icon: "❄️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze pro velké farmy", icon: "🏭", isCorrect: false }], explanation: "Příjemci dotací musí splňovat základní standardy." },
        { question: "Carbon farming strategie:", type: "multiple_choice", options: [{ text: "Podpora ukládání uhlíku v zemědělství", icon: "🌍", isCorrect: true }, { text: "Spalování uhlí", icon: "🔥", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze lesy", icon: "🌲", isCorrect: false }], explanation: "EU připravuje certifikaci uhlíkových kreditů ze zemědělství." },
        { question: "Strategie pro biodiverzitu:", type: "multiple_choice", options: [{ text: "30% chráněných území do 2030", icon: "🦋", isCorrect: true }, { text: "Méně ochrany", icon: "📉", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze moře", icon: "🌊", isCorrect: false }], explanation: "EU chce výrazně rozšířit chráněná území." }
    ],
    module6_level10: [
        { question: "Udržitelné zemědělství musí:", type: "multiple_choice", options: [{ text: "Sladit produkci, ekologii a ekonomiku", icon: "⚖️", isCorrect: true }, { text: "Pouze maximalizovat zisk", icon: "💰", isCorrect: false }, { text: "Pouze chránit přírodu", icon: "🌿", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Tři pilíře udržitelnosti musí být v rovnováze." },
        { question: "Planetary boundaries:", type: "multiple_choice", options: [{ text: "Limity únosnosti planety", icon: "🌍", isCorrect: true }, { text: "Hranice států", icon: "🗺️", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Pouze teorie", icon: "📖", isCorrect: false }], explanation: "Překročení hranic ohrožuje stabilitu klimatu a ekosystémů." },
        { question: "Doughnut economics:", type: "multiple_choice", options: [{ text: "Model udržitelného rozvoje", icon: "🍩", isCorrect: true }, { text: "Cukrárna", icon: "🍰", isCorrect: false }, { text: "Typ farmy", icon: "🏡", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Kate Raworth navrhla model respektující sociální i ekologické limity." },
        { question: "True cost accounting:", type: "multiple_choice", options: [{ text: "Započítání všech nákladů včetně externalit", icon: "💰", isCorrect: true }, { text: "Pouze přímé náklady", icon: "📊", isCorrect: false }, { text: "Bez nákladů", icon: "❌", isCorrect: false }, { text: "Neexistuje", icon: "⛔", isCorrect: false }], explanation: "Skutečné náklady zahrnují dopady na zdraví a přírodu." },
        { question: "Agroekologická transformace:", type: "multiple_choice", options: [{ text: "Systémová změna potravinového systému", icon: "🔄", isCorrect: true }, { text: "Pouze technická změna", icon: "🔧", isCorrect: false }, { text: "Není možná", icon: "❌", isCorrect: false }, { text: "Pouze pro malé farmy", icon: "🏡", isCorrect: false }], explanation: "Transformace vyžaduje změny na všech úrovních systému." },
        { question: "Food sovereignty:", type: "multiple_choice", options: [{ text: "Právo komunit rozhodovat o svém jídle", icon: "🍽️", isCorrect: true }, { text: "Pouze dovoz", icon: "✈️", isCorrect: false }, { text: "Pouze vývoz", icon: "🚢", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Potravinová suverenita podporuje lokální systémy a tradice." },
        { question: "Planetary diet:", type: "multiple_choice", options: [{ text: "Strava zdravá pro lidi i planetu", icon: "🥗", isCorrect: true }, { text: "Jídlo z vesmíru", icon: "🚀", isCorrect: false }, { text: "Pouze maso", icon: "🥩", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "EAT-Lancet komise navrhla udržitelnou referenční stravu." },
        { question: "Lokální potravinové systémy:", type: "multiple_choice", options: [{ text: "Snižují emise z dopravy a posilují komunity", icon: "🏘️", isCorrect: true }, { text: "Jsou dražší vždy", icon: "💰", isCorrect: false }, { text: "Jsou nemožné", icon: "❌", isCorrect: false }, { text: "Pouze pro bohaté", icon: "💎", isCorrect: false }], explanation: "Lokální systémy mají mnoho sociálních a ekologických výhod." },
        { question: "One Health přístup:", type: "multiple_choice", options: [{ text: "Propojení zdraví lidí, zvířat a ekosystémů", icon: "🔗", isCorrect: true }, { text: "Pouze lidské zdraví", icon: "👤", isCorrect: false }, { text: "Pouze veterina", icon: "🐄", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Zdraví všech je propojeno a vyžaduje holistický přístup." },
        { question: "Budoucnost zemědělství:", type: "multiple_choice", options: [{ text: "Regenerativní, precizní, lokální, spravedlivé", icon: "🌱", isCorrect: true }, { text: "Více chemie", icon: "🧪", isCorrect: false }, { text: "Bez farmářů", icon: "🤖", isCorrect: false }, { text: "Žádná", icon: "❌", isCorrect: false }], explanation: "Udržitelná budoucnost vyžaduje transformaci celého systému." }
    ]
};
