// Modul 4: Zavlažování - 100 otázek (10 levelů x 10 otázek)
const MODULE4_QUESTIONS = {
    // Level 1 - Základy zavlažování
    module4_level1: [
        { question: "Proč je voda důležitá pro rostliny?", type: "multiple_choice", options: [{ text: "Pro fotosyntézu a transport živin", icon: "💧", isCorrect: true }, { text: "Pouze pro chlazení", icon: "❄️", isCorrect: false }, { text: "Pouze pro vzhled", icon: "🎨", isCorrect: false }, { text: "Není důležitá", icon: "❌", isCorrect: false }], explanation: "Voda je nezbytná pro fotosyntézu, transport živin a regulaci teploty rostlin." },
        { question: "Kolik vody rostliny spotřebují?", type: "multiple_choice", options: [{ text: "Závisí na druhu a podmínkách", icon: "📊", isCorrect: true }, { text: "Vždy stejně", icon: "➡️", isCorrect: false }, { text: "Velmi málo", icon: "💧", isCorrect: false }, { text: "Nic", icon: "0️⃣", isCorrect: false }], explanation: "Spotřeba vody závisí na druhu rostliny, teplotě, vlhkosti a fázi růstu." },
        { question: "Co je evapotranspirace?", type: "multiple_choice", options: [{ text: "Výpar z půdy a rostlin", icon: "☁️", isCorrect: true }, { text: "Pouze déšť", icon: "🌧️", isCorrect: false }, { text: "Druh hnojiva", icon: "🧪", isCorrect: false }, { text: "Typ půdy", icon: "🌍", isCorrect: false }], explanation: "Evapotranspirace je součet evaporace (výpar z půdy) a transpirace (výpar z rostlin)." },
        { question: "Kdy rostliny potřebují nejvíce vody?", type: "multiple_choice", options: [{ text: "V období růstu a kvetení", icon: "🌸", isCorrect: true }, { text: "V zimě", icon: "❄️", isCorrect: false }, { text: "Při sklizni", icon: "🌾", isCorrect: false }, { text: "Nikdy", icon: "⛔", isCorrect: false }], explanation: "Kritická období jsou klíčení, odnožování, kvetení a nalévání zrna." },
        { question: "Co je deficit vody?", type: "multiple_choice", options: [{ text: "Nedostatek vody pro optimální růst", icon: "🏜️", isCorrect: true }, { text: "Přebytek vody", icon: "💦", isCorrect: false }, { text: "Správné množství", icon: "✅", isCorrect: false }, { text: "Druh závlahy", icon: "💧", isCorrect: false }], explanation: "Vodní deficit způsobuje stres rostlin, vadnutí a snížení výnosů." },
        { question: "Co je zavlažování?", type: "multiple_choice", options: [{ text: "Umělý přívod vody k rostlinám", icon: "💦", isCorrect: true }, { text: "Pouze déšť", icon: "🌧️", isCorrect: false }, { text: "Odvodnění", icon: "⬇️", isCorrect: false }, { text: "Hnojení", icon: "🧪", isCorrect: false }], explanation: "Zavlažování doplňuje přirozené srážky pro zajištění dostatku vody." },
        { question: "Jaké jsou zdroje vody pro zavlažování?", type: "multiple_choice", options: [{ text: "Řeky, studny, nádrže, přehrady", icon: "🏞️", isCorrect: true }, { text: "Pouze déšť", icon: "🌧️", isCorrect: false }, { text: "Pouze moře", icon: "🌊", isCorrect: false }, { text: "Pouze led", icon: "🧊", isCorrect: false }], explanation: "Voda se čerpá z povrchových i podzemních zdrojů, ukládá v nádržích." },
        { question: "Co je vodní stres?", type: "multiple_choice", options: [{ text: "Stav rostliny při nedostatku vody", icon: "🥀", isCorrect: true }, { text: "Stres z přebytku vody", icon: "💦", isCorrect: false }, { text: "Stres farmáře", icon: "😰", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Vodní stres způsobuje uzavírání průduchů, zpomalení růstu a vadnutí." },
        { question: "Jak poznat, že rostlina potřebuje vodu?", type: "multiple_choice", options: [{ text: "Vadnutí, ztráta turgoru listů", icon: "🍂", isCorrect: true }, { text: "Rychlý růst", icon: "📈", isCorrect: false }, { text: "Zelené listy", icon: "🌿", isCorrect: false }, { text: "Kvetení", icon: "🌸", isCorrect: false }], explanation: "Vadnoucí listy a ztráta turgoru jsou prvními příznaky nedostatku vody." },
        { question: "Co je půdní vlhkost?", type: "multiple_choice", options: [{ text: "Množství vody v půdě", icon: "💧", isCorrect: true }, { text: "Teplota půdy", icon: "🌡️", isCorrect: false }, { text: "Barva půdy", icon: "🎨", isCorrect: false }, { text: "pH půdy", icon: "📊", isCorrect: false }], explanation: "Půdní vlhkost určuje dostupnost vody pro kořeny rostlin." }
    ],

    // Level 2 - Typy zavlažování
    module4_level2: [
        { question: "Co je povrchové zavlažování?", type: "multiple_choice", options: [{ text: "Voda teče po povrchu půdy", icon: "🌊", isCorrect: true }, { text: "Voda z nebe", icon: "🌧️", isCorrect: false }, { text: "Podzemní voda", icon: "⬇️", isCorrect: false }, { text: "Kapková závlaha", icon: "💧", isCorrect: false }], explanation: "Povrchová závlaha využívá gravitaci k rozvodu vody po poli." },
        { question: "Kapková závlaha dodává vodu:", type: "multiple_choice", options: [{ text: "Přímo ke kořenům rostlin", icon: "🎯", isCorrect: true }, { text: "Na listy", icon: "🍃", isCorrect: false }, { text: "Do vzduchu", icon: "💨", isCorrect: false }, { text: "Na cestu", icon: "🛣️", isCorrect: false }], explanation: "Kapková závlaha je nejúspornější - dodává vodu přesně tam, kde je potřeba." },
        { question: "Postřikovací závlaha napodobuje:", type: "multiple_choice", options: [{ text: "Déšť", icon: "🌧️", isCorrect: true }, { text: "Sníh", icon: "❄️", isCorrect: false }, { text: "Mlhu", icon: "🌫️", isCorrect: false }, { text: "Vítr", icon: "💨", isCorrect: false }], explanation: "Postřikovače vytvářejí umělý déšť rozprašováním vody do vzduchu." },
        { question: "Pivot je:", type: "multiple_choice", options: [{ text: "Kruhový zavlažovací systém", icon: "⭕", isCorrect: true }, { text: "Druh traktoru", icon: "🚜", isCorrect: false }, { text: "Typ půdy", icon: "🌍", isCorrect: false }, { text: "Hnojivo", icon: "🧪", isCorrect: false }], explanation: "Pivot je závlahové rameno otáčející se kolem centrálního bodu." },
        { question: "Podpovrchová závlaha:", type: "multiple_choice", options: [{ text: "Dodává vodu pod povrchem", icon: "⬇️", isCorrect: true }, { text: "Pouze postřikuje", icon: "💦", isCorrect: false }, { text: "Používá helikoptéru", icon: "🚁", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Podpovrchové hadice dodávají vodu přímo do kořenové zóny." },
        { question: "Mikrozávlaha je vhodná pro:", type: "multiple_choice", options: [{ text: "Zeleninu, sady, skleníky", icon: "🌿", isCorrect: true }, { text: "Velká pole obilí", icon: "🌾", isCorrect: false }, { text: "Pouze trávníky", icon: "🏡", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Mikrozávlaha je přesná a vhodná pro intenzivní kultury." },
        { question: "Výhoda kapkové závlahy je:", type: "multiple_choice", options: [{ text: "Vysoká účinnost využití vody", icon: "✅", isCorrect: true }, { text: "Nízká cena", icon: "💰", isCorrect: false }, { text: "Jednoduchost", icon: "😊", isCorrect: false }, { text: "Nevyžaduje údržbu", icon: "🔧", isCorrect: false }], explanation: "Kapková závlaha má účinnost až 95%, minimalizuje ztráty." },
        { question: "Nevýhoda postřikovačů je:", type: "multiple_choice", options: [{ text: "Ztráty odparem a větrem", icon: "💨", isCorrect: true }, { text: "Příliš přesná", icon: "🎯", isCorrect: false }, { text: "Příliš levná", icon: "💰", isCorrect: false }, { text: "Žádná", icon: "✅", isCorrect: false }], explanation: "Postřikovače ztrácejí vodu odparem a úletem za větrného počasí." },
        { question: "Fertrigace je:", type: "multiple_choice", options: [{ text: "Hnojení přes závlahový systém", icon: "🧪", isCorrect: true }, { text: "Fermentace hnojiv", icon: "🦠", isCorrect: false }, { text: "Druh postřikovače", icon: "💦", isCorrect: false }, { text: "Typ pumpy", icon: "⚙️", isCorrect: false }], explanation: "Fertrigace kombinuje zavlažování s aplikací rozpustných hnojiv." },
        { question: "Závlahová dávka je:", type: "multiple_choice", options: [{ text: "Množství vody na jeden zálivek", icon: "📊", isCorrect: true }, { text: "Cena vody", icon: "💰", isCorrect: false }, { text: "Druh hadice", icon: "🔧", isCorrect: false }, { text: "Typ postřikovače", icon: "💦", isCorrect: false }], explanation: "Závlahová dávka se uvádí v mm nebo l/m² a závisí na potřebě rostlin." }
    ],

    // Level 3 - Plánování závlahy
    module4_level3: [
        { question: "Co ovlivňuje potřebu závlahy?", type: "multiple_choice", options: [{ text: "Počasí, plodina, půda, fáze růstu", icon: "📊", isCorrect: true }, { text: "Pouze počasí", icon: "🌤️", isCorrect: false }, { text: "Pouze typ rostliny", icon: "🌱", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Potřeba závlahy závisí na mnoha faktorech, které se mění v čase." },
        { question: "ETc je:", type: "multiple_choice", options: [{ text: "Evapotranspirace plodiny", icon: "☁️", isCorrect: true }, { text: "Druh pumpy", icon: "⚙️", isCorrect: false }, { text: "Typ hadice", icon: "🔧", isCorrect: false }, { text: "Zkratka firmy", icon: "🏢", isCorrect: false }], explanation: "ETc je skutečná evapotranspirace konkrétní plodiny." },
        { question: "Referenční evapotranspirace (ETo) se měří:", type: "multiple_choice", options: [{ text: "Pomocí meteorologických dat", icon: "🌡️", isCorrect: true }, { text: "Očima", icon: "👀", isCorrect: false }, { text: "Pomocí váhy", icon: "⚖️", isCorrect: false }, { text: "Neměří se", icon: "❌", isCorrect: false }], explanation: "ETo se počítá z teploty, vlhkosti, větru a záření." },
        { question: "Koeficient plodiny (Kc) udává:", type: "multiple_choice", options: [{ text: "Poměr spotřeby vody plodiny k ETo", icon: "📐", isCorrect: true }, { text: "Cenu plodiny", icon: "💰", isCorrect: false }, { text: "Výnos plodiny", icon: "🌾", isCorrect: false }, { text: "Barvu plodiny", icon: "🎨", isCorrect: false }], explanation: "Kc se mění během vegetace - jiný je při vzcházení a při kvetení." },
        { question: "Půdní senzory měří:", type: "multiple_choice", options: [{ text: "Vlhkost půdy v reálném čase", icon: "📱", isCorrect: true }, { text: "Pouze teplotu", icon: "🌡️", isCorrect: false }, { text: "Pouze pH", icon: "📊", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Senzory pomáhají optimalizovat termín a dávku závlahy." },
        { question: "Tenziometr měří:", type: "multiple_choice", options: [{ text: "Sací tlak vody v půdě", icon: "📏", isCorrect: true }, { text: "Tlak vzduchu", icon: "💨", isCorrect: false }, { text: "Teplotu", icon: "🌡️", isCorrect: false }, { text: "pH", icon: "📊", isCorrect: false }], explanation: "Tenziometr ukazuje, jak snadno mohou rostliny čerpat vodu z půdy." },
        { question: "Bilance vody na poli zahrnuje:", type: "multiple_choice", options: [{ text: "Srážky + závlaha - evapotranspirace - odtok", icon: "⚖️", isCorrect: true }, { text: "Pouze srážky", icon: "🌧️", isCorrect: false }, { text: "Pouze závlahu", icon: "💦", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Vodní bilance pomáhá plánovat závlahu podle skutečné potřeby." },
        { question: "Kritická období pro závlahu obilovin jsou:", type: "multiple_choice", options: [{ text: "Odnožování, sloupkování, kvetení", icon: "🌾", isCorrect: true }, { text: "Pouze po sklizni", icon: "✂️", isCorrect: false }, { text: "V zimě", icon: "❄️", isCorrect: false }, { text: "Nikdy", icon: "⛔", isCorrect: false }], explanation: "Nedostatek vody v kritických obdobích výrazně snižuje výnos." },
        { question: "Deficit irrigation je:", type: "multiple_choice", options: [{ text: "Záměrně omezená závlaha pro úsporu", icon: "💧", isCorrect: true }, { text: "Nadměrná závlaha", icon: "💦", isCorrect: false }, { text: "Žádná závlaha", icon: "⛔", isCorrect: false }, { text: "Typ pumpy", icon: "⚙️", isCorrect: false }], explanation: "Řízený deficit může šetřit vodu bez velkého dopadu na výnos." },
        { question: "Automatické řízení závlahy využívá:", type: "multiple_choice", options: [{ text: "Senzory, počítače, předpověď počasí", icon: "🖥️", isCorrect: true }, { text: "Pouze manuální ovládání", icon: "✋", isCorrect: false }, { text: "Pouze časovač", icon: "⏰", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Chytré systémy optimalizují závlahu na základě aktuálních dat." }
    ],

    // Level 4 - Závlahová technika
    module4_level4: [
        { question: "Čerpadlo slouží k:", type: "multiple_choice", options: [{ text: "Dopravě vody ze zdroje", icon: "⚙️", isCorrect: true }, { text: "Filtraci vody", icon: "🔍", isCorrect: false }, { text: "Ohřevu vody", icon: "🔥", isCorrect: false }, { text: "Měření vody", icon: "📏", isCorrect: false }], explanation: "Čerpadla vytvářejí tlak potřebný pro rozvod vody systémem." },
        { question: "Filtrace vody je důležitá pro:", type: "multiple_choice", options: [{ text: "Prevenci ucpání kapkovačů", icon: "🔧", isCorrect: true }, { text: "Lepší chuť", icon: "😋", isCorrect: false }, { text: "Ohřev", icon: "🔥", isCorrect: false }, { text: "Není důležitá", icon: "❌", isCorrect: false }], explanation: "Čistá voda zabraňuje ucpávání emitorů a prodlužuje životnost systému." },
        { question: "Kapkovač (emitor) vydává:", type: "multiple_choice", options: [{ text: "Přesné množství vody za hodinu", icon: "💧", isCorrect: true }, { text: "Neomezené množství", icon: "🌊", isCorrect: false }, { text: "Pouze vzduch", icon: "💨", isCorrect: false }, { text: "Hnojivo", icon: "🧪", isCorrect: false }], explanation: "Kapkovače mají definovaný průtok, např. 2 nebo 4 l/hod." },
        { question: "Tlak v systému se měří v:", type: "multiple_choice", options: [{ text: "Barech nebo kPa", icon: "📊", isCorrect: true }, { text: "Litrech", icon: "🥛", isCorrect: false }, { text: "Metrech", icon: "📏", isCorrect: false }, { text: "Hodinách", icon: "⏰", isCorrect: false }], explanation: "Správný tlak je klíčový pro rovnoměrné zavlažování." },
        { question: "Redukční ventil:", type: "multiple_choice", options: [{ text: "Snižuje tlak vody", icon: "⬇️", isCorrect: true }, { text: "Zvyšuje tlak", icon: "⬆️", isCorrect: false }, { text: "Měří průtok", icon: "📊", isCorrect: false }, { text: "Filtruje vodu", icon: "🔍", isCorrect: false }], explanation: "Redukční ventily zajišťují optimální tlak pro kapkovače." },
        { question: "PE hadice se používá pro:", type: "multiple_choice", options: [{ text: "Rozvod vody v závlaze", icon: "🔧", isCorrect: true }, { text: "Elektrické vedení", icon: "⚡", isCorrect: false }, { text: "Odvod vzduchu", icon: "💨", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Polyethylenové hadice jsou standardem pro kapkové závlahy." },
        { question: "Vodoměr měří:", type: "multiple_choice", options: [{ text: "Spotřebu vody", icon: "📊", isCorrect: true }, { text: "Tlak vody", icon: "📏", isCorrect: false }, { text: "Teplotu vody", icon: "🌡️", isCorrect: false }, { text: "Kvalitu vody", icon: "✅", isCorrect: false }], explanation: "Vodoměr je důležitý pro sledování spotřeby a plánování." },
        { question: "Elektromagnetický ventil:", type: "multiple_choice", options: [{ text: "Umožňuje automatické ovládání", icon: "🔌", isCorrect: true }, { text: "Vyrábí elektřinu", icon: "⚡", isCorrect: false }, { text: "Filtruje vodu", icon: "🔍", isCorrect: false }, { text: "Měří průtok", icon: "📊", isCorrect: false }], explanation: "Elektroventily se ovládají řídicí jednotkou podle programu." },
        { question: "Řídicí jednotka závlahy:", type: "multiple_choice", options: [{ text: "Automaticky spouští a vypíná závlahu", icon: "🖥️", isCorrect: true }, { text: "Pouze měří", icon: "📊", isCorrect: false }, { text: "Pouze filtruje", icon: "🔍", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Řídicí jednotka může být programována na základě času nebo senzorů." },
        { question: "Zpětný ventil brání:", type: "multiple_choice", options: [{ text: "Zpětnému toku vody", icon: "⛔", isCorrect: true }, { text: "Průtoku vody", icon: "💧", isCorrect: false }, { text: "Filtraci", icon: "🔍", isCorrect: false }, { text: "Měření", icon: "📊", isCorrect: false }], explanation: "Zpětný ventil chrání zdroj vody před kontaminací." }
    ],

    // Level 5 - Kvalita závlahové vody
    module4_level5: [
        { question: "Kvalita závlahové vody ovlivňuje:", type: "multiple_choice", options: [{ text: "Zdraví rostlin i půdy", icon: "🌱", isCorrect: true }, { text: "Pouze barvu rostlin", icon: "🎨", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze cenu", icon: "💰", isCorrect: false }], explanation: "Nevhodná voda může poškodit rostliny, zasolit půdu nebo ucpat systém." },
        { question: "EC vody udává:", type: "multiple_choice", options: [{ text: "Elektrickou vodivost (soli)", icon: "⚡", isCorrect: true }, { text: "Teplotu", icon: "🌡️", isCorrect: false }, { text: "Barvu", icon: "🎨", isCorrect: false }, { text: "Tlak", icon: "📏", isCorrect: false }], explanation: "Vyšší EC znamená více rozpuštěných solí, což může být problém." },
        { question: "Tvrdá voda obsahuje:", type: "multiple_choice", options: [{ text: "Vápník a hořčík", icon: "⚪", isCorrect: true }, { text: "Pouze železo", icon: "⚙️", isCorrect: false }, { text: "Pouze sodík", icon: "🧂", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Tvrdá voda může způsobovat usazeniny a ucpávání kapkovačů." },
        { question: "Sodná voda je problematická, protože:", type: "multiple_choice", options: [{ text: "Poškozuje strukturu půdy", icon: "🌍", isCorrect: true }, { text: "Je drahá", icon: "💰", isCorrect: false }, { text: "Má špatnou barvu", icon: "🎨", isCorrect: false }, { text: "Nic", icon: "✅", isCorrect: false }], explanation: "Sodík rozbíjí půdní agregáty a zhoršuje propustnost půdy." },
        { question: "SAR je ukazatel:", type: "multiple_choice", options: [{ text: "Sodíkového nebezpečí pro půdu", icon: "⚠️", isCorrect: true }, { text: "Teploty vody", icon: "🌡️", isCorrect: false }, { text: "Tlaku vody", icon: "📏", isCorrect: false }, { text: "Barvy vody", icon: "🎨", isCorrect: false }], explanation: "Sodium Adsorption Ratio hodnotí riziko sodíkové degradace půdy." },
        { question: "Chlor ve vodě může:", type: "multiple_choice", options: [{ text: "Poškodit citlivé rostliny", icon: "🥀", isCorrect: true }, { text: "Vždy pomáhat", icon: "✅", isCorrect: false }, { text: "Nic nedělat", icon: "❌", isCorrect: false }, { text: "Zlepšit chuť plodů", icon: "😋", isCorrect: false }], explanation: "Vysoké koncentrace chloru způsobují spálení okrajů listů." },
        { question: "pH závlahové vody by mělo být:", type: "multiple_choice", options: [{ text: "6,0-7,5", icon: "⚖️", isCorrect: true }, { text: "Pod 4", icon: "📉", isCorrect: false }, { text: "Nad 10", icon: "📈", isCorrect: false }, { text: "Nezáleží", icon: "🤷", isCorrect: false }], explanation: "Extrémní pH ovlivňuje dostupnost živin a může poškodit systém." },
        { question: "Železo ve vodě způsobuje:", type: "multiple_choice", options: [{ text: "Ucpávání emitorů", icon: "🔧", isCorrect: true }, { text: "Lepší růst", icon: "📈", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Čistší vodu", icon: "💧", isCorrect: false }], explanation: "Rozpuštěné železo oxiduje a vytváří usazeniny v systému." },
        { question: "Biologická kontaminace vody zahrnuje:", type: "multiple_choice", options: [{ text: "Řasy, bakterie, biofilm", icon: "🦠", isCorrect: true }, { text: "Pouze písek", icon: "🏖️", isCorrect: false }, { text: "Pouze kameny", icon: "🪨", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Organické látky a mikroorganismy mohou ucpávat kapkovače." },
        { question: "Chlorování závlahové vody:", type: "multiple_choice", options: [{ text: "Dezinfikuje a čistí systém", icon: "🧪", isCorrect: true }, { text: "Je zakázáno", icon: "⛔", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }, { text: "Škodí vždy", icon: "☠️", isCorrect: false }], explanation: "Občasné chlorování odstraňuje biofilm a bakterie ze systému." }
    ],

    // Level 6 - Úspora vody
    module4_level6: [
        { question: "Proč šetřit vodou při zavlažování?", type: "multiple_choice", options: [{ text: "Voda je omezený zdroj a náklad", icon: "💧", isCorrect: true }, { text: "Není důvod", icon: "❌", isCorrect: false }, { text: "Rostliny vodu nepotřebují", icon: "🌱", isCorrect: false }, { text: "Je vždy zadarmo", icon: "💰", isCorrect: false }], explanation: "Efektivní využití vody šetří náklady i přírodní zdroje." },
        { question: "Mulčování snižuje:", type: "multiple_choice", options: [{ text: "Výpar vody z půdy", icon: "☁️", isCorrect: true }, { text: "Růst rostlin", icon: "📉", isCorrect: false }, { text: "Kvalitu plodů", icon: "🍎", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Mulč vytváří bariéru, která omezuje evaporaci z povrchu půdy." },
        { question: "Zavlažování v noci je výhodnější, protože:", type: "multiple_choice", options: [{ text: "Méně odparu a větru", icon: "🌙", isCorrect: true }, { text: "Rostliny spí", icon: "😴", isCorrect: false }, { text: "Je to levnější", icon: "💰", isCorrect: false }, { text: "Není výhodnější", icon: "❌", isCorrect: false }], explanation: "Nižší teploty a klid vzduchu minimalizují ztráty vody." },
        { question: "Kapková závlaha oproti postřiku ušetří:", type: "multiple_choice", options: [{ text: "30-50% vody", icon: "💧", isCorrect: true }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Spotřebuje více", icon: "📈", isCorrect: false }, { text: "5% vody", icon: "💧", isCorrect: false }], explanation: "Kapková závlaha má účinnost až 95% oproti 60-70% u postřiku." },
        { question: "Recyklace odpadní vody je:", type: "multiple_choice", options: [{ text: "Možná po úpravě pro zavlažování", icon: "♻️", isCorrect: true }, { text: "Zakázaná", icon: "⛔", isCorrect: false }, { text: "Nemožná", icon: "❌", isCorrect: false }, { text: "Nebezpečná vždy", icon: "☠️", isCorrect: false }], explanation: "Vyčištěná odpadní voda může být zdrojem pro zavlažování." },
        { question: "Zachycování dešťové vody:", type: "multiple_choice", options: [{ text: "Snižuje potřebu jiných zdrojů", icon: "🌧️", isCorrect: true }, { text: "Je zakázáno", icon: "⛔", isCorrect: false }, { text: "Je zbytečné", icon: "❌", isCorrect: false }, { text: "Škodí rostlinám", icon: "☠️", isCorrect: false }], explanation: "Dešťová voda je kvalitní a levný zdroj pro závlahu." },
        { question: "Precizní závlaha využívá:", type: "multiple_choice", options: [{ text: "Senzory a data pro optimalizaci", icon: "📊", isCorrect: true }, { text: "Pouze odhad", icon: "🤔", isCorrect: false }, { text: "Náhodné zalévání", icon: "🎲", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Precizní závlaha aplikuje vodu jen tam, kde je skutečně potřeba." },
        { question: "Sucho-tolerantní odrůdy:", type: "multiple_choice", options: [{ text: "Vyžadují méně vody", icon: "🌵", isCorrect: true }, { text: "Vyžadují více vody", icon: "💦", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Jsou horší kvalitou", icon: "📉", isCorrect: false }], explanation: "Šlechtění na suchovzdornost snižuje závlahovou potřebu." },
        { question: "Správné načasování závlahy:", type: "multiple_choice", options: [{ text: "Minimalizuje ztráty a maximalizuje efekt", icon: "⏰", isCorrect: true }, { text: "Není důležité", icon: "❌", isCorrect: false }, { text: "Zvyšuje spotřebu", icon: "📈", isCorrect: false }, { text: "Závisí na barvě hadice", icon: "🎨", isCorrect: false }], explanation: "Zavlažování v pravý čas a v pravém množství je klíčem k úspoře." },
        { question: "Deficit irrigation může:", type: "multiple_choice", options: [{ text: "Ušetřit vodu při minimálním dopadu na výnos", icon: "💧", isCorrect: true }, { text: "Vždy zvýšit výnos", icon: "📈", isCorrect: false }, { text: "Zničit úrodu", icon: "☠️", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Řízený stres v některých fázích může zlepšit kvalitu a ušetřit vodu." }
    ],

    // Level 7 - Závlaha specifických plodin
    module4_level7: [
        { question: "Rajčata potřebují:", type: "multiple_choice", options: [{ text: "Pravidelnou závlahu bez stresu", icon: "🍅", isCorrect: true }, { text: "Žádnou vodu", icon: "🏜️", isCorrect: false }, { text: "Pouze déšť", icon: "🌧️", isCorrect: false }, { text: "Slanou vodu", icon: "🧂", isCorrect: false }], explanation: "Nepravidelná závlaha rajčat způsobuje praskání plodů." },
        { question: "Vinná réva při deficitní závlaze:", type: "multiple_choice", options: [{ text: "Může mít lepší kvalitu vína", icon: "🍇", isCorrect: true }, { text: "Vždy uhyne", icon: "☠️", isCorrect: false }, { text: "Nemá žádný efekt", icon: "❌", isCorrect: false }, { text: "Ztratí listy", icon: "🍂", isCorrect: false }], explanation: "Mírný stres koncentruje cukry a aromatické látky v hroznech." },
        { question: "Kukuřice je na vodu kritická v:", type: "multiple_choice", options: [{ text: "Období metání a kvetení", icon: "🌽", isCorrect: true }, { text: "Po sklizni", icon: "✂️", isCorrect: false }, { text: "V zimě", icon: "❄️", isCorrect: false }, { text: "Nikdy", icon: "⛔", isCorrect: false }], explanation: "Nedostatek vody při kvetení způsobuje špatné opylení a prázdné klasy." },
        { question: "Brambory vyžadují:", type: "multiple_choice", options: [{ text: "Rovnoměrnou vlhkost pro kvalitní hlízy", icon: "🥔", isCorrect: true }, { text: "Sucho", icon: "🏜️", isCorrect: false }, { text: "Zaplavení", icon: "🌊", isCorrect: false }, { text: "Slanou vodu", icon: "🧂", isCorrect: false }], explanation: "Kolísání vlhkosti způsobuje praskliny a deformace hlíz." },
        { question: "Ovocné stromy mají kritické období:", type: "multiple_choice", options: [{ text: "Při kvetení a nalévání plodů", icon: "🍎", isCorrect: true }, { text: "V zimě", icon: "❄️", isCorrect: false }, { text: "Po sklizni pouze", icon: "✂️", isCorrect: false }, { text: "Nikdy", icon: "⛔", isCorrect: false }], explanation: "Nedostatek vody v kritických fázích snižuje velikost a kvalitu plodů." },
        { question: "Salát potřebuje:", type: "multiple_choice", options: [{ text: "Častou, mírnou závlahu", icon: "🥬", isCorrect: true }, { text: "Žádnou vodu", icon: "🏜️", isCorrect: false }, { text: "Pouze postřik listů", icon: "💦", isCorrect: false }, { text: "Horkou vodu", icon: "🔥", isCorrect: false }], explanation: "Salát má mělké kořeny a vyžaduje stálou vlhkost povrchu." },
        { question: "Cibule a česnek:", type: "multiple_choice", options: [{ text: "Potřebují sucho před sklizní", icon: "🧅", isCorrect: true }, { text: "Potřebují vodu až do sklizně", icon: "💧", isCorrect: false }, { text: "Nepotřebují vodu", icon: "🏜️", isCorrect: false }, { text: "Milují záplavy", icon: "🌊", isCorrect: false }], explanation: "Sucho před sklizní zlepšuje skladovatelnost cibulové zeleniny." },
        { question: "Pšenice je na sucho nejcitlivější:", type: "multiple_choice", options: [{ text: "Při sloupkování a nalévání zrna", icon: "🌾", isCorrect: true }, { text: "Po sklizni", icon: "✂️", isCorrect: false }, { text: "V zimě", icon: "❄️", isCorrect: false }, { text: "Při setí", icon: "🌰", isCorrect: false }], explanation: "Sucho v kritických fázích výrazně snižuje výnos a kvalitu zrna." },
        { question: "Jahody vyžadují:", type: "multiple_choice", options: [{ text: "Kapkovou závlahu pro kvalitní plody", icon: "🍓", isCorrect: true }, { text: "Postřik na plody", icon: "💦", isCorrect: false }, { text: "Záplavu", icon: "🌊", isCorrect: false }, { text: "Žádnou vodu", icon: "🏜️", isCorrect: false }], explanation: "Mokré plody jahod jsou náchylné ke hnilobě, kapkovka je ideální." },
        { question: "Rýže se pěstuje:", type: "multiple_choice", options: [{ text: "Zaplavením polí vodou", icon: "🌾", isCorrect: true }, { text: "V poušti", icon: "🏜️", isCorrect: false }, { text: "Bez vody", icon: "❌", isCorrect: false }, { text: "Kapkovou závlahou", icon: "💧", isCorrect: false }], explanation: "Rýže tradičně roste v zaplavených polích, existují i úspornější metody." }
    ],

    // Level 8 - Problémy a údržba
    module4_level8: [
        { question: "Ucpání kapkovačů způsobuje:", type: "multiple_choice", options: [{ text: "Nerovnoměrnou závlahu", icon: "🔧", isCorrect: true }, { text: "Lepší růst", icon: "📈", isCorrect: false }, { text: "Úsporu vody", icon: "💧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Ucpané kapkovače znamenají, že některé rostliny nedostávají vodu." },
        { question: "Proplach systému se dělá:", type: "multiple_choice", options: [{ text: "Pravidelně pro odstranění usazenin", icon: "🔄", isCorrect: true }, { text: "Nikdy", icon: "⛔", isCorrect: false }, { text: "Pouze při instalaci", icon: "🔧", isCorrect: false }, { text: "Jen při poruše", icon: "❌", isCorrect: false }], explanation: "Pravidelné proplachování prodlužuje životnost systému." },
        { question: "Netěsnost v systému:", type: "multiple_choice", options: [{ text: "Způsobuje ztráty vody a tlaku", icon: "💦", isCorrect: true }, { text: "Je žádoucí", icon: "✅", isCorrect: false }, { text: "Nic nezpůsobuje", icon: "❌", isCorrect: false }, { text: "Zlepšuje závlahu", icon: "📈", isCorrect: false }], explanation: "Netěsnosti je třeba okamžitě opravit pro zachování účinnosti." },
        { question: "Filtry je třeba:", type: "multiple_choice", options: [{ text: "Pravidelně čistit nebo měnit", icon: "🔧", isCorrect: true }, { text: "Nikdy nečistit", icon: "⛔", isCorrect: false }, { text: "Vyhodit", icon: "🗑️", isCorrect: false }, { text: "Ignorovat", icon: "🙈", isCorrect: false }], explanation: "Zanesené filtry snižují průtok a tlak v systému." },
        { question: "Zazimování systému zahrnuje:", type: "multiple_choice", options: [{ text: "Vypuštění vody před mrazy", icon: "❄️", isCorrect: true }, { text: "Pouze vypnutí", icon: "🔌", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Zalití vodou", icon: "💧", isCorrect: false }], explanation: "Voda v potrubí by zamrzla a poškodila systém." },
        { question: "Kontrola tlaku se provádí:", type: "multiple_choice", options: [{ text: "Manometrem na různých místech", icon: "📊", isCorrect: true }, { text: "Pohledem", icon: "👀", isCorrect: false }, { text: "Poslechem", icon: "👂", isCorrect: false }, { text: "Čichem", icon: "👃", isCorrect: false }], explanation: "Pokles tlaku indikuje netěsnost nebo ucpání." },
        { question: "Hlodavci mohou:", type: "multiple_choice", options: [{ text: "Prokousat hadice", icon: "🐀", isCorrect: true }, { text: "Zlepšit systém", icon: "📈", isCorrect: false }, { text: "Nic nedělat", icon: "❌", isCorrect: false }, { text: "Čistit filtry", icon: "🔧", isCorrect: false }], explanation: "Ochrana před hlodavci je důležitá zejména u podpovrchové závlahy." },
        { question: "UV záření poškozuje:", type: "multiple_choice", options: [{ text: "Plastové komponenty", icon: "☀️", isCorrect: true }, { text: "Pouze vodu", icon: "💧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze kov", icon: "⚙️", isCorrect: false }], explanation: "Hadice vystavené slunci degradují rychleji." },
        { question: "Chemické čištění systému:", type: "multiple_choice", options: [{ text: "Odstraňuje usazeniny a biofilm", icon: "🧪", isCorrect: true }, { text: "Je zakázáno", icon: "⛔", isCorrect: false }, { text: "Škodí vždy", icon: "☠️", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Kyselé nebo oxidační přípravky čistí ucpané kapkovače." },
        { question: "Záruční doba závlahových systémů je obvykle:", type: "multiple_choice", options: [{ text: "1-5 let podle komponentu", icon: "📅", isCorrect: true }, { text: "Navždy", icon: "♾️", isCorrect: false }, { text: "1 den", icon: "📆", isCorrect: false }, { text: "Žádná", icon: "❌", isCorrect: false }], explanation: "Kvalitní komponenty mají záruku, životnost může být delší." }
    ],

    // Level 9 - Chytrá závlaha
    module4_level9: [
        { question: "IoT v závlaze znamená:", type: "multiple_choice", options: [{ text: "Propojená chytrá zařízení", icon: "📱", isCorrect: true }, { text: "Typ hadice", icon: "🔧", isCorrect: false }, { text: "Druh vody", icon: "💧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Internet of Things umožňuje vzdálené sledování a ovládání závlahy." },
        { question: "Půdní senzory vlhkosti:", type: "multiple_choice", options: [{ text: "Měří aktuální stav v reálném čase", icon: "📊", isCorrect: true }, { text: "Pouze předpovídají", icon: "🔮", isCorrect: false }, { text: "Nic neměří", icon: "❌", isCorrect: false }, { text: "Měří pouze teplotu", icon: "🌡️", isCorrect: false }], explanation: "Kapacitní nebo tenziometrické senzory poskytují přesná data o vlhkosti." },
        { question: "Meteorologická stanice na farmě:", type: "multiple_choice", options: [{ text: "Poskytuje data pro výpočet potřeby vody", icon: "🌤️", isCorrect: true }, { text: "Je zbytečná", icon: "❌", isCorrect: false }, { text: "Pouze měří déšť", icon: "🌧️", isCorrect: false }, { text: "Předpovídá úrodu", icon: "🌾", isCorrect: false }], explanation: "Lokální data jsou přesnější než obecné předpovědi." },
        { question: "Aplikace pro smartphone umožňuje:", type: "multiple_choice", options: [{ text: "Vzdálené ovládání a monitoring", icon: "📱", isCorrect: true }, { text: "Pouze hry", icon: "🎮", isCorrect: false }, { text: "Nic užitečného", icon: "❌", isCorrect: false }, { text: "Pouze volání", icon: "📞", isCorrect: false }], explanation: "Mobilní aplikace poskytují přehled a kontrolu odkudkoliv." },
        { question: "Drony v závlaze se používají pro:", type: "multiple_choice", options: [{ text: "Monitoring stavu porostů", icon: "🛸", isCorrect: true }, { text: "Pouze postřik", icon: "💦", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze zábavu", icon: "🎉", isCorrect: false }], explanation: "Drony s multispektrálními kamerami odhalují stres rostlin." },
        { question: "NDVI index ukazuje:", type: "multiple_choice", options: [{ text: "Zdravotní stav vegetace", icon: "🌿", isCorrect: true }, { text: "Pouze teplotu", icon: "🌡️", isCorrect: false }, { text: "Cenu plodin", icon: "💰", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "NDVI ze satelitů nebo dronů identifikuje oblasti se stresem." },
        { question: "Prediktivní závlaha využívá:", type: "multiple_choice", options: [{ text: "Předpověď počasí a AI", icon: "🤖", isCorrect: true }, { text: "Pouze historii", icon: "📜", isCorrect: false }, { text: "Náhodu", icon: "🎲", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Systém předvídá potřebu a nastavuje závlahu proaktivně." },
        { question: "Cloud computing v závlaze:", type: "multiple_choice", options: [{ text: "Zpracovává a ukládá data online", icon: "☁️", isCorrect: true }, { text: "Vytváří mraky pro déšť", icon: "🌧️", isCorrect: false }, { text: "Je zbytečný", icon: "❌", isCorrect: false }, { text: "Pouze zálohuje", icon: "💾", isCorrect: false }], explanation: "Cloudové platformy analyzují data a optimalizují rozhodování." },
        { question: "Machine learning v závlaze:", type: "multiple_choice", options: [{ text: "Učí se z dat a zlepšuje řízení", icon: "🧠", isCorrect: true }, { text: "Nahrazuje rostliny", icon: "🤖", isCorrect: false }, { text: "Je nebezpečné", icon: "⚠️", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "AI algoritmy se učí z historických dat a optimalizují závlahu." },
        { question: "Digitální dvojče farmy je:", type: "multiple_choice", options: [{ text: "Virtuální model pro simulace", icon: "💻", isCorrect: true }, { text: "Kopie farmy", icon: "📋", isCorrect: false }, { text: "Druhá farma", icon: "🏡", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Digitální dvojče umožňuje testovat scénáře bez rizika." }
    ],

    // Level 10 - Budoucnost a udržitelnost
    module4_level10: [
        { question: "Nedostatek vody je:", type: "multiple_choice", options: [{ text: "Globální výzva pro zemědělství", icon: "🌍", isCorrect: true }, { text: "Pouze lokální problém", icon: "📍", isCorrect: false }, { text: "Žádný problém", icon: "✅", isCorrect: false }, { text: "Vyřešený problém", icon: "✅", isCorrect: false }], explanation: "Klimatická změna a růst populace zvyšují tlak na vodní zdroje." },
        { question: "Desalinizace je:", type: "multiple_choice", options: [{ text: "Odsolování mořské vody", icon: "🌊", isCorrect: true }, { text: "Solení vody", icon: "🧂", isCorrect: false }, { text: "Filtrace", icon: "🔍", isCorrect: false }, { text: "Ohřev vody", icon: "🔥", isCorrect: false }], explanation: "Desalinizace může být zdrojem vody v pobřežních oblastech." },
        { question: "Recyklace šedé vody:", type: "multiple_choice", options: [{ text: "Využívá odpadní vodu z domácností", icon: "♻️", isCorrect: true }, { text: "Je zakázána", icon: "⛔", isCorrect: false }, { text: "Je nemožná", icon: "❌", isCorrect: false }, { text: "Škodí rostlinám", icon: "☠️", isCorrect: false }], explanation: "Šedá voda (z umyvadel, sprch) může být po úpravě využita." },
        { question: "Water footprint je:", type: "multiple_choice", options: [{ text: "Vodní stopa produktu nebo činnosti", icon: "👣", isCorrect: true }, { text: "Otisk nohy ve vodě", icon: "🦶", isCorrect: false }, { text: "Druh závlahy", icon: "💧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Vodní stopa měří celkovou spotřebu vody v životním cyklu." },
        { question: "Virtuální voda je:", type: "multiple_choice", options: [{ text: "Voda spotřebovaná na výrobu produktu", icon: "💧", isCorrect: true }, { text: "Umělá voda", icon: "🤖", isCorrect: false }, { text: "Voda ve videohře", icon: "🎮", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Import potravin je vlastně import virtuální vody z jiných regionů." },
        { question: "Aquaponics kombinuje:", type: "multiple_choice", options: [{ text: "Chov ryb a pěstování rostlin", icon: "🐟", isCorrect: true }, { text: "Pouze ryby", icon: "🐠", isCorrect: false }, { text: "Pouze rostliny", icon: "🌱", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Aquaponics využívá odpadní vodu od ryb jako hnojivo pro rostliny." },
        { question: "Atmosférická voda je získávána z:", type: "multiple_choice", options: [{ text: "Mlhy a vzdušné vlhkosti", icon: "🌫️", isCorrect: true }, { text: "Pouze deště", icon: "🌧️", isCorrect: false }, { text: "Pouze řek", icon: "🏞️", isCorrect: false }, { text: "Není možné", icon: "❌", isCorrect: false }], explanation: "Speciální sítě a zařízení mohou sbírat vodu ze vzduchu." },
        { question: "Precision irrigation budoucnosti:", type: "multiple_choice", options: [{ text: "Bude plně automatická a prediktivní", icon: "🤖", isCorrect: true }, { text: "Zmizí", icon: "❌", isCorrect: false }, { text: "Bude pouze manuální", icon: "✋", isCorrect: false }, { text: "Nebude existovat", icon: "⛔", isCorrect: false }], explanation: "AI a senzory umožní závlahu přesně podle potřeb každé rostliny." },
        { question: "Odpovědné vodní hospodářství vyžaduje:", type: "multiple_choice", options: [{ text: "Spolupráci všech uživatelů", icon: "🤝", isCorrect: true }, { text: "Pouze farmáře", icon: "👨‍🌾", isCorrect: false }, { text: "Pouze vládu", icon: "🏛️", isCorrect: false }, { text: "Nikoho", icon: "❌", isCorrect: false }], explanation: "Udržitelné využívání vody je společnou odpovědností." },
        { question: "Budoucnost závlah směřuje k:", type: "multiple_choice", options: [{ text: "Efektivitě, recyklaci, chytrým systémům", icon: "🎯", isCorrect: true }, { text: "Plýtvání vodou", icon: "💦", isCorrect: false }, { text: "Zrušení zavlažování", icon: "⛔", isCorrect: false }, { text: "Pouze tradičním metodám", icon: "📜", isCorrect: false }], explanation: "Inovace a udržitelnost budou klíčem k zajištění produkce potravin." }
    ]
};
