// Modul 5: Mechanizace - 100 otázek (10 levelů x 10 otázek)
const MODULE5_QUESTIONS = {
    module5_level1: [
        { question: "Co je traktor?", type: "multiple_choice", options: [{ text: "Základní tažný stroj v zemědělství", icon: "🚜", isCorrect: true }, { text: "Osobní automobil", icon: "🚗", isCorrect: false }, { text: "Letadlo", icon: "✈️", isCorrect: false }, { text: "Loď", icon: "🚢", isCorrect: false }], explanation: "Traktor je univerzální stroj pro tažení nářadí a pohon strojů." },
        { question: "Výkon traktoru se měří v:", type: "multiple_choice", options: [{ text: "Koních (kW nebo HP)", icon: "🐴", isCorrect: true }, { text: "Litrech", icon: "🥛", isCorrect: false }, { text: "Metrech", icon: "📏", isCorrect: false }, { text: "Kilogramech", icon: "⚖️", isCorrect: false }], explanation: "Výkon udává schopnost traktoru vykonávat práci." },
        { question: "PTO (vývodový hřídel) slouží k:", type: "multiple_choice", options: [{ text: "Přenosu síly na připojené stroje", icon: "⚙️", isCorrect: true }, { text: "Řízení", icon: "🎮", isCorrect: false }, { text: "Brzdění", icon: "🛑", isCorrect: false }, { text: "Osvětlení", icon: "💡", isCorrect: false }], explanation: "PTO přenáší rotační sílu z motoru na aktivní stroje." },
        { question: "Hydraulika v traktoru:", type: "multiple_choice", options: [{ text: "Ovládá nástroje a zvedání", icon: "🔧", isCorrect: true }, { text: "Pouze chladí motor", icon: "❄️", isCorrect: false }, { text: "Pouze maže", icon: "🛢️", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Hydraulický systém umožňuje ovládání připojených nástrojů." },
        { question: "Tříbodový závěs slouží k:", type: "multiple_choice", options: [{ text: "Připojení nářadí k traktoru", icon: "🔗", isCorrect: true }, { text: "Sezení řidiče", icon: "🪑", isCorrect: false }, { text: "Tankování", icon: "⛽", isCorrect: false }, { text: "Osvětlení", icon: "💡", isCorrect: false }], explanation: "Tříbodový závěs je standardizovaný systém pro připojení nářadí." },
        { question: "Diferenciál v traktoru:", type: "multiple_choice", options: [{ text: "Umožňuje různou rychlost kol v zatáčce", icon: "🔄", isCorrect: true }, { text: "Zvyšuje výkon", icon: "📈", isCorrect: false }, { text: "Snižuje spotřebu", icon: "📉", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Diferenciál rozděluje hnací sílu mezi kola." },
        { question: "Pohon 4x4 znamená:", type: "multiple_choice", options: [{ text: "Pohon všech čtyř kol", icon: "🚜", isCorrect: true }, { text: "4 traktory", icon: "4️⃣", isCorrect: false }, { text: "4 motory", icon: "⚙️", isCorrect: false }, { text: "4 řidiče", icon: "👥", isCorrect: false }], explanation: "Pohon všech kol zlepšuje trakci v těžkém terénu." },
        { question: "Kabina traktoru poskytuje:", type: "multiple_choice", options: [{ text: "Ochranu a komfort obsluhy", icon: "🏠", isCorrect: true }, { text: "Pouze výhled", icon: "👀", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }, { text: "Pouze stín", icon: "🌤️", isCorrect: false }], explanation: "Moderní kabiny mají klimatizaci, filtraci a ochranu ROPS." },
        { question: "GPS v traktoru slouží k:", type: "multiple_choice", options: [{ text: "Přesné navigaci a automatickému řízení", icon: "📍", isCorrect: true }, { text: "Pouze mapám", icon: "🗺️", isCorrect: false }, { text: "Telefonování", icon: "📞", isCorrect: false }, { text: "Ničemu", icon: "❌", isCorrect: false }], explanation: "GPS umožňuje precizní zemědělství a autosteering." },
        { question: "Jaké palivo používají traktory?", type: "multiple_choice", options: [{ text: "Většinou naftu (diesel)", icon: "⛽", isCorrect: true }, { text: "Pouze benzín", icon: "🔥", isCorrect: false }, { text: "Pouze elektřinu", icon: "⚡", isCorrect: false }, { text: "Vodu", icon: "💧", isCorrect: false }], explanation: "Dieselové motory jsou standardem, roste podíl alternativ." }
    ],
    module5_level2: [
        { question: "Pluh slouží k:", type: "multiple_choice", options: [{ text: "Obracení a kypření půdy", icon: "🌍", isCorrect: true }, { text: "Setí", icon: "🌰", isCorrect: false }, { text: "Sklizni", icon: "🌾", isCorrect: false }, { text: "Postřiku", icon: "💦", isCorrect: false }], explanation: "Pluh obrací půdu a zapravuje posklizňové zbytky." },
        { question: "Radličkový pluh má:", type: "multiple_choice", options: [{ text: "Radlice pro řezání a obracení půdy", icon: "🔪", isCorrect: true }, { text: "Pouze kola", icon: "🛞", isCorrect: false }, { text: "Motor", icon: "⚙️", isCorrect: false }, { text: "Zásobník", icon: "📦", isCorrect: false }], explanation: "Radličky řežou a obrací půdní skývu." },
        { question: "Dlátový pluh:", type: "multiple_choice", options: [{ text: "Hloubkově kypří bez obracení", icon: "⬇️", isCorrect: true }, { text: "Seje semena", icon: "🌰", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Dlátový pluh rozrušuje zhutnělé vrstvy bez obracení půdy." },
        { question: "Brány slouží k:", type: "multiple_choice", options: [{ text: "Drobení hrud a urovnání", icon: "🧹", isCorrect: true }, { text: "Orání", icon: "🚜", isCorrect: false }, { text: "Sklizni", icon: "🌾", isCorrect: false }, { text: "Postřiku", icon: "💦", isCorrect: false }], explanation: "Brány připravují seťové lůžko po orbě." },
        { question: "Rotavátor:", type: "multiple_choice", options: [{ text: "Kypří půdu rotujícími noži", icon: "🔄", isCorrect: true }, { text: "Seje", icon: "🌰", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Zavlažuje", icon: "💧", isCorrect: false }], explanation: "Rotavátor intenzivně kypří a míchá půdu." },
        { question: "Kypřič (kultivator):", type: "multiple_choice", options: [{ text: "Mělce zpracovává půdu", icon: "🌱", isCorrect: true }, { text: "Oře", icon: "🚜", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Kypřiče zpracovávají půdu bez obracení." },
        { question: "Válec utužuje půdu pro:", type: "multiple_choice", options: [{ text: "Lepší kontakt semen s půdou", icon: "🌰", isCorrect: true }, { text: "Zábavu", icon: "🎉", isCorrect: false }, { text: "Odvodnění", icon: "💧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Válení zlepšuje vzcházení semen." },
        { question: "Podmítač slouží k:", type: "multiple_choice", options: [{ text: "Mělkému zpracování strniště", icon: "🌾", isCorrect: true }, { text: "Hluboké orbě", icon: "⬇️", isCorrect: false }, { text: "Sklizni", icon: "✂️", isCorrect: false }, { text: "Postřiku", icon: "💦", isCorrect: false }], explanation: "Podmítka zapravuje zbytky a podporuje klíčení plevelů." },
        { question: "Smyk slouží k:", type: "multiple_choice", options: [{ text: "Urovnání povrchu", icon: "➡️", isCorrect: true }, { text: "Orání", icon: "🚜", isCorrect: false }, { text: "Sklizni", icon: "🌾", isCorrect: false }, { text: "Setí", icon: "🌰", isCorrect: false }], explanation: "Smyk urovnává povrch před setím nebo po setí." },
        { question: "Kombinované stroje:", type: "multiple_choice", options: [{ text: "Provádějí více operací najednou", icon: "🔧", isCorrect: true }, { text: "Jsou zakázané", icon: "⛔", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Jsou pomalé", icon: "🐌", isCorrect: false }], explanation: "Kombinované stroje šetří čas a přejezdy po poli." }
    ],
    module5_level3: [
        { question: "Secí stroj slouží k:", type: "multiple_choice", options: [{ text: "Výsevu osiva do půdy", icon: "🌰", isCorrect: true }, { text: "Orbě", icon: "🚜", isCorrect: false }, { text: "Sklizni", icon: "🌾", isCorrect: false }, { text: "Postřiku", icon: "💦", isCorrect: false }], explanation: "Secí stroje ukládají osivo v přesném množství a hloubce." },
        { question: "Pneumatický secí stroj:", type: "multiple_choice", options: [{ text: "Používá vzduch k dopravě osiva", icon: "💨", isCorrect: true }, { text: "Je nafukovací", icon: "🎈", isCorrect: false }, { text: "Nemá kola", icon: "🛞", isCorrect: false }, { text: "Je ruční", icon: "✋", isCorrect: false }], explanation: "Vzduchový proud distribuuje osivo do výsevních botek." },
        { question: "Přesný secí stroj:", type: "multiple_choice", options: [{ text: "Ukládá jednotlivá semena v přesných rozestupech", icon: "🎯", isCorrect: true }, { text: "Seje náhodně", icon: "🎲", isCorrect: false }, { text: "Pouze oře", icon: "🚜", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }], explanation: "Pro kukuřici, cukrovku a zeleninu je přesný výsev klíčový." },
        { question: "Sazeč brambor:", type: "multiple_choice", options: [{ text: "Vysazuje hlízy do řádků", icon: "🥔", isCorrect: true }, { text: "Sklízí brambory", icon: "🌾", isCorrect: false }, { text: "Oře", icon: "🚜", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Sazeče automaticky ukládají sadbu do připravené půdy." },
        { question: "Výsevní botka:", type: "multiple_choice", options: [{ text: "Vytváří rýhu a ukládá osivo", icon: "👢", isCorrect: true }, { text: "Chrání nohu", icon: "🦶", isCorrect: false }, { text: "Je ozdoba", icon: "🎀", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Botka otevírá půdu, ukládá semeno a zase přikrývá." },
        { question: "Zásobník osiva:", type: "multiple_choice", options: [{ text: "Obsahuje osivo pro výsev", icon: "📦", isCorrect: true }, { text: "Obsahuje palivo", icon: "⛽", isCorrect: false }, { text: "Obsahuje vodu", icon: "💧", isCorrect: false }, { text: "Je prázdný", icon: "⬜", isCorrect: false }], explanation: "Zásobník musí být čistý a osivo správně nastaveno." },
        { question: "Značkovač řádků:", type: "multiple_choice", options: [{ text: "Vyznačuje stopu pro další průjezd", icon: "📍", isCorrect: true }, { text: "Maluje čáry", icon: "🎨", isCorrect: false }, { text: "Seje", icon: "🌰", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }], explanation: "Značkovač zajišťuje rovnoběžné jízdy bez mezer a překryvů." },
        { question: "Hloubka setí se nastavuje:", type: "multiple_choice", options: [{ text: "Podle druhu plodiny", icon: "📏", isCorrect: true }, { text: "Náhodně", icon: "🎲", isCorrect: false }, { text: "Vždy stejně", icon: "➡️", isCorrect: false }, { text: "Nenastavuje se", icon: "❌", isCorrect: false }], explanation: "Správná hloubka je klíčová pro vzcházení." },
        { question: "GPS řízené setí:", type: "multiple_choice", options: [{ text: "Zajišťuje přesné řádky bez překryvů", icon: "📍", isCorrect: true }, { text: "Je zbytečné", icon: "❌", isCorrect: false }, { text: "Pouze naviguje", icon: "🧭", isCorrect: false }, { text: "Nic nedělá", icon: "⛔", isCorrect: false }], explanation: "GPS umožňuje přesnost na centimetry i v noci nebo mlze." },
        { question: "Strip-till je:", type: "multiple_choice", options: [{ text: "Zpracování pouze pásu půdy pro setí", icon: "➖", isCorrect: true }, { text: "Plošná orba", icon: "🌍", isCorrect: false }, { text: "Postřik", icon: "💦", isCorrect: false }, { text: "Sklizeň", icon: "🌾", isCorrect: false }], explanation: "Strip-till kombinuje výhody bezorebného a klasického systému." }
    ],
    module5_level4: [
        { question: "Rozmetadlo hnojiv:", type: "multiple_choice", options: [{ text: "Rovnoměrně aplikuje granulovaná hnojiva", icon: "🧪", isCorrect: true }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Oře", icon: "🚜", isCorrect: false }, { text: "Seje", icon: "🌰", isCorrect: false }], explanation: "Rozmetadla zajišťují rovnoměrnou distribuci hnojiv na poli." },
        { question: "Postřikovač aplikuje:", type: "multiple_choice", options: [{ text: "Pesticidy a kapalná hnojiva", icon: "💦", isCorrect: true }, { text: "Pouze vodu", icon: "💧", isCorrect: false }, { text: "Pouze semena", icon: "🌰", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Postřikovače aplikují přípravky na ochranu rostlin." },
        { question: "Tryska postřikovače určuje:", type: "multiple_choice", options: [{ text: "Velikost kapek a pokrytí", icon: "💧", isCorrect: true }, { text: "Pouze barvu", icon: "🎨", isCorrect: false }, { text: "Pouze tlak", icon: "📊", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Správná tryska je klíčová pro účinnou aplikaci." },
        { question: "Samojízdný postřikovač:", type: "multiple_choice", options: [{ text: "Má vlastní pohon a vysokou světlou výšku", icon: "🚜", isCorrect: true }, { text: "Je tažený", icon: "🔗", isCorrect: false }, { text: "Je ruční", icon: "✋", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Samojízdné stroje projíždějí vysokými porosty." },
        { question: "Cisterna na kejdu:", type: "multiple_choice", options: [{ text: "Přepravuje a aplikuje tekutá statková hnojiva", icon: "🛢️", isCorrect: true }, { text: "Pouze skladuje", icon: "📦", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Postřikuje pesticidy", icon: "💦", isCorrect: false }], explanation: "Kejdovače aplikují organická hnojiva na pole." },
        { question: "Hadicový aplikátor kejdy:", type: "multiple_choice", options: [{ text: "Ukládá kejdu do řádků na povrch", icon: "〰️", isCorrect: true }, { text: "Rozstřikuje do vzduchu", icon: "💨", isCorrect: false }, { text: "Vstřikuje do půdy", icon: "⬇️", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Hadicová aplikace snižuje ztráty amoniaku." },
        { question: "Injektáž kejdy:", type: "multiple_choice", options: [{ text: "Vstřikuje kejdu přímo do půdy", icon: "⬇️", isCorrect: true }, { text: "Rozstřikuje na povrch", icon: "💦", isCorrect: false }, { text: "Pouze přepravuje", icon: "🚛", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Injektáž minimalizuje ztráty a zápach." },
        { question: "Variabilní dávkování:", type: "multiple_choice", options: [{ text: "Mění dávku podle mapy nebo senzorů", icon: "📊", isCorrect: true }, { text: "Dávkuje vždy stejně", icon: "➡️", isCorrect: false }, { text: "Nedávkuje nic", icon: "❌", isCorrect: false }, { text: "Je náhodné", icon: "🎲", isCorrect: false }], explanation: "Variabilní aplikace optimalizuje spotřebu vstupů." },
        { question: "Senzory na postřikovači:", type: "multiple_choice", options: [{ text: "Detekují plevele nebo porost", icon: "👀", isCorrect: true }, { text: "Pouze měří rychlost", icon: "⏱️", isCorrect: false }, { text: "Nic nedetekují", icon: "❌", isCorrect: false }, { text: "Hrají hudbu", icon: "🎵", isCorrect: false }], explanation: "Senzory umožňují cílenou aplikaci pouze tam, kde je potřeba." },
        { question: "Drony pro postřik:", type: "multiple_choice", options: [{ text: "Aplikují přípravky na malých plochách", icon: "🛸", isCorrect: true }, { text: "Pouze fotografují", icon: "📷", isCorrect: false }, { text: "Sklízejí", icon: "🌾", isCorrect: false }, { text: "Jsou zakázány", icon: "⛔", isCorrect: false }], explanation: "Drony jsou vhodné pro těžko přístupný terén." }
    ],
    module5_level5: [
        { question: "Sklízecí mlátička (kombajn):", type: "multiple_choice", options: [{ text: "Žne, mlátí a čistí zrno", icon: "🌾", isCorrect: true }, { text: "Pouze seje", icon: "🌰", isCorrect: false }, { text: "Pouze oře", icon: "🚜", isCorrect: false }, { text: "Pouze postřikuje", icon: "💦", isCorrect: false }], explanation: "Kombajn provádí sklizeň obilovin v jedné operaci." },
        { question: "Žací ústrojí kombajnu:", type: "multiple_choice", options: [{ text: "Seká a shrnuje porost", icon: "✂️", isCorrect: true }, { text: "Mlátí zrno", icon: "🌾", isCorrect: false }, { text: "Čistí zrno", icon: "🧹", isCorrect: false }, { text: "Skladuje zrno", icon: "📦", isCorrect: false }], explanation: "Žací lišta odřezává obilí a přivádí do mlátícího ústrojí." },
        { question: "Mlátící buben:", type: "multiple_choice", options: [{ text: "Odděluje zrno od klasů", icon: "🥁", isCorrect: true }, { text: "Řeže obilí", icon: "✂️", isCorrect: false }, { text: "Čistí zrno", icon: "🧹", isCorrect: false }, { text: "Skladuje slámu", icon: "📦", isCorrect: false }], explanation: "Rotující buben vytloukává zrno z klasů." },
        { question: "Separační jednotka:", type: "multiple_choice", options: [{ text: "Odděluje zrno od slámy", icon: "🔄", isCorrect: true }, { text: "Pouze řeže", icon: "✂️", isCorrect: false }, { text: "Pouze mlátí", icon: "🥁", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Vytřásadla nebo rotory dokončují separaci zrna." },
        { question: "Čistící ústrojí kombajnu:", type: "multiple_choice", options: [{ text: "Odděluje nečistoty od zrna", icon: "🧹", isCorrect: true }, { text: "Myje zrno", icon: "💧", isCorrect: false }, { text: "Barví zrno", icon: "🎨", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Síta a vzduchový proud čistí zrno od plev a prachu." },
        { question: "Zásobník zrna na kombajnu:", type: "multiple_choice", options: [{ text: "Dočasně skladuje sklizené zrno", icon: "📦", isCorrect: true }, { text: "Obsahuje palivo", icon: "⛽", isCorrect: false }, { text: "Obsahuje vodu", icon: "💧", isCorrect: false }, { text: "Je vždy prázdný", icon: "⬜", isCorrect: false }], explanation: "Zásobník se vyprazdňuje do návěsů nebo sil." },
        { question: "Řezačka na kukuřici:", type: "multiple_choice", options: [{ text: "Seká a drtí celé rostliny na siláž", icon: "🌽", isCorrect: true }, { text: "Pouze sklízí zrno", icon: "🌾", isCorrect: false }, { text: "Pouze seje", icon: "🌰", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Řezačka vytváří řezanku pro silážování." },
        { question: "Kombajn na brambory:", type: "multiple_choice", options: [{ text: "Vyrývá, čistí a nakládá hlízy", icon: "🥔", isCorrect: true }, { text: "Seje brambory", icon: "🌰", isCorrect: false }, { text: "Postřikuje brambory", icon: "💦", isCorrect: false }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }], explanation: "Bramborové kombajny jsou složité stroje s mnoha separačními stupni." },
        { question: "Sklizeň řepky je náročná kvůli:", type: "multiple_choice", options: [{ text: "Snadnému pukání šešulí", icon: "💥", isCorrect: true }, { text: "Velké výšce", icon: "📏", isCorrect: false }, { text: "Nízké ceně", icon: "💰", isCorrect: false }, { text: "Ničemu", icon: "✅", isCorrect: false }], explanation: "Řepka vyžaduje šetrné zacházení a často desikaci." },
        { question: "Yield monitor v kombajnu:", type: "multiple_choice", options: [{ text: "Měří výnos v reálném čase", icon: "📊", isCorrect: true }, { text: "Pouze hraje hudbu", icon: "🎵", isCorrect: false }, { text: "Měří palivo", icon: "⛽", isCorrect: false }, { text: "Nic neměří", icon: "❌", isCorrect: false }], explanation: "Monitor výnosů vytváří mapy produktivity pole." }
    ],
    module5_level6: [
        { question: "Žací stroj (sekačka) slouží k:", type: "multiple_choice", options: [{ text: "Sečení trávy a pícnin", icon: "🌿", isCorrect: true }, { text: "Orání", icon: "🚜", isCorrect: false }, { text: "Setí", icon: "🌰", isCorrect: false }, { text: "Postřiku", icon: "💦", isCorrect: false }], explanation: "Sekačky připravují píci pro seno nebo siláž." },
        { question: "Bubnová sekačka:", type: "multiple_choice", options: [{ text: "Má rotující bubny s noži", icon: "🔄", isCorrect: true }, { text: "Má žací lištu", icon: "➖", isCorrect: false }, { text: "Je ruční", icon: "✋", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Bubnové sekačky jsou rychlé a vhodné pro vysoké výnosy." },
        { question: "Obracec (obraceč) sena:", type: "multiple_choice", options: [{ text: "Převrací posekanou hmotu pro sušení", icon: "🔄", isCorrect: true }, { text: "Seká trávu", icon: "✂️", isCorrect: false }, { text: "Lisuje balíky", icon: "📦", isCorrect: false }, { text: "Seje", icon: "🌰", isCorrect: false }], explanation: "Obracení urychluje rovnoměrné sušení sena." },
        { question: "Shrnovač vytváří:", type: "multiple_choice", options: [{ text: "Řádky pro sběr lisem", icon: "➖", isCorrect: true }, { text: "Balíky", icon: "📦", isCorrect: false }, { text: "Pouze obrací", icon: "🔄", isCorrect: false }, { text: "Seje", icon: "🌰", isCorrect: false }], explanation: "Shrnutá hmota se pak sbírá lisem nebo nakladačem." },
        { question: "Lis na kulaté balíky:", type: "multiple_choice", options: [{ text: "Vytváří válcové balíky sena/slámy", icon: "⭕", isCorrect: true }, { text: "Vytváří hranaté balíky", icon: "⬜", isCorrect: false }, { text: "Pouze seká", icon: "✂️", isCorrect: false }, { text: "Pouze obrací", icon: "🔄", isCorrect: false }], explanation: "Kulaté balíky jsou běžné pro menší farmy." },
        { question: "Velkoobjemový lis:", type: "multiple_choice", options: [{ text: "Vytváří velké hranaté balíky", icon: "📦", isCorrect: true }, { text: "Vytváří malé kulaté balíky", icon: "⭕", isCorrect: false }, { text: "Pouze seká", icon: "✂️", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Velké balíky jsou efektivnější pro dopravu a skladování." },
        { question: "Omotávačka balíků:", type: "multiple_choice", options: [{ text: "Balí balíky do fólie pro senáž", icon: "🎁", isCorrect: true }, { text: "Pouze lisuje", icon: "📦", isCorrect: false }, { text: "Pouze seká", icon: "✂️", isCorrect: false }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }], explanation: "Fólie vytváří anaerobní prostředí pro fermentaci." },
        { question: "Sběrací vůz:", type: "multiple_choice", options: [{ text: "Sbírá a převáží píci ze řádků", icon: "🚛", isCorrect: true }, { text: "Pouze seká", icon: "✂️", isCorrect: false }, { text: "Pouze lisuje", icon: "📦", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Sběrací vozy jsou alternativou k lisování." },
        { question: "Nakladač balíků:", type: "multiple_choice", options: [{ text: "Nakládá balíky na přívěsy", icon: "📦", isCorrect: true }, { text: "Lisuje balíky", icon: "🔧", isCorrect: false }, { text: "Seká trávu", icon: "✂️", isCorrect: false }, { text: "Oře", icon: "🚜", isCorrect: false }], explanation: "Nakladače šetří ruční práci při sklizni." },
        { question: "Silážní kombajn:", type: "multiple_choice", options: [{ text: "Seká a drtí píci pro siláž", icon: "🌿", isCorrect: true }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }, { text: "Pouze lisuje", icon: "📦", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Řezačka vytváří jemnou řezanku pro kvalitní siláž." }
    ],
    module5_level7: [
        { question: "Čelní nakladač na traktoru:", type: "multiple_choice", options: [{ text: "Nakládá a manipuluje s materiálem", icon: "🏗️", isCorrect: true }, { text: "Pouze jezdí", icon: "🚜", isCorrect: false }, { text: "Pouze oře", icon: "🌍", isCorrect: false }, { text: "Pouze postřikuje", icon: "💦", isCorrect: false }], explanation: "Čelní nakladač je univerzální nástroj pro manipulaci." },
        { question: "Teleskopický manipulátor:", type: "multiple_choice", options: [{ text: "Má výsuvné rameno pro větší dosah", icon: "📏", isCorrect: true }, { text: "Má pouze vidlice", icon: "🍴", isCorrect: false }, { text: "Je bez ramene", icon: "❌", isCorrect: false }, { text: "Pouze jezdí", icon: "🚜", isCorrect: false }], explanation: "Teleskop dosáhne do výšky a vzdálenosti." },
        { question: "Vysokozdvižný vozík:", type: "multiple_choice", options: [{ text: "Zvedá a převáží palety", icon: "📦", isCorrect: true }, { text: "Pouze jezdí", icon: "🚗", isCorrect: false }, { text: "Pouze oře", icon: "🚜", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }], explanation: "Vysokozdvižné vozíky jsou nezbytné ve skladech." },
        { question: "Dopravník zrna:", type: "multiple_choice", options: [{ text: "Přepravuje sypké materiály", icon: "〰️", isCorrect: true }, { text: "Pouze skladuje", icon: "📦", isCorrect: false }, { text: "Pouze mlátí", icon: "🥁", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Šnekové nebo pásové dopravníky plní sila a sklady." },
        { question: "Návěs na obiloviny:", type: "multiple_choice", options: [{ text: "Přepravuje sklizené zrno", icon: "🚛", isCorrect: true }, { text: "Seje", icon: "🌰", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }, { text: "Oře", icon: "🚜", isCorrect: false }], explanation: "Návěsy musí mít nepropustné bočnice." },
        { question: "Rozmetadlo chlévské mrvy:", type: "multiple_choice", options: [{ text: "Rozmetá hnůj na pole", icon: "💩", isCorrect: true }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }, { text: "Pouze skladuje", icon: "📦", isCorrect: false }, { text: "Postřikuje pesticidy", icon: "💦", isCorrect: false }], explanation: "Rozmetadla rovnoměrně distribuují organickou hmotu." },
        { question: "Míchací vůz (krmný vůz):", type: "multiple_choice", options: [{ text: "Míchá a dávkuje krmnou směs", icon: "🔄", isCorrect: true }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }, { text: "Pouze skladuje", icon: "📦", isCorrect: false }, { text: "Dojí krávy", icon: "🐄", isCorrect: false }], explanation: "TMR vůz vytváří vyváženou krmnou dávku." },
        { question: "Silážní jáma se plní:", type: "multiple_choice", options: [{ text: "Návěsy a dusá se traktorem", icon: "🚜", isCorrect: true }, { text: "Ručně", icon: "✋", isCorrect: false }, { text: "Sama", icon: "🤖", isCorrect: false }, { text: "Kombajnem", icon: "🌾", isCorrect: false }], explanation: "Správné udusání je klíčové pro kvalitu siláže." },
        { question: "Ovinovačka balíků:", type: "multiple_choice", options: [{ text: "Balí více balíků do fólie", icon: "🎁", isCorrect: true }, { text: "Pouze lisuje", icon: "📦", isCorrect: false }, { text: "Pouze převáží", icon: "🚛", isCorrect: false }, { text: "Seká", icon: "✂️", isCorrect: false }], explanation: "Skupinové ovinování je rychlejší a úspornější." },
        { question: "Drtič balíků:", type: "multiple_choice", options: [{ text: "Rozbíjí balíky pro podestýlku nebo krmení", icon: "💥", isCorrect: true }, { text: "Lisuje balíky", icon: "📦", isCorrect: false }, { text: "Sklízí", icon: "🌾", isCorrect: false }, { text: "Postřikuje", icon: "💦", isCorrect: false }], explanation: "Drtič usnadňuje manipulaci s balíkovanou slámou." }
    ],
    module5_level8: [
        { question: "ISOBUS je:", type: "multiple_choice", options: [{ text: "Standardní komunikace mezi traktorem a nářadím", icon: "🔌", isCorrect: true }, { text: "Druh paliva", icon: "⛽", isCorrect: false }, { text: "Typ traktoru", icon: "🚜", isCorrect: false }, { text: "Navigační systém", icon: "🧭", isCorrect: false }], explanation: "ISOBUS umožňuje univerzální připojení různých strojů." },
        { question: "Autosteering (automatické řízení):", type: "multiple_choice", options: [{ text: "GPS řídí traktor po přesných liniích", icon: "📍", isCorrect: true }, { text: "Traktor jede sám bez obsluhy", icon: "🤖", isCorrect: false }, { text: "Pouze naviguje", icon: "🧭", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Autosteering zvyšuje přesnost a snižuje únavu řidiče." },
        { question: "RTK korekce:", type: "multiple_choice", options: [{ text: "Zvyšuje přesnost GPS na centimetry", icon: "🎯", isCorrect: true }, { text: "Je druh traktoru", icon: "🚜", isCorrect: false }, { text: "Je typ hnojiva", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "RTK poskytuje přesnost do 2 cm pro precizní práci." },
        { question: "Telematics v traktorech:", type: "multiple_choice", options: [{ text: "Vzdálený monitoring a diagnostika", icon: "📱", isCorrect: true }, { text: "Pouze GPS", icon: "📍", isCorrect: false }, { text: "Pouze telefon", icon: "📞", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Telematics umožňuje sledování flotily a preventivní údržbu." },
        { question: "Variabilní aplikace:", type: "multiple_choice", options: [{ text: "Mění dávku podle předpisu nebo senzorů", icon: "📊", isCorrect: true }, { text: "Je vždy stejná", icon: "➡️", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Je náhodná", icon: "🎲", isCorrect: false }], explanation: "VRA optimalizuje vstupy podle potřeb jednotlivých zón." },
        { question: "Task controller:", type: "multiple_choice", options: [{ text: "Řídí práci stroje podle předpisu", icon: "🖥️", isCorrect: true }, { text: "Pouze měří čas", icon: "⏱️", isCorrect: false }, { text: "Pouze hraje hudbu", icon: "🎵", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Task controller automaticky nastavuje stroj podle map." },
        { question: "Section control:", type: "multiple_choice", options: [{ text: "Automaticky vypíná sekce v překryvech", icon: "⛔", isCorrect: true }, { text: "Pouze měří", icon: "📏", isCorrect: false }, { text: "Pouze počítá", icon: "🔢", isCorrect: false }, { text: "Nic nedělá", icon: "❌", isCorrect: false }], explanation: "Section control šetří osivo, hnojivo a pesticidy." },
        { question: "AEF certifikace:", type: "multiple_choice", options: [{ text: "Potvrzuje kompatibilitu ISOBUS zařízení", icon: "✅", isCorrect: true }, { text: "Je typ traktoru", icon: "🚜", isCorrect: false }, { text: "Je značka hnojiv", icon: "🧪", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "AEF certifikace zajišťuje spolupráci různých výrobců." },
        { question: "Fleet management:", type: "multiple_choice", options: [{ text: "Řízení a sledování vozového parku", icon: "📊", isCorrect: true }, { text: "Pouze počítání strojů", icon: "🔢", isCorrect: false }, { text: "Pouze parkování", icon: "🅿️", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Fleet management optimalizuje využití strojů." },
        { question: "Data logging:", type: "multiple_choice", options: [{ text: "Záznam dat o práci strojů", icon: "📝", isCorrect: true }, { text: "Pouze navigace", icon: "🧭", isCorrect: false }, { text: "Pouze komunikace", icon: "📞", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Zaznamenané data jsou základem pro analýzu a zlepšení." }
    ],
    module5_level9: [
        { question: "Autonomní traktor:", type: "multiple_choice", options: [{ text: "Pracuje bez obsluhy", icon: "🤖", isCorrect: true }, { text: "Má pouze GPS", icon: "📍", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Je ruční", icon: "✋", isCorrect: false }], explanation: "Autonomní stroje jsou realitou a budou běžnější." },
        { question: "Elektrický traktor:", type: "multiple_choice", options: [{ text: "Pohání ho elektromotor a baterie", icon: "⚡", isCorrect: true }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Má pouze diesel", icon: "⛽", isCorrect: false }, { text: "Je na páru", icon: "💨", isCorrect: false }], explanation: "Elektrické traktory jsou vhodné pro menší farmy a skleníky." },
        { question: "Robotické plečky:", type: "multiple_choice", options: [{ text: "Autonomně likvidují plevele", icon: "🤖", isCorrect: true }, { text: "Pouze jezdí", icon: "🚗", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }, { text: "Sklízejí", icon: "🌾", isCorrect: false }], explanation: "Roboti mohou mechanicky odstraňovat plevele bez herbicidů." },
        { question: "Swarm robotics:", type: "multiple_choice", options: [{ text: "Spolupráce mnoha malých robotů", icon: "🐝", isCorrect: true }, { text: "Jeden velký robot", icon: "🤖", isCorrect: false }, { text: "Pouze drony", icon: "🛸", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Roje malých robotů mohou být alternativou k velkým strojům." },
        { question: "Vodíkový pohon traktorů:", type: "multiple_choice", options: [{ text: "Využívá vodíkové palivové články", icon: "💧", isCorrect: true }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Spaluje vodu", icon: "🔥", isCorrect: false }, { text: "Je zakázán", icon: "⛔", isCorrect: false }], explanation: "Vodík je potenciální čisté palivo budoucnosti." },
        { question: "3D tisk v zemědělství:", type: "multiple_choice", options: [{ text: "Výroba náhradních dílů na farmě", icon: "🖨️", isCorrect: true }, { text: "Tisk traktorů", icon: "🚜", isCorrect: false }, { text: "Tisk plodin", icon: "🌱", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "3D tisk může zkrátit čekání na náhradní díly." },
        { question: "Exoskelet pro farmáře:", type: "multiple_choice", options: [{ text: "Podporuje tělo při těžké práci", icon: "💪", isCorrect: true }, { text: "Nahrazuje farmáře", icon: "🤖", isCorrect: false }, { text: "Je oblek", icon: "👔", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Exoskelet snižuje námahu při manuální práci." },
        { question: "Mixed reality v servisu strojů:", type: "multiple_choice", options: [{ text: "AR/VR pomáhá při opravách", icon: "🥽", isCorrect: true }, { text: "Pouze hry", icon: "🎮", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }, { text: "Pouze video", icon: "📹", isCorrect: false }], explanation: "AR brýle mohou zobrazovat návody přímo na stroji." },
        { question: "Prediktivní údržba:", type: "multiple_choice", options: [{ text: "AI předpovídá poruchy před vznikem", icon: "🔮", isCorrect: true }, { text: "Oprava až po poruše", icon: "🔧", isCorrect: false }, { text: "Žádná údržba", icon: "❌", isCorrect: false }, { text: "Pouze pravidelná", icon: "📅", isCorrect: false }], explanation: "Senzory a AI minimalizují neplánované prostoje." },
        { question: "Digital twin stroje:", type: "multiple_choice", options: [{ text: "Virtuální kopie pro simulace", icon: "💻", isCorrect: true }, { text: "Druhý stroj", icon: "🚜", isCorrect: false }, { text: "Pouze fotka", icon: "📷", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Digitální dvojče umožňuje testování a optimalizaci." }
    ],
    module5_level10: [
        { question: "Investice do mechanizace vyžaduje:", type: "multiple_choice", options: [{ text: "Analýzu návratnosti a využití", icon: "📊", isCorrect: true }, { text: "Pouze nejlevnější stroj", icon: "💰", isCorrect: false }, { text: "Pouze nejdražší stroj", icon: "💎", isCorrect: false }, { text: "Náhodný výběr", icon: "🎲", isCorrect: false }], explanation: "Ekonomická analýza je základem správného rozhodnutí." },
        { question: "Sdílení strojů (ring) umožňuje:", type: "multiple_choice", options: [{ text: "Snížení nákladů na mechanizaci", icon: "🤝", isCorrect: true }, { text: "Pouze problémy", icon: "❌", isCorrect: false }, { text: "Vyšší náklady", icon: "📈", isCorrect: false }, { text: "Nic", icon: "⛔", isCorrect: false }], explanation: "Strojní kroužky zvyšují využití drahých strojů." },
        { question: "Služby v zemědělství:", type: "multiple_choice", options: [{ text: "Alternativa k vlastnictví strojů", icon: "🛠️", isCorrect: true }, { text: "Jsou zakázané", icon: "⛔", isCorrect: false }, { text: "Jsou dražší vždy", icon: "💰", isCorrect: false }, { text: "Neexistují", icon: "❌", isCorrect: false }], explanation: "Služby mohou být ekonomicky výhodnější než vlastnictví." },
        { question: "Leasing strojů:", type: "multiple_choice", options: [{ text: "Nájem s možností odkupu", icon: "📄", isCorrect: true }, { text: "Pouze prodej", icon: "💰", isCorrect: false }, { text: "Pouze půjčka", icon: "🏦", isCorrect: false }, { text: "Neexistuje", icon: "❌", isCorrect: false }], explanation: "Leasing snižuje počáteční investici a rozloží náklady." },
        { question: "Odpisy strojů:", type: "multiple_choice", options: [{ text: "Účetní vyjádření opotřebení", icon: "📉", isCorrect: true }, { text: "Pouze daň", icon: "💰", isCorrect: false }, { text: "Pouze opravy", icon: "🔧", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "Odpisy jsou nákladem a snižují základ daně." },
        { question: "TCO (Total Cost of Ownership):", type: "multiple_choice", options: [{ text: "Celkové náklady na vlastnictví", icon: "💰", isCorrect: true }, { text: "Pouze pořizovací cena", icon: "💵", isCorrect: false }, { text: "Pouze palivo", icon: "⛽", isCorrect: false }, { text: "Pouze opravy", icon: "🔧", isCorrect: false }], explanation: "TCO zahrnuje pořízení, provoz, údržbu i prodej." },
        { question: "Bezpečnost práce se stroji:", type: "multiple_choice", options: [{ text: "Je prioritou a vyžaduje školení", icon: "⚠️", isCorrect: true }, { text: "Není důležitá", icon: "❌", isCorrect: false }, { text: "Je pouze doporučená", icon: "🤷", isCorrect: false }, { text: "Závisí na počasí", icon: "🌤️", isCorrect: false }], explanation: "Zemědělství patří k rizikovým odvětvím." },
        { question: "ROPS na traktoru:", type: "multiple_choice", options: [{ text: "Ochranná konstrukce proti převrácení", icon: "🛡️", isCorrect: true }, { text: "Typ motoru", icon: "⚙️", isCorrect: false }, { text: "Druh pneumatik", icon: "🛞", isCorrect: false }, { text: "Nic", icon: "❌", isCorrect: false }], explanation: "ROPS chrání obsluhu při převrácení traktoru." },
        { question: "Ergonomie v kabině:", type: "multiple_choice", options: [{ text: "Snižuje únavu a zvyšuje produktivitu", icon: "🪑", isCorrect: true }, { text: "Je zbytečná", icon: "❌", isCorrect: false }, { text: "Pouze vzhled", icon: "🎨", isCorrect: false }, { text: "Zvyšuje náklady pouze", icon: "💰", isCorrect: false }], explanation: "Pohodlná kabina je důležitá pro dlouhé pracovní dny." },
        { question: "Budoucnost mechanizace směřuje k:", type: "multiple_choice", options: [{ text: "Automatizaci, elektrifikaci, preciznosti", icon: "🎯", isCorrect: true }, { text: "Více manuální práce", icon: "✋", isCorrect: false }, { text: "Konci mechanizace", icon: "⛔", isCorrect: false }, { text: "Pouze velkým strojům", icon: "🚜", isCorrect: false }], explanation: "Inovace povedou k udržitelnější a efektivnější produkci." }
    ]
};
