// Module 6: Ecology - 100 questions
const MODULE6_QUESTIONS = {
    // Level 1 - Ecological Farming Basics
    module6_level1: [
        { question: "What is organic farming?", type: "multiple_choice", options: [{ text: "Farming without synthetic chemicals", icon: "🌿", isCorrect: true }, { text: "Only large farms", icon: "🏭", isCorrect: false }, { text: "Only small gardens", icon: "🏡", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Organic farming doesn't use synthetic pesticides and fertilizers." },
        { question: "Bio certification in EU:", type: "multiple_choice", options: [{ text: "Has uniform rules and logo", icon: "🌱", isCorrect: true }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Is voluntary", icon: "🤷", isCorrect: false }, { text: "Only for fruit", icon: "🍎", isCorrect: false }], explanation: "EU organic logo guarantees compliance with ecological standards." },
        { question: "Conversion period to organic is:", type: "multiple_choice", options: [{ text: "2-3 years depending on crop", icon: "📅", isCorrect: true }, { text: "1 week", icon: "📆", isCorrect: false }, { text: "10 years", icon: "📅", isCorrect: false }, { text: "Not needed", icon: "❌", isCorrect: false }], explanation: "Soil must be cleansed of residues before certification." },
        { question: "In organic farming, prohibited are:", type: "multiple_choice", options: [{ text: "GMOs and synthetic pesticides", icon: "⛔", isCorrect: true }, { text: "Compost", icon: "♻️", isCorrect: false }, { text: "Crop rotation", icon: "🔄", isCorrect: false }, { text: "Manual work", icon: "✋", isCorrect: false }], explanation: "Organic standards exclude GMOs and synthetic chemicals." },
        { question: "Biodiversity means:", type: "multiple_choice", options: [{ text: "Diversity of living organisms", icon: "🦋", isCorrect: true }, { text: "Only organic products", icon: "🌿", isCorrect: false }, { text: "Type of fertilizer", icon: "🧪", isCorrect: false }, { text: "Type of crop", icon: "🌾", isCorrect: false }], explanation: "Biodiversity is the foundation of healthy ecosystems." },
        { question: "Pollinators are important for:", type: "multiple_choice", options: [{ text: "Plant pollination and fruit formation", icon: "🐝", isCorrect: true }, { text: "Only honey", icon: "🍯", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }, { text: "Only beauty", icon: "🎨", isCorrect: false }], explanation: "Without pollinators, many crops wouldn't produce fruit." },
        { question: "Beneficial predators in orchards:", type: "multiple_choice", options: [{ text: "Ladybugs, lacewings, parasitic wasps", icon: "🐞", isCorrect: true }, { text: "Only birds", icon: "🐦", isCorrect: false }, { text: "None", icon: "❌", isCorrect: false }, { text: "Only spiders", icon: "🕷️", isCorrect: false }], explanation: "Natural enemies help regulate pest populations." },
        { question: "Agroecology studies:", type: "multiple_choice", options: [{ text: "Ecological processes in agriculture", icon: "🔬", isCorrect: true }, { text: "Only economics", icon: "💰", isCorrect: false }, { text: "Only weather", icon: "🌤️", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Agroecology seeks sustainable ways of farming." },
        { question: "Ecosystem services include:", type: "multiple_choice", options: [{ text: "Pollination, water purification, soil formation", icon: "🌍", isCorrect: true }, { text: "Only production", icon: "🌾", isCorrect: false }, { text: "Only beauty", icon: "🎨", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Nature provides services we would otherwise have to pay for." },
        { question: "Landscape features support:", type: "multiple_choice", options: [{ text: "Biodiversity and natural enemies", icon: "🌳", isCorrect: true }, { text: "Only aesthetics", icon: "🎨", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }, { text: "Pests", icon: "🐛", isCorrect: false }], explanation: "Hedgerows, woodlots, and wetlands are refuges for beneficial organisms." }
    ],

    // Level 2 - Carbon & Climate
    module6_level2: [
        { question: "Agriculture's carbon footprint:", type: "multiple_choice", options: [{ text: "Includes emissions from production and transport", icon: "👣", isCorrect: true }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Is always zero", icon: "0️⃣", isCorrect: false }, { text: "Only from tractors", icon: "🚜", isCorrect: false }], explanation: "Agriculture contributes to CO2, CH4, and N2O emissions." },
        { question: "Carbon sequestration in soil:", type: "multiple_choice", options: [{ text: "Storing carbon from atmosphere", icon: "⬇️", isCorrect: true }, { text: "Releasing CO2", icon: "⬆️", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Burning", icon: "🔥", isCorrect: false }], explanation: "Healthy soil can be a significant carbon sink." },
        { question: "Methane in agriculture comes from:", type: "multiple_choice", options: [{ text: "Ruminants and rice paddies", icon: "🐄", isCorrect: true }, { text: "Only tractors", icon: "🚜", isCorrect: false }, { text: "Only the sun", icon: "☀️", isCorrect: false }, { text: "Nowhere", icon: "❌", isCorrect: false }], explanation: "Ruminants produce methane during digestion." },
        { question: "Nitrous oxide is produced by:", type: "multiple_choice", options: [{ text: "Application of nitrogen fertilizers", icon: "🧪", isCorrect: true }, { text: "Plowing", icon: "🚜", isCorrect: false }, { text: "Harvesting", icon: "🌾", isCorrect: false }, { text: "Not produced", icon: "❌", isCorrect: false }], explanation: "N2O is a potent greenhouse gas from fertilizers and manure." },
        { question: "Regenerative agriculture:", type: "multiple_choice", options: [{ text: "Restores soil health and biodiversity", icon: "♻️", isCorrect: true }, { text: "Destroys soil", icon: "❌", isCorrect: false }, { text: "Uses more chemicals", icon: "🧪", isCorrect: false }, { text: "Doesn't exist", icon: "⛔", isCorrect: false }], explanation: "Regenerative approaches actively improve the ecosystem." },
        { question: "Cover crops:", type: "multiple_choice", options: [{ text: "Protect soil and sequester carbon", icon: "🌱", isCorrect: true }, { text: "Are weeds", icon: "🌿", isCorrect: false }, { text: "Cause harm", icon: "❌", isCorrect: false }, { text: "Only for beauty", icon: "🎨", isCorrect: false }], explanation: "Cover crops protect soil and add organic matter." },
        { question: "No-till farming:", type: "multiple_choice", options: [{ text: "Farming without plowing", icon: "🚫", isCorrect: true }, { text: "Intensive plowing", icon: "🚜", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only in winter", icon: "❄️", isCorrect: false }], explanation: "No-till protects soil structure and soil life." },
        { question: "Agroforestry combines:", type: "multiple_choice", options: [{ text: "Trees with crops or animals", icon: "🌳", isCorrect: true }, { text: "Only trees", icon: "🌲", isCorrect: false }, { text: "Only crops", icon: "🌾", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Trees in fields provide shade, biomass, and diversity." },
        { question: "Carbon credits:", type: "multiple_choice", options: [{ text: "Reward for carbon storage", icon: "💰", isCorrect: true }, { text: "Tax", icon: "📋", isCorrect: false }, { text: "Fertilizer", icon: "🧪", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Farmers can earn income for climate-positive practices." },
        { question: "LCA (Life Cycle Assessment):", type: "multiple_choice", options: [{ text: "Impact assessment across entire life cycle", icon: "🔄", isCorrect: true }, { text: "Only price", icon: "💰", isCorrect: false }, { text: "Only yield", icon: "🌾", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "LCA measures environmental impact from field to plate." }
    ],

    // Level 3 - Soil & Water Protection
    module6_level3: [
        { question: "Soil erosion is:", type: "multiple_choice", options: [{ text: "Removal of soil by water or wind", icon: "💨", isCorrect: true }, { text: "Soil enrichment", icon: "📈", isCorrect: false }, { text: "Plant growth", icon: "🌱", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Erosion is a serious problem; soil loss is nearly irreversible." },
        { question: "Erosion control measures include:", type: "multiple_choice", options: [{ text: "Buffer strips, hedgerows, grass cover", icon: "🌾", isCorrect: true }, { text: "More plowing", icon: "🚜", isCorrect: false }, { text: "Vegetation removal", icon: "✂️", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Vegetation and technical measures slow water runoff." },
        { question: "GAEC are:", type: "multiple_choice", options: [{ text: "Good Agricultural and Environmental Conditions", icon: "📋", isCorrect: true }, { text: "Type of fertilizer", icon: "🧪", isCorrect: false }, { text: "Type of tractor", icon: "🚜", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "GAEC are mandatory standards for receiving subsidies." },
        { question: "Water contamination from agriculture:", type: "multiple_choice", options: [{ text: "Nitrates, phosphorus, pesticides", icon: "💧", isCorrect: true }, { text: "Only water", icon: "💧", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only salt", icon: "🧂", isCorrect: false }], explanation: "Runoff from fields can contaminate water sources." },
        { question: "EU Nitrates Directive:", type: "multiple_choice", options: [{ text: "Limits nitrogen application", icon: "📋", isCorrect: true }, { text: "Supports more fertilization", icon: "📈", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only for rice", icon: "🍚", isCorrect: false }], explanation: "The directive protects waters from nitrate pollution." },
        { question: "Vulnerable zones are:", type: "multiple_choice", options: [{ text: "Areas at risk of water pollution", icon: "⚠️", isCorrect: true }, { text: "Safe areas", icon: "✅", isCorrect: false }, { text: "Only deserts", icon: "🏜️", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Stricter fertilization rules apply in vulnerable zones." },
        { question: "Riparian vegetation:", type: "multiple_choice", options: [{ text: "Protects waterways from runoff", icon: "🌿", isCorrect: true }, { text: "Causes harm", icon: "❌", isCorrect: false }, { text: "Is prohibited", icon: "⛔", isCorrect: false }, { text: "Only for beauty", icon: "🎨", isCorrect: false }], explanation: "Vegetation along streams captures nutrients and sediments." },
        { question: "Wetlands in the landscape:", type: "multiple_choice", options: [{ text: "Purify water and support biodiversity", icon: "🦆", isCorrect: true }, { text: "Are useless", icon: "❌", isCorrect: false }, { text: "Only obstruct", icon: "⛔", isCorrect: false }, { text: "Spread disease", icon: "🦠", isCorrect: false }], explanation: "Wetlands are valuable ecosystems with many functions." },
        { question: "Precision fertilization reduces:", type: "multiple_choice", options: [{ text: "Nutrient losses to the environment", icon: "📉", isCorrect: true }, { text: "Yields", icon: "🌾", isCorrect: false }, { text: "Quality", icon: "⭐", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Precise application minimizes surpluses and losses." },
        { question: "Sustainable intensification:", type: "multiple_choice", options: [{ text: "More production with less impact", icon: "🎯", isCorrect: true }, { text: "More chemicals", icon: "🧪", isCorrect: false }, { text: "Less production", icon: "📉", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "The goal is to increase efficiency while protecting environment." }
    ],

    // Level 4 - Organic Practices
    module6_level4: [
        { question: "Organic fertilization:", type: "multiple_choice", options: [{ text: "Compost, manure, green manure", icon: "♻️", isCorrect: true }, { text: "Synthetic fertilizers", icon: "🧪", isCorrect: false }, { text: "Pesticides", icon: "💦", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Organic fertilizers supply nutrients and improve soil." },
        { question: "Green manure is:", type: "multiple_choice", options: [{ text: "Plowing in plants to enrich soil", icon: "🌿", isCorrect: true }, { text: "Green color fertilizer", icon: "🎨", isCorrect: false }, { text: "Synthetic fertilizer", icon: "🧪", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Green manure adds organic matter and nutrients." },
        { question: "Legumes fix:", type: "multiple_choice", options: [{ text: "Atmospheric nitrogen into soil", icon: "🌿", isCorrect: true }, { text: "Only phosphorus", icon: "🧪", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }, { text: "Carbon dioxide", icon: "☁️", isCorrect: false }], explanation: "Symbiosis with rhizobia bacteria fixes nitrogen from atmosphere." },
        { question: "Composting is:", type: "multiple_choice", options: [{ text: "Controlled decomposition of organic matter", icon: "♻️", isCorrect: true }, { text: "Burning waste", icon: "🔥", isCorrect: false }, { text: "Landfilling", icon: "🗑️", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Compost is valuable fertilizer and soil conditioner." },
        { question: "Vermicompost is:", type: "multiple_choice", options: [{ text: "Compost created by earthworms", icon: "🪱", isCorrect: true }, { text: "Synthetic fertilizer", icon: "🧪", isCorrect: false }, { text: "Pesticide", icon: "💦", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Worm castings are high-quality organic fertilizer." },
        { question: "Biopreparations are:", type: "multiple_choice", options: [{ text: "Products from living organisms", icon: "🦠", isCorrect: true }, { text: "Synthetic chemistry", icon: "🧪", isCorrect: false }, { text: "Pesticides", icon: "💦", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Biopreparations contain beneficial microorganisms or extracts." },
        { question: "Microbial inoculants:", type: "multiple_choice", options: [{ text: "Beneficial microorganisms for soil", icon: "🦠", isCorrect: true }, { text: "Pathogens", icon: "☠️", isCorrect: false }, { text: "Pesticides", icon: "💦", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Inoculants improve soil and plant health." },
        { question: "Biological control uses:", type: "multiple_choice", options: [{ text: "Natural enemies of pests", icon: "🐞", isCorrect: true }, { text: "More chemicals", icon: "🧪", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }, { text: "Only sprays", icon: "💦", isCorrect: false }], explanation: "Predators and parasitoids regulate pest populations." },
        { question: "Pheromone traps:", type: "multiple_choice", options: [{ text: "Monitor or catch insects", icon: "🪤", isCorrect: true }, { text: "Kill everything", icon: "☠️", isCorrect: false }, { text: "Fertilize", icon: "🧪", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Pheromones attract specific insect species." },
        { question: "Mulching in organic:", type: "multiple_choice", options: [{ text: "Suppresses weeds and protects soil", icon: "🍂", isCorrect: true }, { text: "Harms plants", icon: "❌", isCorrect: false }, { text: "Is prohibited", icon: "⛔", isCorrect: false }, { text: "Does nothing", icon: "🤷", isCorrect: false }], explanation: "Mulch is an important tool in organic farming." }
    ],

    // Level 5 - Animal Welfare
    module6_level5: [
        { question: "Animal welfare in organic:", type: "multiple_choice", options: [{ text: "Higher welfare standards", icon: "🐄", isCorrect: true }, { text: "No requirements", icon: "❌", isCorrect: false }, { text: "Lower standards", icon: "📉", isCorrect: false }, { text: "Only for poultry", icon: "🐔", isCorrect: false }], explanation: "Organic requires outdoor access, space, natural behavior." },
        { question: "Outdoor access for organic hens:", type: "multiple_choice", options: [{ text: "Is mandatory", icon: "✅", isCorrect: true }, { text: "Is prohibited", icon: "⛔", isCorrect: false }, { text: "Is voluntary", icon: "🤷", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Organic poultry must have access to outdoor range." },
        { question: "Antibiotics in organic livestock:", type: "multiple_choice", options: [{ text: "Restricted, only therapeutic use", icon: "💊", isCorrect: true }, { text: "Freely used", icon: "✅", isCorrect: false }, { text: "Completely banned", icon: "⛔", isCorrect: false }, { text: "Mandatory", icon: "📋", isCorrect: false }], explanation: "Organic prioritizes prevention; antibiotics only as last resort." },
        { question: "Feed for organic animals:", type: "multiple_choice", options: [{ text: "Must be of organic origin", icon: "🌿", isCorrect: true }, { text: "Can be anything", icon: "🤷", isCorrect: false }, { text: "Must be GMO", icon: "🧬", isCorrect: false }, { text: "Only hay", icon: "🌾", isCorrect: false }], explanation: "Organic animals receive organic feed without GMOs." },
        { question: "Pasture-based farming:", type: "multiple_choice", options: [{ text: "Animals graze on grasslands", icon: "🐄", isCorrect: true }, { text: "Animals stay indoors", icon: "🏠", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only for sheep", icon: "🐑", isCorrect: false }], explanation: "Grazing is the natural way of raising ruminants." },
        { question: "Extensive farming:", type: "multiple_choice", options: [{ text: "Low intensity, large space", icon: "🌳", isCorrect: true }, { text: "High intensity", icon: "📈", isCorrect: false }, { text: "No space", icon: "📦", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Extensive farming gives animals more space and freedom." },
        { question: "Local breeds:", type: "multiple_choice", options: [{ text: "Better adapted to local conditions", icon: "🐄", isCorrect: true }, { text: "Always worse", icon: "📉", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }, { text: "Only for shows", icon: "🏆", isCorrect: false }], explanation: "Traditional breeds are more resilient and sustainable." },
        { question: "Silvopasture is:", type: "multiple_choice", options: [{ text: "Grazing under trees", icon: "🌳", isCorrect: true }, { text: "Forest management", icon: "🌲", isCorrect: false }, { text: "Mushroom growing", icon: "🍄", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Combining trees and grazing provides shade and forage." },
        { question: "Rotational grazing:", type: "multiple_choice", options: [{ text: "Rotating pasture areas", icon: "🔄", isCorrect: true }, { text: "Continuous grazing", icon: "📍", isCorrect: false }, { text: "No grazing", icon: "⛔", isCorrect: false }, { text: "Only in summer", icon: "☀️", isCorrect: false }], explanation: "Rotation allows grassland regeneration." },
        { question: "Mob grazing:", type: "multiple_choice", options: [{ text: "Intensive short-duration grazing", icon: "🐄", isCorrect: true }, { text: "Year-round grazing", icon: "📅", isCorrect: false }, { text: "Without animals", icon: "❌", isCorrect: false }, { text: "Doesn't exist", icon: "⛔", isCorrect: false }], explanation: "High density for short time mimics natural herds." }
    ],

    // Level 6 - Genetics & Breeding
    module6_level6: [
        { question: "GMO in EU is:", type: "multiple_choice", options: [{ text: "Strictly regulated", icon: "📋", isCorrect: true }, { text: "Completely banned", icon: "⛔", isCorrect: false }, { text: "Without restrictions", icon: "✅", isCorrect: false }, { text: "Only for research", icon: "🔬", isCorrect: false }], explanation: "EU has the strictest GMO rules in the world." },
        { question: "Cisgenics:", type: "multiple_choice", options: [{ text: "Gene transfer within species", icon: "🧬", isCorrect: true }, { text: "Transfer between species", icon: "🔄", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Is banned", icon: "⛔", isCorrect: false }], explanation: "Cisgenics uses genes from related species." },
        { question: "CRISPR in breeding:", type: "multiple_choice", options: [{ text: "Precise gene editing", icon: "✂️", isCorrect: true }, { text: "Is banned", icon: "⛔", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only for medicine", icon: "💊", isCorrect: false }], explanation: "CRISPR enables targeted changes without inserting foreign genes." },
        { question: "Coexistence of GMO and organic:", type: "multiple_choice", options: [{ text: "Requires protective measures", icon: "🛡️", isCorrect: true }, { text: "Is impossible", icon: "❌", isCorrect: false }, { text: "Requires nothing", icon: "🤷", isCorrect: false }, { text: "Is mandatory", icon: "📋", isCorrect: false }], explanation: "Rules minimize GMO contamination of organic production." },
        { question: "Marker-assisted selection:", type: "multiple_choice", options: [{ text: "Breeding using genetic markers", icon: "🔬", isCorrect: true }, { text: "Manual selection", icon: "✋", isCorrect: false }, { text: "GMO", icon: "🧬", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "MAS accelerates breeding without GMO technologies." },
        { question: "Varieties for organic:", type: "multiple_choice", options: [{ text: "Resistant, adapted to low inputs", icon: "🌱", isCorrect: true }, { text: "High yield at any cost", icon: "📈", isCorrect: false }, { text: "Only GMO", icon: "🧬", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Organic requires varieties resistant to diseases and competitive against weeds." },
        { question: "Participatory breeding:", type: "multiple_choice", options: [{ text: "Involving farmers in breeding", icon: "👨‍🌾", isCorrect: true }, { text: "Only scientists", icon: "🔬", isCorrect: false }, { text: "Only companies", icon: "🏢", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Farmers help select varieties suitable for their conditions." },
        { question: "Conservation of genetic resources:", type: "multiple_choice", options: [{ text: "Gene banks and on-farm conservation", icon: "🏦", isCorrect: true }, { text: "Not important", icon: "❌", isCorrect: false }, { text: "Only in museums", icon: "🏛️", isCorrect: false }, { text: "Only in nature", icon: "🌳", isCorrect: false }], explanation: "Genetic diversity is insurance for the future." },
        { question: "Landraces are:", type: "multiple_choice", options: [{ text: "Traditional local varieties", icon: "🌾", isCorrect: true }, { text: "Modern hybrids", icon: "🧬", isCorrect: false }, { text: "GMO varieties", icon: "🧬", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Traditional varieties are adapted to local conditions." },
        { question: "Heterosis effect:", type: "multiple_choice", options: [{ text: "Increased vigor of hybrids", icon: "💪", isCorrect: true }, { text: "Yield reduction", icon: "📉", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only in GMO", icon: "🧬", isCorrect: false }], explanation: "Crossing different lines produces more vigorous offspring." }
    ],

    // Level 7 - Certification Systems
    module6_level7: [
        { question: "Organic certification is provided by:", type: "multiple_choice", options: [{ text: "Accredited control organizations", icon: "✅", isCorrect: true }, { text: "The farmer", icon: "👨‍🌾", isCorrect: false }, { text: "Nobody", icon: "❌", isCorrect: false }, { text: "Supermarkets", icon: "🛒", isCorrect: false }], explanation: "Certified bodies verify compliance with organic rules." },
        { question: "EU organic logo is:", type: "multiple_choice", options: [{ text: "Mandatory on organic products", icon: "🌿", isCorrect: true }, { text: "Voluntary", icon: "🤷", isCorrect: false }, { text: "Banned", icon: "⛔", isCorrect: false }, { text: "Only national", icon: "🏳️", isCorrect: false }], explanation: "The green leaf is the unified logo for organic products in EU." },
        { question: "Demeter is:", type: "multiple_choice", options: [{ text: "Biodynamic farming certification", icon: "🌙", isCorrect: true }, { text: "Fertilizer", icon: "🧪", isCorrect: false }, { text: "Pesticide", icon: "💦", isCorrect: false }, { text: "Tractor", icon: "🚜", isCorrect: false }], explanation: "Demeter has stricter rules than standard organic." },
        { question: "Biodynamic agriculture:", type: "multiple_choice", options: [{ text: "Works with cosmic rhythms", icon: "🌙", isCorrect: true }, { text: "Uses more chemicals", icon: "🧪", isCorrect: false }, { text: "Is banned", icon: "⛔", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Biodynamics is based on Rudolf Steiner's teachings." },
        { question: "Permaculture:", type: "multiple_choice", options: [{ text: "Permanent sustainable systems", icon: "♾️", isCorrect: true }, { text: "Only gardening", icon: "🌷", isCorrect: false }, { text: "Intensive agriculture", icon: "🏭", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Permaculture mimics natural ecosystems." },
        { question: "Natural farming (Fukuoka):", type: "multiple_choice", options: [{ text: "Minimal intervention in nature", icon: "🍃", isCorrect: true }, { text: "Intensive plowing", icon: "🚜", isCorrect: false }, { text: "Lots of chemicals", icon: "🧪", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Masanobu Fukuoka promoted farming without tillage and chemicals." },
        { question: "Forest gardens:", type: "multiple_choice", options: [{ text: "Multi-layered growing systems", icon: "🌳", isCorrect: true }, { text: "Only forest", icon: "🌲", isCorrect: false }, { text: "Only garden", icon: "🌷", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Forest gardens combine trees, shrubs, and herbs." },
        { question: "Syntropic agriculture:", type: "multiple_choice", options: [{ text: "Building complex ecosystems", icon: "🌿", isCorrect: true }, { text: "Monocultures", icon: "🌾", isCorrect: false }, { text: "Destroying nature", icon: "❌", isCorrect: false }, { text: "Doesn't exist", icon: "⛔", isCorrect: false }], explanation: "Ernst Götsch developed a system for regenerating degraded soils." },
        { question: "Holistic management:", type: "multiple_choice", options: [{ text: "Whole-system approach to farm management", icon: "🔄", isCorrect: true }, { text: "Only finances", icon: "💰", isCorrect: false }, { text: "Only animals", icon: "🐄", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Allan Savory developed a system for landscape regeneration through grazing." },
        { question: "Community Supported Agriculture:", type: "multiple_choice", options: [{ text: "Direct partnership of farmers and consumers", icon: "🤝", isCorrect: true }, { text: "Supermarket", icon: "🛒", isCorrect: false }, { text: "Export", icon: "✈️", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "CSA shares risks and benefits between farmers and members." }
    ],

    // Level 8 - Conservation & Biodiversity
    module6_level8: [
        { question: "Natura 2000 is:", type: "multiple_choice", options: [{ text: "Network of EU protected areas", icon: "🌍", isCorrect: true }, { text: "Fertilizer", icon: "🧪", isCorrect: false }, { text: "Variety", icon: "🌱", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Natura 2000 protects valuable habitats and species." },
        { question: "Agri-environment schemes are:", type: "multiple_choice", options: [{ text: "Environmental payments", icon: "💶", isCorrect: true }, { text: "Pesticides", icon: "💦", isCorrect: false }, { text: "Fertilizers", icon: "🧪", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "AES reward farmers for environmental services." },
        { question: "Ecological fallows are:", type: "multiple_choice", options: [{ text: "Areas left without production", icon: "🌿", isCorrect: true }, { text: "Intensively used", icon: "🏭", isCorrect: false }, { text: "Banned", icon: "⛔", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Fallows provide shelter and food for wildlife." },
        { question: "Flower strips are:", type: "multiple_choice", options: [{ text: "Strips with flowering plants", icon: "🌸", isCorrect: true }, { text: "Asphalt roads", icon: "🛣️", isCorrect: false }, { text: "Fences", icon: "🚧", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Flower strips support pollinators and natural enemies." },
        { question: "Extensive meadows:", type: "multiple_choice", options: [{ text: "Low-fertilized, species-rich", icon: "🌼", isCorrect: true }, { text: "Intensively fertilized", icon: "🧪", isCorrect: false }, { text: "Without plants", icon: "🏜️", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Extensive meadows are refuges of biodiversity." },
        { question: "Woodlots in the landscape:", type: "multiple_choice", options: [{ text: "Islands of shrubs and trees", icon: "🌳", isCorrect: true }, { text: "Grain fields", icon: "🌾", isCorrect: false }, { text: "Landfills", icon: "🗑️", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Woodlots provide shelter for wildlife and birds." },
        { question: "High Nature Value farming:", type: "multiple_choice", options: [{ text: "HNV - farming supporting biodiversity", icon: "🦋", isCorrect: true }, { text: "Intensive farms", icon: "🏭", isCorrect: false }, { text: "Greenhouses", icon: "🏠", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "HNV systems are key to preserving biodiversity." },
        { question: "Species dependent on agriculture:", type: "multiple_choice", options: [{ text: "Partridge, skylark, lapwing", icon: "🐦", isCorrect: true }, { text: "Only domestic animals", icon: "🐄", isCorrect: false }, { text: "Only pests", icon: "🐛", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }], explanation: "Many species depend on traditional farming practices." },
        { question: "Intensification threatens:", type: "multiple_choice", options: [{ text: "Biodiversity and landscape character", icon: "⚠️", isCorrect: true }, { text: "Nothing", icon: "✅", isCorrect: false }, { text: "Only pests", icon: "🐛", isCorrect: false }, { text: "Only economy", icon: "💰", isCorrect: false }], explanation: "Monotonous landscape without hedges loses species diversity." },
        { question: "Rewilding is:", type: "multiple_choice", options: [{ text: "Return of nature to the landscape", icon: "🐺", isCorrect: true }, { text: "Intensification", icon: "📈", isCorrect: false }, { text: "Urbanization", icon: "🏙️", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Rewilding restores natural processes and large herbivores." }
    ],

    // Level 9 - EU Policy
    module6_level9: [
        { question: "Farm to Fork EU strategy:", type: "multiple_choice", options: [{ text: "Path to sustainable food system", icon: "🍴", isCorrect: true }, { text: "New fast food", icon: "🍔", isCorrect: false }, { text: "Transport company", icon: "🚛", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "F2F is part of the European Green Deal." },
        { question: "Green Deal aims at:", type: "multiple_choice", options: [{ text: "Climate neutrality by 2050", icon: "🌍", isCorrect: true }, { text: "More emissions", icon: "☁️", isCorrect: false }, { text: "More chemicals", icon: "🧪", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Green Deal transforms EU economy to sustainable." },
        { question: "Target of 25% organic land by 2030:", type: "multiple_choice", options: [{ text: "Is part of Farm to Fork", icon: "🌿", isCorrect: true }, { text: "Is unrealistic", icon: "❌", isCorrect: false }, { text: "Was cancelled", icon: "⛔", isCorrect: false }, { text: "Doesn't exist", icon: "🤷", isCorrect: false }], explanation: "EU wants to significantly expand organic farming." },
        { question: "50% pesticide reduction:", type: "multiple_choice", options: [{ text: "EU target by 2030", icon: "📉", isCorrect: true }, { text: "Increase", icon: "📈", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only recommendation", icon: "🤷", isCorrect: false }], explanation: "EU plans to dramatically reduce pesticide use." },
        { question: "EU Taxonomy:", type: "multiple_choice", options: [{ text: "Classification of sustainable activities", icon: "📋", isCorrect: true }, { text: "Tax", icon: "💰", isCorrect: false }, { text: "Fertilizer", icon: "🧪", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Taxonomy defines what is considered green investment." },
        { question: "CAP (Common Agricultural Policy):", type: "multiple_choice", options: [{ text: "EU's common agricultural policy", icon: "🇪🇺", isCorrect: true }, { text: "Type of hat", icon: "🧢", isCorrect: false }, { text: "American policy", icon: "🇺🇸", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "CAP distributes agricultural subsidies in EU." },
        { question: "Eco-schemes in new CAP:", type: "multiple_choice", options: [{ text: "Voluntary environmental commitments", icon: "🌿", isCorrect: true }, { text: "Mandatory chemicals", icon: "🧪", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }, { text: "Only for organic", icon: "🌱", isCorrect: false }], explanation: "Eco-schemes reward farmers for climate and environmental measures." },
        { question: "Conditionality in CAP:", type: "multiple_choice", options: [{ text: "Conditions for receiving subsidies", icon: "📋", isCorrect: true }, { text: "Air conditioning", icon: "❄️", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only for large farms", icon: "🏭", isCorrect: false }], explanation: "Subsidy recipients must meet basic standards." },
        { question: "Carbon farming strategy:", type: "multiple_choice", options: [{ text: "Support for carbon storage in agriculture", icon: "🌍", isCorrect: true }, { text: "Burning coal", icon: "🔥", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only forests", icon: "🌲", isCorrect: false }], explanation: "EU is preparing carbon credit certification from agriculture." },
        { question: "Biodiversity strategy:", type: "multiple_choice", options: [{ text: "30% protected areas by 2030", icon: "🦋", isCorrect: true }, { text: "Less protection", icon: "📉", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }, { text: "Only oceans", icon: "🌊", isCorrect: false }], explanation: "EU wants to significantly expand protected areas." }
    ],

    // Level 10 - Sustainable Future
    module6_level10: [
        { question: "Sustainable agriculture must:", type: "multiple_choice", options: [{ text: "Balance production, ecology, and economy", icon: "⚖️", isCorrect: true }, { text: "Only maximize profit", icon: "💰", isCorrect: false }, { text: "Only protect nature", icon: "🌿", isCorrect: false }, { text: "Nothing", icon: "❌", isCorrect: false }], explanation: "Three pillars of sustainability must be in balance." },
        { question: "Planetary boundaries:", type: "multiple_choice", options: [{ text: "Limits of Earth's carrying capacity", icon: "🌍", isCorrect: true }, { text: "Country borders", icon: "🗺️", isCorrect: false }, { text: "Don't exist", icon: "❌", isCorrect: false }, { text: "Only theory", icon: "📖", isCorrect: false }], explanation: "Exceeding boundaries threatens climate and ecosystem stability." },
        { question: "Doughnut economics:", type: "multiple_choice", options: [{ text: "Model of sustainable development", icon: "🍩", isCorrect: true }, { text: "Bakery", icon: "🍰", isCorrect: false }, { text: "Type of farm", icon: "🏡", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Kate Raworth designed a model respecting social and ecological limits." },
        { question: "True cost accounting:", type: "multiple_choice", options: [{ text: "Including all costs including externalities", icon: "💰", isCorrect: true }, { text: "Only direct costs", icon: "📊", isCorrect: false }, { text: "No costs", icon: "❌", isCorrect: false }, { text: "Doesn't exist", icon: "⛔", isCorrect: false }], explanation: "True costs include impacts on health and nature." },
        { question: "Agroecological transformation:", type: "multiple_choice", options: [{ text: "Systemic change of food system", icon: "🔄", isCorrect: true }, { text: "Only technical change", icon: "🔧", isCorrect: false }, { text: "Not possible", icon: "❌", isCorrect: false }, { text: "Only for small farms", icon: "🏡", isCorrect: false }], explanation: "Transformation requires changes at all levels of the system." },
        { question: "Food sovereignty:", type: "multiple_choice", options: [{ text: "Right of communities to decide about their food", icon: "🍽️", isCorrect: true }, { text: "Only imports", icon: "✈️", isCorrect: false }, { text: "Only exports", icon: "🚢", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Food sovereignty supports local systems and traditions." },
        { question: "Planetary diet:", type: "multiple_choice", options: [{ text: "Diet healthy for people and planet", icon: "🥗", isCorrect: true }, { text: "Food from space", icon: "🚀", isCorrect: false }, { text: "Only meat", icon: "🥩", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "EAT-Lancet commission proposed a sustainable reference diet." },
        { question: "Local food systems:", type: "multiple_choice", options: [{ text: "Reduce transport emissions and strengthen communities", icon: "🏘️", isCorrect: true }, { text: "Are always more expensive", icon: "💰", isCorrect: false }, { text: "Are impossible", icon: "❌", isCorrect: false }, { text: "Only for the rich", icon: "💎", isCorrect: false }], explanation: "Local systems have many social and ecological benefits." },
        { question: "One Health approach:", type: "multiple_choice", options: [{ text: "Connecting health of people, animals, and ecosystems", icon: "🔗", isCorrect: true }, { text: "Only human health", icon: "👤", isCorrect: false }, { text: "Only veterinary", icon: "🐄", isCorrect: false }, { text: "Doesn't exist", icon: "❌", isCorrect: false }], explanation: "Health of all is connected and requires a holistic approach." },
        { question: "Future of agriculture:", type: "multiple_choice", options: [{ text: "Regenerative, precise, local, fair", icon: "🌱", isCorrect: true }, { text: "More chemicals", icon: "🧪", isCorrect: false }, { text: "Without farmers", icon: "🤖", isCorrect: false }, { text: "None", icon: "❌", isCorrect: false }], explanation: "Sustainable future requires transformation of the entire system." }
    ]
};

// Export to window
window.MODULE6_QUESTIONS = MODULE6_QUESTIONS;
