// Module 7: Mifugo (Livestock) - 100 maswali
// Lugha: Kiswahili (Swahili)
// Nchi: Kenya
// 🐄 Generated for AgroLinguo

const MODULE7_QUESTIONS_SW = {
  "module7_level1": [
    {"question": "Mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Wanyama wanaofugwa kwa faida", "icon": "🐄", "isCorrect": true}, {"text": "Mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Mazao ya shamba", "icon": "❌", "isCorrect": false}, {"text": "Mashine za kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mifugo ni wanyama kama ng'ombe, mbuzi, na kuku wanaofugwa."},
    {"question": "Ng'ombe wa maziwa wanazalisha nini?", "type": "multiple_choice", "options": [{"text": "Maziwa kwa ajili ya kuuza na kutumia", "icon": "🐄", "isCorrect": true}, {"text": "Mayai tu", "icon": "❌", "isCorrect": false}, {"text": "Pamba tu", "icon": "❌", "isCorrect": false}, {"text": "Mazao ya shamba", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Ng'ombe wa maziwa wanazalisha maziwa kila siku."},
    {"question": "Kuku wanazalisha nini?", "type": "multiple_choice", "options": [{"text": "Mayai na nyama", "icon": "🐄", "isCorrect": true}, {"text": "Maziwa tu", "icon": "❌", "isCorrect": false}, {"text": "Pamba tu", "icon": "❌", "isCorrect": false}, {"text": "Mazao ya shamba", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Kuku wanazalisha mayai na nyama."},
    {"question": "Mbuzi wanaweza kula nini?", "type": "multiple_choice", "options": [{"text": "Nyasi, majani, na miti", "icon": "🐄", "isCorrect": true}, {"text": "Nyama tu", "icon": "❌", "isCorrect": false}, {"text": "Samaki tu", "icon": "❌", "isCorrect": false}, {"text": "Plastiki", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Mbuzi ni browser na wanaweza kula mimea mbalimbali."},
    {"question": "Kondoo wanazalisha nini zaidi ya nyama?", "type": "multiple_choice", "options": [{"text": "Pamba (sufu)", "icon": "🐄", "isCorrect": true}, {"text": "Mayai", "icon": "❌", "isCorrect": false}, {"text": "Maziwa mengi", "icon": "❌", "isCorrect": false}, {"text": "Ngozi tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Kondoo wanazalisha sufu ambayo inatumiwa kwa nguo."},
    {"question": "Maji ni muhimu kwa mifugo kwa sababu gani?", "type": "multiple_choice", "options": [{"text": "Kwa kunywa na kudumisha afya", "icon": "🐄", "isCorrect": true}, {"text": "Kwa kupiga mbizi tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kwa mapambo tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Maji safi ni muhimu kwa afya na uzalishaji wa mifugo."},
    {"question": "Banda la ng'ombe linapaswa kuwa na nini?", "type": "multiple_choice", "options": [{"text": "Hewa ya kutosha, sakafu safi, na paa", "icon": "🐄", "isCorrect": true}, {"text": "Giza kamili", "icon": "❌", "isCorrect": false}, {"text": "Maji mengi sakafuni", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Mazingira mazuri yanaboresha afya na uzalishaji."},
    {"question": "Chanjo ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kuzuia magonjwa", "icon": "🐄", "isCorrect": true}, {"text": "Kuongeza uzito haraka", "icon": "❌", "isCorrect": false}, {"text": "Kubadilisha rangi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Chanjo inazuia magonjwa hatari kwa mifugo."},
    {"question": "Bata wanazalisha nini?", "type": "multiple_choice", "options": [{"text": "Mayai na nyama", "icon": "🐄", "isCorrect": true}, {"text": "Maziwa", "icon": "❌", "isCorrect": false}, {"text": "Pamba", "icon": "❌", "isCorrect": false}, {"text": "Mazao ya shamba", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Bata wanazalisha mayai makubwa na nyama."},
    {"question": "Nguruwe wanafaa kwa nini?", "type": "multiple_choice", "options": [{"text": "Nyama na kupata faida haraka", "icon": "🐄", "isCorrect": true}, {"text": "Maziwa tu", "icon": "❌", "isCorrect": false}, {"text": "Mayai tu", "icon": "❌", "isCorrect": false}, {"text": "Pamba tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Nguruwe wanakua haraka na wana nyama nyingi."}
  ],
  "module7_level2": [
    {"question": "Dairy farming ni nini?", "type": "multiple_choice", "options": [{"text": "Ufugaji wa ng'ombe wa maziwa", "icon": "🐄", "isCorrect": true}, {"text": "Ufugaji wa kuku tu", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha mahindi tu", "icon": "❌", "isCorrect": false}, {"text": "Uvuvi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Dairy farming inalenga uzalishaji wa maziwa."},
    {"question": "Friesian ni aina gani ya ng'ombe?", "type": "multiple_choice", "options": [{"text": "Ng'ombe wa maziwa wenye rangi nyeusi na nyeupe", "icon": "🐄", "isCorrect": true}, {"text": "Ng'ombe wa nyama tu", "icon": "❌", "isCorrect": false}, {"text": "Mbuzi", "icon": "❌", "isCorrect": false}, {"text": "Kondoo", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Friesian ni ng'ombe wa maziwa maarufu Kenya."},
    {"question": "Silage ni nini?", "type": "multiple_choice", "options": [{"text": "Chakula cha mifugo kilichohifadhiwa kwa kuoza", "icon": "🐄", "isCorrect": true}, {"text": "Dawa ya mifugo", "icon": "❌", "isCorrect": false}, {"text": "Aina ya mbegu", "icon": "❌", "isCorrect": false}, {"text": "Maji ya kunywa", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Silage ni nyasi zilizohifadhiwa kwa fermentation."},
    {"question": "Deworming ni nini?", "type": "multiple_choice", "options": [{"text": "Kutoa dawa ya minyoo kwa mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Kukata pembe", "icon": "❌", "isCorrect": false}, {"text": "Kunyoa pamba", "icon": "❌", "isCorrect": false}, {"text": "Kupiga chanjo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Deworming inazuia minyoo wanaosababisha mifugo kudhoofika."},
    {"question": "Hoof trimming ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kuzuia maumivu na matatizo ya kutembea", "icon": "🐄", "isCorrect": true}, {"text": "Kupamba mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kuongeza maziwa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Kwato zilizokua sana zinasababisha maumivu."},
    {"question": "Broiler ni kuku wa aina gani?", "type": "multiple_choice", "options": [{"text": "Kuku wanaolewa kwa nyama", "icon": "🐄", "isCorrect": true}, {"text": "Kuku wa mayai tu", "icon": "❌", "isCorrect": false}, {"text": "Kuku wa kuzaliana tu", "icon": "❌", "isCorrect": false}, {"text": "Kuku wa kienyeji tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Broilers wanakua haraka na wana nyama nyingi."},
    {"question": "Layer ni kuku wa aina gani?", "type": "multiple_choice", "options": [{"text": "Kuku wanaolewa kwa mayai", "icon": "🐄", "isCorrect": true}, {"text": "Kuku wa nyama tu", "icon": "❌", "isCorrect": false}, {"text": "Kuku wa mapambo", "icon": "❌", "isCorrect": false}, {"text": "Bata", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Layers wanaweza kutaga mayai 250+ kwa mwaka."},
    {"question": "Incubator ni nini?", "type": "multiple_choice", "options": [{"text": "Mashine ya kuangulia mayai", "icon": "🐄", "isCorrect": true}, {"text": "Banda la kuku", "icon": "❌", "isCorrect": false}, {"text": "Chombo cha maji", "icon": "❌", "isCorrect": false}, {"text": "Aina ya chakula", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Incubator inatoa joto la kuangulia bila kuku."},
    {"question": "Crossbreeding ni nini?", "type": "multiple_choice", "options": [{"text": "Kuzaliana aina mbili tofauti za mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Kuzaliana ndugu", "icon": "❌", "isCorrect": false}, {"text": "Kutumia mashine", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Crossbreeding inaweza kuboresha sifa za mifugo."},
    {"question": "AI (Artificial Insemination) ni nini?", "type": "multiple_choice", "options": [{"text": "Kupandisha mifugo bila dume kuwepo", "icon": "🐄", "isCorrect": true}, {"text": "Kompyuta ya kilimo", "icon": "❌", "isCorrect": false}, {"text": "Chakula cha mifugo", "icon": "❌", "isCorrect": false}, {"text": "Dawa ya mifugo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! AI inaruhusu kupata mbegu bora kutoka madume bora."}
  ],
  "module7_level3": [
    {"question": "Mastitis ni ugonjwa gani?", "type": "multiple_choice", "options": [{"text": "Ugonjwa wa matiti ya ng'ombe", "icon": "🐄", "isCorrect": true}, {"text": "Ugonjwa wa miguu", "icon": "❌", "isCorrect": false}, {"text": "Ugonjwa wa macho", "icon": "❌", "isCorrect": false}, {"text": "Ugonjwa wa masikio", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mastitis inasababishwa na bacteria na inapunguza maziwa."},
    {"question": "Foot and Mouth Disease (FMD) inaathiri nini?", "type": "multiple_choice", "options": [{"text": "Miguu na mdomo wa mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Mabawa tu", "icon": "❌", "isCorrect": false}, {"text": "Mayai tu", "icon": "❌", "isCorrect": false}, {"text": "Maziwa tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! FMD ni ugonjwa wa virusi unaoenea haraka."},
    {"question": "Newcastle disease inaathiri mifugo gani?", "type": "multiple_choice", "options": [{"text": "Kuku na ndege wengine", "icon": "🐄", "isCorrect": true}, {"text": "Ng'ombe tu", "icon": "❌", "isCorrect": false}, {"text": "Mbuzi tu", "icon": "❌", "isCorrect": false}, {"text": "Nguruwe tu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Newcastle ni ugonjwa hatari kwa kuku."},
    {"question": "East Coast Fever (ECF) husababishwa na nini?", "type": "multiple_choice", "options": [{"text": "Kupe wanaosambaza protozoa", "icon": "🐄", "isCorrect": true}, {"text": "Maji machafu", "icon": "❌", "isCorrect": false}, {"text": "Chakula kibaya", "icon": "❌", "isCorrect": false}, {"text": "Hewa chafu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! ECF inasambazwa na kupe na ni hatari kwa ng'ombe."},
    {"question": "Dipping ni nini?", "type": "multiple_choice", "options": [{"text": "Kuogesha mifugo kwa dawa ya kupe", "icon": "🐄", "isCorrect": true}, {"text": "Kuogesha kwa maji tu", "icon": "❌", "isCorrect": false}, {"text": "Kulisha mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kukamua maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Dipping inazuia kupe na magonjwa wanayosambaza."},
    {"question": "Coccidiosis inaathiri mifugo gani?", "type": "multiple_choice", "options": [{"text": "Kuku na ndama", "icon": "🐄", "isCorrect": true}, {"text": "Samaki tu", "icon": "❌", "isCorrect": false}, {"text": "Ng'ombe wakubwa tu", "icon": "❌", "isCorrect": false}, {"text": "Mimea", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Coccidiosis ni ugonjwa wa matumbo wa vifaranga na ndama."},
    {"question": "Rabies ni hatari kwa nini?", "type": "multiple_choice", "options": [{"text": "Inasambaa kwa binadamu na kusababisha kifo", "icon": "🐄", "isCorrect": true}, {"text": "Haienei", "icon": "❌", "isCorrect": false}, {"text": "Inaathiri mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna hatari", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Rabies ni ugonjwa wa virusi unaosambazwa na kuumwa."},
    {"question": "Anthrax ni ugonjwa gani?", "type": "multiple_choice", "options": [{"text": "Ugonjwa wa bacteria unaoua haraka", "icon": "🐄", "isCorrect": true}, {"text": "Ugonjwa wa ngozi tu", "icon": "❌", "isCorrect": false}, {"text": "Ugonjwa wa mimea", "icon": "❌", "isCorrect": false}, {"text": "Haukubalishi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Anthrax ni hatari na inaweza kuenea kwa binadamu."},
    {"question": "Bloat ni tatizo gani kwa mifugo?", "type": "multiple_choice", "options": [{"text": "Gesi kujikusanya tumboni na kusababisha hatari", "icon": "🐄", "isCorrect": true}, {"text": "Kupunguza uzito", "icon": "❌", "isCorrect": false}, {"text": "Rangi kubadilika", "icon": "❌", "isCorrect": false}, {"text": "Hakuna tatizo", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Bloat inaweza kuua haraka ikiwa haitatibiwa."},
    {"question": "Quarantine kwa mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kuwatenga mifugo wapya au wagonjwa", "icon": "🐄", "isCorrect": true}, {"text": "Kuwauza wote", "icon": "❌", "isCorrect": false}, {"text": "Kuwachanganya wote", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Quarantine inazuia kuenea kwa magonjwa."}
  ],
  "module7_level4": [
    {"question": "Total Mixed Ration (TMR) ni nini?", "type": "multiple_choice", "options": [{"text": "Chakula cha ng'ombe kilichochanganywa kwa usawa", "icon": "🐄", "isCorrect": true}, {"text": "Dawa ya mifugo", "icon": "❌", "isCorrect": false}, {"text": "Mbegu za kupanda", "icon": "❌", "isCorrect": false}, {"text": "Maji ya kunywa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! TMR inaweka virutubisho vyote pamoja kwa kila mlo."},
    {"question": "Crude Protein (CP) ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kwa ukuaji na uzalishaji wa maziwa", "icon": "🐄", "isCorrect": true}, {"text": "Rangi ya ngozi tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kwa manyoya tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Protini ni msingi wa ukuaji na uzalishaji."},
    {"question": "Dry Matter Intake (DMI) ni nini?", "type": "multiple_choice", "options": [{"text": "Kiasi cha chakula kavu kinacholiwa na mnyama", "icon": "🐄", "isCorrect": true}, {"text": "Maji yanayonywewa", "icon": "❌", "isCorrect": false}, {"text": "Uzito wa mnyama", "icon": "❌", "isCorrect": false}, {"text": "Bei ya chakula", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! DMI inaonyesha kiasi halisi cha virutubisho."},
    {"question": "Concentrate feed ni nini?", "type": "multiple_choice", "options": [{"text": "Chakula chenye nguvu nyingi kwa ujazo mdogo", "icon": "🐄", "isCorrect": true}, {"text": "Nyasi tu", "icon": "❌", "isCorrect": false}, {"text": "Maji tu", "icon": "❌", "isCorrect": false}, {"text": "Dawa tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Concentrates kama dairy meal zina virutubisho vingi."},
    {"question": "Roughage ni nini?", "type": "multiple_choice", "options": [{"text": "Chakula chenye nyuzi nyingi kama nyasi na silage", "icon": "🐄", "isCorrect": true}, {"text": "Chakula cha nguvu tu", "icon": "❌", "isCorrect": false}, {"text": "Maji tu", "icon": "❌", "isCorrect": false}, {"text": "Dawa tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Roughage ni muhimu kwa rumen ya ng'ombe."},
    {"question": "Rumen ni nini?", "type": "multiple_choice", "options": [{"text": "Tumbo la kwanza la ng'ombe lenye microbes", "icon": "🐄", "isCorrect": true}, {"text": "Ini", "icon": "❌", "isCorrect": false}, {"text": "Moyo", "icon": "❌", "isCorrect": false}, {"text": "Ubongo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Rumen ina bacteria zinazosaga nyasi."},
    {"question": "Body Condition Score (BCS) inaonyesha nini?", "type": "multiple_choice", "options": [{"text": "Hali ya mwili wa mnyama (mafuta vs misuli)", "icon": "🐄", "isCorrect": true}, {"text": "Rangi ya ngozi tu", "icon": "❌", "isCorrect": false}, {"text": "Umri wa mnyama", "icon": "❌", "isCorrect": false}, {"text": "Bei ya mnyama", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! BCS inasaidia kuamua lishe na afya."},
    {"question": "Mineral lick ni nini?", "type": "multiple_choice", "options": [{"text": "Jiwe la madini kwa mifugo kulamba", "icon": "🐄", "isCorrect": true}, {"text": "Dawa ya kunywa", "icon": "❌", "isCorrect": false}, {"text": "Chakula cha kawaida", "icon": "❌", "isCorrect": false}, {"text": "Maji ya kuosha", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Mineral lick inatoa madini muhimu kama chumvi."},
    {"question": "Metabolic energy (ME) ni nini?", "type": "multiple_choice", "options": [{"text": "Nguvu inayopatikana kutoka chakula", "icon": "🐄", "isCorrect": true}, {"text": "Uzito wa chakula", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya chakula", "icon": "❌", "isCorrect": false}, {"text": "Bei ya chakula", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! ME inaonyesha kiasi cha nishati kinachoweza kutumika."},
    {"question": "Colostrum ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kutoa kingamwili kwa ndama/vifaranga wachanga", "icon": "🐄", "isCorrect": true}, {"text": "Kupambwa tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kwa watu wazima tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Colostrum ina antibodies muhimu kwa watoto wachanga."}
  ],
  "module7_level5": [
    {"question": "Selective breeding ni nini?", "type": "multiple_choice", "options": [{"text": "Kuchagua wazazi bora kuzalisha vizazi bora", "icon": "🐄", "isCorrect": true}, {"text": "Kuzaliana bila mpango", "icon": "❌", "isCorrect": false}, {"text": "Kununua mifugo yoyote", "icon": "❌", "isCorrect": false}, {"text": "Kuuza mifugo yote", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Selective breeding inaboresha sifa za mifugo kwa muda."},
    {"question": "Expected Progeny Difference (EPD) ni nini?", "type": "multiple_choice", "options": [{"text": "Utabiri wa sifa za watoto wa mfugo", "icon": "🐄", "isCorrect": true}, {"text": "Bei ya mnyama", "icon": "❌", "isCorrect": false}, {"text": "Uzito wa mnyama", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya mnyama", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! EPDs zinasaidia kuchagua wazazi bora."},
    {"question": "Heritability ni nini?", "type": "multiple_choice", "options": [{"text": "Uwezekano wa sifa kupitishwa kwa vizazi", "icon": "🐄", "isCorrect": true}, {"text": "Bei ya mnyama", "icon": "❌", "isCorrect": false}, {"text": "Uzito wa mnyama", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya mnyama", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Sifa zenye heritability ya juu zinaweza kubadilishwa haraka."},
    {"question": "Inbreeding ni hatari kwa nini?", "type": "multiple_choice", "options": [{"text": "Inaweza kusababisha matatizo ya kijeni", "icon": "🐄", "isCorrect": true}, {"text": "Inaboresha mifugo", "icon": "❌", "isCorrect": false}, {"text": "Hakuna hatari", "icon": "❌", "isCorrect": false}, {"text": "Inaongeza mavuno", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Inbreeding inapunguza tofauti za kijeni na inaweza kuleta matatizo."},
    {"question": "Heterosis/Hybrid vigor ni nini?", "type": "multiple_choice", "options": [{"text": "Watoto wa chotara kuwa bora kuliko wazazi", "icon": "🐄", "isCorrect": true}, {"text": "Watoto kudhoofika", "icon": "❌", "isCorrect": false}, {"text": "Hakuna tofauti", "icon": "❌", "isCorrect": false}, {"text": "Bei ya juu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Heterosis inapatikana kwa crossbreeding."},
    {"question": "Genomic selection ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia DNA kuchagua mifugo bora", "icon": "🐄", "isCorrect": true}, {"text": "Kuchagua kwa rangi tu", "icon": "❌", "isCorrect": false}, {"text": "Kuchagua kwa bei tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Genomic selection inaboresha usahihi wa kuchagua."},
    {"question": "Semen quality inapimwa vipi?", "type": "multiple_choice", "options": [{"text": "Kwa motility, concentration, na morphology", "icon": "🐄", "isCorrect": true}, {"text": "Kwa rangi tu", "icon": "❌", "isCorrect": false}, {"text": "Kwa harufu tu", "icon": "❌", "isCorrect": false}, {"text": "Haipimwi", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Semen quality nzuri inaongeza conception rate."},
    {"question": "Estrus/Heat detection ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kujua wakati sahihi wa kupandisha", "icon": "🐄", "isCorrect": true}, {"text": "Kujua wakati wa kukamua", "icon": "❌", "isCorrect": false}, {"text": "Kujua bei", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Kupandisha wakati wa heat kunaongeza uwezekano wa kupata mimba."},
    {"question": "Pregnancy diagnosis inapaswa kufanywa lini?", "type": "multiple_choice", "options": [{"text": "Siku 28-60 baada ya kupandisha", "icon": "🐄", "isCorrect": true}, {"text": "Siku moja tu", "icon": "❌", "isCorrect": false}, {"text": "Mwaka mmoja baadaye", "icon": "❌", "isCorrect": false}, {"text": "Haihitajiki", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Kuthibitisha mimba mapema kunasaidia usimamizi."},
    {"question": "Calving interval ni nini?", "type": "multiple_choice", "options": [{"text": "Muda kati ya kuzaa na kuzaa tena", "icon": "🐄", "isCorrect": true}, {"text": "Muda wa kukamua", "icon": "❌", "isCorrect": false}, {"text": "Muda wa kulisha", "icon": "❌", "isCorrect": false}, {"text": "Bei ya ndama", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Calving interval fupi inaongeza uzalishaji wa maisha."}
  ],
  "module7_level6": [
    {"question": "Milking parlour ni nini?", "type": "multiple_choice", "options": [{"text": "Sehemu maalum ya kukamua maziwa", "icon": "🐄", "isCorrect": true}, {"text": "Banda la kulala", "icon": "❌", "isCorrect": false}, {"text": "Sehemu ya kulisha", "icon": "❌", "isCorrect": false}, {"text": "Duka la maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Milking parlour inaongeza ufanisi wa kukamua."},
    {"question": "Bulk milk tank ni nini?", "type": "multiple_choice", "options": [{"text": "Tanki kubwa ya kuhifadhi maziwa baridi", "icon": "🐄", "isCorrect": true}, {"text": "Tanki ya maji", "icon": "❌", "isCorrect": false}, {"text": "Tanki ya mafuta", "icon": "❌", "isCorrect": false}, {"text": "Tanki ya chakula", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Bulk tank inapoza maziwa haraka kuhifadhi ubora."},
    {"question": "Somatic Cell Count (SCC) inaonyesha nini?", "type": "multiple_choice", "options": [{"text": "Afya ya kiwele - SCC ya juu inaonyesha mastitis", "icon": "🐄", "isCorrect": true}, {"text": "Rangi ya maziwa", "icon": "❌", "isCorrect": false}, {"text": "Ladha ya maziwa", "icon": "❌", "isCorrect": false}, {"text": "Bei ya maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! SCC ndogo inaonyesha maziwa bora."},
    {"question": "Teat dipping ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumbukiza chuchu kwenye dawa baada ya kukamua", "icon": "🐄", "isCorrect": true}, {"text": "Kuosha ng'ombe mzima", "icon": "❌", "isCorrect": false}, {"text": "Kulisha ng'ombe", "icon": "❌", "isCorrect": false}, {"text": "Kupandisha ng'ombe", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Teat dipping inazuia bacteria kuingia na kusababisha mastitis."},
    {"question": "Dry period ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kiwele kupumzika na kujiandaa kwa lactation mpya", "icon": "🐄", "isCorrect": true}, {"text": "Ng'ombe kukimbia", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kuuza ng'ombe", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Dry period ya wiki 6-8 inaboresha lactation ijayo."},
    {"question": "Peak milk production inakuja lini?", "type": "multiple_choice", "options": [{"text": "Wiki 6-8 baada ya kuzaa", "icon": "🐄", "isCorrect": true}, {"text": "Mara baada ya kuzaa", "icon": "❌", "isCorrect": false}, {"text": "Mwaka mmoja baadaye", "icon": "❌", "isCorrect": false}, {"text": "Kabla ya kuzaa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Peak inaonyesha uwezo wa ng'ombe kuzalisha."},
    {"question": "Lactation curve ni nini?", "type": "multiple_choice", "options": [{"text": "Mfumo wa uzalishaji wa maziwa kwa muda", "icon": "🐄", "isCorrect": true}, {"text": "Njia ya kukamua", "icon": "❌", "isCorrect": false}, {"text": "Aina ya ng'ombe", "icon": "❌", "isCorrect": false}, {"text": "Bei ya maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Lactation curve inaonyesha peak na kushuka kwa uzalishaji."},
    {"question": "Milking hygiene ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kuzuia uchafuzi na magonjwa kwenye maziwa", "icon": "🐄", "isCorrect": true}, {"text": "Kupamba ng'ombe", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kuuza ng'ombe", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Usafi unazuia bacteria kuingia kwenye maziwa."},
    {"question": "Strip cup test ni nini?", "type": "multiple_choice", "options": [{"text": "Kuangalia maziwa ya kwanza kwa ishara za mastitis", "icon": "🐄", "isCorrect": true}, {"text": "Kupima uzito wa maziwa", "icon": "❌", "isCorrect": false}, {"text": "Kupima bei ya maziwa", "icon": "❌", "isCorrect": false}, {"text": "Kuchanganya maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Strip cup inaonyesha mabadiliko katika maziwa mapema."},
    {"question": "Milk let-down reflex ni nini?", "type": "multiple_choice", "options": [{"text": "Oxytocin kusababisha maziwa kutoka", "icon": "🐄", "isCorrect": true}, {"text": "Ng'ombe kukataa kukamua", "icon": "❌", "isCorrect": false}, {"text": "Maziwa kuharibika", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Let-down inahitaji mazingira ya utulivu na ratiba."}
  ],
  "module7_level7": [
    {"question": "Precision livestock farming ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia teknolojia kufuatilia na kusimamia mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Kufuga bila teknolojia", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kuuza mifugo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! PLF inatumia sensors na data kuboresha usimamizi."},
    {"question": "Activity monitors kwa ng'ombe zinafanya nini?", "type": "multiple_choice", "options": [{"text": "Kufuatilia mwendo, heat, na afya", "icon": "🐄", "isCorrect": true}, {"text": "Kupima maziwa tu", "icon": "❌", "isCorrect": false}, {"text": "Kulisha ng'ombe", "icon": "❌", "isCorrect": false}, {"text": "Kuuza ng'ombe", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Activity monitors zinaonyesha mabadiliko ya tabia."},
    {"question": "Automatic milking system (AMS) ni nini?", "type": "multiple_choice", "options": [{"text": "Roboti inayokamua ng'ombe bila binadamu", "icon": "🐄", "isCorrect": true}, {"text": "Kamba ya kukamua", "icon": "❌", "isCorrect": false}, {"text": "Mtu anayekamua", "icon": "❌", "isCorrect": false}, {"text": "Tanki ya maziwa", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! AMS inaruhusu ng'ombe kukamua wakati wanapotaka."},
    {"question": "RFID tags kwa mifugo zinasaidia vipi?", "type": "multiple_choice", "options": [{"text": "Kutambua na kufuatilia kila mnyama", "icon": "🐄", "isCorrect": true}, {"text": "Kupamba mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kulisha mifugo", "icon": "❌", "isCorrect": false}, {"text": "Hakuna msaada", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! RFID inawezesha usimamizi wa data kwa kila mnyama."},
    {"question": "Rumen bolus ni nini?", "type": "multiple_choice", "options": [{"text": "Sensor inayomezwa kupima hali ya tumbo", "icon": "🐄", "isCorrect": true}, {"text": "Dawa ya tumbo", "icon": "❌", "isCorrect": false}, {"text": "Chakula maalum", "icon": "❌", "isCorrect": false}, {"text": "Maji ya kunywa", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Rumen bolus inapima pH na joto kutabiri afya."},
    {"question": "Heat detection devices zinafanya kazi vipi?", "type": "multiple_choice", "options": [{"text": "Kupima mabadiliko ya activity na tabia", "icon": "🐄", "isCorrect": true}, {"text": "Kupima joto la hewa", "icon": "❌", "isCorrect": false}, {"text": "Kupima maziwa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kazi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Devices zinaonyesha wakati sahihi wa kupandisha."},
    {"question": "Milk meters zinafanya nini?", "type": "multiple_choice", "options": [{"text": "Kupima kiasi cha maziwa kwa kila ng'ombe", "icon": "🐄", "isCorrect": true}, {"text": "Kupima joto tu", "icon": "❌", "isCorrect": false}, {"text": "Kupima uzito tu", "icon": "❌", "isCorrect": false}, {"text": "Kupima bei tu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Milk meters zinasaidia kufuatilia uzalishaji wa kila ng'ombe."},
    {"question": "Drone kwa mifugo inatumika vipi?", "type": "multiple_choice", "options": [{"text": "Kufuatilia na kuhesabu mifugo kwenye malisho", "icon": "🐄", "isCorrect": true}, {"text": "Kukamua maziwa", "icon": "❌", "isCorrect": false}, {"text": "Kulisha mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kuuza mifugo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Drones zinafaa kwa mashamba makubwa ya malisho."},
    {"question": "Facial recognition kwa ng'ombe ni nini?", "type": "multiple_choice", "options": [{"text": "Kutambua ng'ombe kwa uso wao", "icon": "🐄", "isCorrect": true}, {"text": "Kupaka rangi", "icon": "❌", "isCorrect": false}, {"text": "Kupima maziwa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! AI inaweza kutambua ng'ombe binafsi kwa uso."},
    {"question": "Smart feeding systems zinafanya nini?", "type": "multiple_choice", "options": [{"text": "Kutoa chakula kulingana na mahitaji ya kila mnyama", "icon": "🐄", "isCorrect": true}, {"text": "Kulisha wote sawa", "icon": "❌", "isCorrect": false}, {"text": "Kutolisha kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kuuza chakula", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Smart feeders zinapunguza upotevu na kuboresha ufanisi."}
  ],
  "module7_level8": [
    {"question": "Carbon footprint ya mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Gesi chafu zinazotolewa na ufugaji", "icon": "🐄", "isCorrect": true}, {"text": "Alama ya kwato", "icon": "❌", "isCorrect": false}, {"text": "Bei ya mifugo", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya mifugo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mifugo, hasa ng'ombe, wanachangia emissions za methane."},
    {"question": "Methane emissions kutoka ng'ombe zinaweza kupunguzwa vipi?", "type": "multiple_choice", "options": [{"text": "Kwa kuboresha lishe na kutumia additives", "icon": "🐄", "isCorrect": true}, {"text": "Kwa kulisha zaidi", "icon": "❌", "isCorrect": false}, {"text": "Haziwezi kupunguzwa", "icon": "❌", "isCorrect": false}, {"text": "Kwa kuongeza ng'ombe", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Lishe bora na additives kama seaweed zinapunguza methane."},
    {"question": "Manure management ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Kupunguza uchafuzi na kutumia kama mbolea", "icon": "🐄", "isCorrect": true}, {"text": "Kupoteza samadi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Kuuza samadi tu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Samadi inaweza kuwa rasilimali au tatizo."},
    {"question": "Biogas kutoka samadi ni nini?", "type": "multiple_choice", "options": [{"text": "Gesi ya kupikia inayotoka kwa kuoza samadi", "icon": "🐄", "isCorrect": true}, {"text": "Gesi ya magari tu", "icon": "❌", "isCorrect": false}, {"text": "Gesi hatari tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Biogas ni nishati safi kutoka kwa mabaki ya mifugo."},
    {"question": "Silvopasture ina faida gani za mazingira?", "type": "multiple_choice", "options": [{"text": "Kuhifadhi kaboni, kutoa kivuli, na kuboresha biodiversity", "icon": "🐄", "isCorrect": true}, {"text": "Kupunguza miti", "icon": "❌", "isCorrect": false}, {"text": "Kuongeza emissions", "icon": "❌", "isCorrect": false}, {"text": "Hakuna faida", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Silvopasture inaunganisha miti na malisho kwa faida nyingi."},
    {"question": "Rotational grazing ni nini?", "type": "multiple_choice", "options": [{"text": "Kuzungusha mifugo kati ya paddocks", "icon": "🐄", "isCorrect": true}, {"text": "Kulisha sehemu moja tu", "icon": "❌", "isCorrect": false}, {"text": "Kutolisha kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kulisha ndani tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Rotational grazing inaboresha malisho na udongo."},
    {"question": "Water footprint ya nyama ni nini?", "type": "multiple_choice", "options": [{"text": "Maji yanayotumika kuzalisha nyama", "icon": "🐄", "isCorrect": true}, {"text": "Alama ya maji kwenye nyama", "icon": "❌", "isCorrect": false}, {"text": "Bei ya maji", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Nyama ya ng'ombe ina water footprint kubwa."},
    {"question": "Antibiotic resistance ni tatizo gani?", "type": "multiple_choice", "options": [{"text": "Bacteria kustahimili dawa kwa sababu ya matumizi mengi", "icon": "🐄", "isCorrect": true}, {"text": "Dawa kuwa na nguvu zaidi", "icon": "❌", "isCorrect": false}, {"text": "Mifugo kuwa na afya zaidi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna tatizo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Kutumia antibiotics vizuri kunazuia resistance."},
    {"question": "Welfare indicators ni nini?", "type": "multiple_choice", "options": [{"text": "Viashiria vinavyoonyesha ustawi wa mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Bei ya mifugo", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya mifugo", "icon": "❌", "isCorrect": false}, {"text": "Umri wa mifugo", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Welfare inahusu afya ya kimwili na kisaikolojia."},
    {"question": "Five Freedoms za ustawi wa mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Haki za msingi za mifugo kuishi vizuri", "icon": "🐄", "isCorrect": true}, {"text": "Aina tano za mifugo", "icon": "❌", "isCorrect": false}, {"text": "Bei tano", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Five Freedoms zinajumuisha kutokuwa na njaa, hofu, maumivu, n.k."}
  ],
  "module7_level9": [
    {"question": "Gene editing kwa mifugo kinaweza kutoa nini?", "type": "multiple_choice", "options": [{"text": "Mifugo yenye sifa bora kama ustahimilivu wa magonjwa", "icon": "🐄", "isCorrect": true}, {"text": "Mifugo wadogo tu", "icon": "❌", "isCorrect": false}, {"text": "Rangi mpya tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna faida", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Gene editing inaweza kuboresha afya na uzalishaji."},
    {"question": "CRISPR katika ufugaji inaweza kutumika vipi?", "type": "multiple_choice", "options": [{"text": "Kubadilisha jeni kwa ustahimilivu au uzalishaji bora", "icon": "🐄", "isCorrect": true}, {"text": "Kupaka rangi", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mifugo", "icon": "❌", "isCorrect": false}, {"text": "Hakuna matumizi", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! CRISPR inaweza kuondoa magonjwa ya kijeni."},
    {"question": "Sexed semen ni nini?", "type": "multiple_choice", "options": [{"text": "Mbegu iliyochaguliwa kutoa jinsia maalum", "icon": "🐄", "isCorrect": true}, {"text": "Mbegu ya kawaida", "icon": "❌", "isCorrect": false}, {"text": "Mbegu ya mimea", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Sexed semen inaruhusu kuzalisha jinsia inayohitajika."},
    {"question": "Embryo transfer ni nini?", "type": "multiple_choice", "options": [{"text": "Kuhamisha embryo kutoka mama bora hadi mama mlezi", "icon": "🐄", "isCorrect": true}, {"text": "Kupandisha kawaida", "icon": "❌", "isCorrect": false}, {"text": "Kumpa dawa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! ET inaruhusu ng'ombe bora kutoa watoto wengi."},
    {"question": "Cloning ya mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kuunda nakala kamili ya mnyama", "icon": "🐄", "isCorrect": true}, {"text": "Kuzaliana kawaida", "icon": "❌", "isCorrect": false}, {"text": "Kupaka rangi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Cloning inaunda mnyama na DNA sawa na asili."},
    {"question": "Microbiome engineering kwa mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kubadilisha bacteria za tumbo kuboresha digestion", "icon": "🐄", "isCorrect": true}, {"text": "Kupaka dawa", "icon": "❌", "isCorrect": false}, {"text": "Kubadilisha rangi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Microbiome bora inaweza kupunguza methane na kuboresha afya."},
    {"question": "Cellular agriculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kuzalisha bidhaa za mifugo bila wanyama", "icon": "🐄", "isCorrect": true}, {"text": "Kufuga wanyama tu", "icon": "❌", "isCorrect": false}, {"text": "Kupanda mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Lab-grown meat na dairy zinatengenezwa bila wanyama."},
    {"question": "Digital twin ya shamba la mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Mfano wa kidijitali wa shamba kwa uchambuzi", "icon": "🐄", "isCorrect": true}, {"text": "Mashamba mawili", "icon": "❌", "isCorrect": false}, {"text": "Picha ya shamba", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Digital twin inasaidia kupanga na kuboresha operesheni."},
    {"question": "Blockchain kwa traceability ya mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kufuatilia historia ya mnyama kwa uwazi", "icon": "🐄", "isCorrect": true}, {"text": "Kufunga mifugo", "icon": "❌", "isCorrect": false}, {"text": "Kuuza mifugo tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Blockchain inatoa historia isiyobadilika ya bidhaa."},
    {"question": "AI katika disease detection kwa mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kompyuta kutambua magonjwa mapema", "icon": "🐄", "isCorrect": true}, {"text": "Kutibu magonjwa", "icon": "❌", "isCorrect": false}, {"text": "Kueneza magonjwa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! AI inaweza kutambua ishara za ugonjwa kabla ya binadamu."}
  ],
  "module7_level10": [
    {"question": "One Health approach katika ufugaji ni nini?", "type": "multiple_choice", "options": [{"text": "Kuunganisha afya ya mifugo, binadamu, na mazingira", "icon": "🐄", "isCorrect": true}, {"text": "Afya ya mifugo tu", "icon": "❌", "isCorrect": false}, {"text": "Afya ya binadamu tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna uhusiano", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! One Health inatambua uhusiano wa afya zote."},
    {"question": "Zoonotic diseases ni nini?", "type": "multiple_choice", "options": [{"text": "Magonjwa yanayopita kutoka wanyama hadi binadamu", "icon": "🐄", "isCorrect": true}, {"text": "Magonjwa ya mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Magonjwa ya binadamu tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna magonjwa kama hayo", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Zoonoses kama rabies na avian flu zinaathiri binadamu."},
    {"question": "Antimicrobial stewardship ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia antibiotics kwa busara kuzuia resistance", "icon": "🐄", "isCorrect": true}, {"text": "Kutumia antibiotics nyingi", "icon": "❌", "isCorrect": false}, {"text": "Kutotumia dawa kabisa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Stewardship inahifadhi ufanisi wa antibiotics."},
    {"question": "Climate-smart livestock systems ni nini?", "type": "multiple_choice", "options": [{"text": "Ufugaji unaostahimili na kupunguza athari za hali ya hewa", "icon": "🐄", "isCorrect": true}, {"text": "Ufugaji wa kawaida", "icon": "❌", "isCorrect": false}, {"text": "Kutofuga kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kuongeza emissions", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Climate-smart systems zinajiandaa kwa mabadiliko ya hali ya hewa."},
    {"question": "Alternative proteins zinaathiri vipi ufugaji wa jadi?", "type": "multiple_choice", "options": [{"text": "Zinashindana na bidhaa za mifugo", "icon": "🐄", "isCorrect": true}, {"text": "Zinasaidia ufugaji", "icon": "❌", "isCorrect": false}, {"text": "Hakuna athari", "icon": "❌", "isCorrect": false}, {"text": "Zinaongeza bei ya nyama", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Plant-based na lab-grown proteins ni ushindani mpya."},
    {"question": "Insect farming kwa chakula cha mifugo ni nini?", "type": "multiple_choice", "options": [{"text": "Kuzalisha wadudu kama chanzo cha protini", "icon": "🐄", "isCorrect": true}, {"text": "Kuua wadudu wote", "icon": "❌", "isCorrect": false}, {"text": "Kulisha mifugo magugu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Wadudu kama black soldier fly ni protini endelevu."},
    {"question": "Agroecological livestock systems ni nini?", "type": "multiple_choice", "options": [{"text": "Ufugaji unaofuata kanuni za ikolojia", "icon": "🐄", "isCorrect": true}, {"text": "Ufugaji wa viwanda tu", "icon": "❌", "isCorrect": false}, {"text": "Kutofuga kabisa", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Agroecology inaunganisha mifugo na mazingira."},
    {"question": "Pasture-raised vs factory farming: tofauti ni ipi?", "type": "multiple_choice", "options": [{"text": "Pasture-raised wanyama wanaishi nje, factory farming ndani", "icon": "🐄", "isCorrect": true}, {"text": "Hakuna tofauti", "icon": "❌", "isCorrect": false}, {"text": "Factory farming ni bora", "icon": "❌", "isCorrect": false}, {"text": "Pasture ni ya viwanda", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Pasture-raised kwa kawaida ina welfare na mazingira bora."},
    {"question": "Regenerative grazing ni nini?", "type": "multiple_choice", "options": [{"text": "Malisho yanayoboresha udongo na mazingira", "icon": "🐄", "isCorrect": true}, {"text": "Malisho yanayoharibu udongo", "icon": "❌", "isCorrect": false}, {"text": "Kutolisha kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kulisha ndani tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Regenerative grazing inaboresha afya ya udongo na kuhifadhi kaboni."},
    {"question": "Integrated crop-livestock systems zina faida gani?", "type": "multiple_choice", "options": [{"text": "Mzunguko wa virutubisho na kupunguza pembejeo", "icon": "🐄", "isCorrect": true}, {"text": "Kuongeza gharama", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mavuno", "icon": "❌", "isCorrect": false}, {"text": "Hakuna faida", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mifumo ya pamoja yanatumia samadi na malisho kwa ufanisi."}
  ]
};

window.MODULE7_QUESTIONS_SW = MODULE7_QUESTIONS_SW;
