// Module 6: Ikolojia (Ecology) - 100 maswali
// Lugha: Kiswahili (Swahili)
// Nchi: Kenya
// 🌍 Generated for AgroLinguo

const MODULE6_QUESTIONS_SW = {
  "module6_level1": [
    {"question": "Ikolojia ni nini?", "type": "multiple_choice", "options": [{"text": "Uhusiano kati ya viumbe na mazingira yao", "icon": "🌍", "isCorrect": true}, {"text": "Uchumi tu", "icon": "❌", "isCorrect": false}, {"text": "Siasa tu", "icon": "❌", "isCorrect": false}, {"text": "Hisabati tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Ikolojia inachunguza jinsi viumbe vinavyoishi na kuingiliana."},
    {"question": "Mazingira ni nini?", "type": "multiple_choice", "options": [{"text": "Kila kitu kinachozunguka viumbe hai", "icon": "🌍", "isCorrect": true}, {"text": "Nyumba tu", "icon": "❌", "isCorrect": false}, {"text": "Maji tu", "icon": "❌", "isCorrect": false}, {"text": "Hewa tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Mazingira yanajumuisha hewa, maji, udongo, na viumbe vingine."},
    {"question": "Kilimo endelevu ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo kinachohifadhi mazingira kwa vizazi vijavyo", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha muda mfupi", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha kemikali tu", "icon": "❌", "isCorrect": false}, {"text": "Kilimo bila maji", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Kilimo endelevu kinalinda rasilimali za asili."},
    {"question": "Biodiversity ni nini?", "type": "multiple_choice", "options": [{"text": "Aina mbalimbali za viumbe hai", "icon": "🌍", "isCorrect": true}, {"text": "Aina moja tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna viumbe", "icon": "❌", "isCorrect": false}, {"text": "Mimea tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Biodiversity inahusu anuwai ya mimea, wanyama, na viumbe vyote."},
    {"question": "Mzunguko wa maji ni nini?", "type": "multiple_choice", "options": [{"text": "Jinsi maji yanavyosafiri kutoka bahari hadi ardhi na kurudi", "icon": "🌍", "isCorrect": true}, {"text": "Bomba la maji", "icon": "❌", "isCorrect": false}, {"text": "Tank ya maji", "icon": "❌", "isCorrect": false}, {"text": "Mto mmoja", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Mzunguko wa maji unajumuisha mvua, uvukizi, na mtiririko."},
    {"question": "Uchafuzi wa mazingira husababishwa na nini?", "type": "multiple_choice", "options": [{"text": "Shughuli za binadamu zinazoharibu mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Mvua tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Kemikali, plastiki, na gesi chafu zinachafua mazingira."},
    {"question": "Mzunguko wa nitrojeni unasaidia vipi mimea?", "type": "multiple_choice", "options": [{"text": "Kubadilisha nitrojeni ya hewa kuwa virutubisho", "icon": "🌍", "isCorrect": true}, {"text": "Kuongeza maji", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza jua", "icon": "❌", "isCorrect": false}, {"text": "Hakuna msaada", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Bakteria hurekebisha nitrojeni ili mimea itumie."},
    {"question": "Mti mmoja unasaidia mazingira vipi?", "type": "multiple_choice", "options": [{"text": "Kutoa oksijeni, kuhifadhi maji, na kulinda udongo", "icon": "🌍", "isCorrect": true}, {"text": "Kuchafua hewa", "icon": "❌", "isCorrect": false}, {"text": "Kuondoa maji", "icon": "❌", "isCorrect": false}, {"text": "Hakuna msaada", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Miti ni muhimu sana kwa ikolojia na kilimo."},
    {"question": "Organic farming ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo bila kemikali za sanisi", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha kemikali nyingi", "icon": "❌", "isCorrect": false}, {"text": "Kutolima kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha mashine tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Organic farming inatumia mbinu za asili."},
    {"question": "Pollinators ni nini?", "type": "multiple_choice", "options": [{"text": "Viumbe kama nyuki wanaosaidia mimea kuzaa", "icon": "🌍", "isCorrect": true}, {"text": "Wadudu waharibifu", "icon": "❌", "isCorrect": false}, {"text": "Magonjwa ya mimea", "icon": "❌", "isCorrect": false}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Nyuki na vipepeo wanasaidia mimea kuchavusha."}
  ],
  "module6_level2": [
    {"question": "Mzunguko wa kaboni ni nini?", "type": "multiple_choice", "options": [{"text": "Jinsi kaboni inavyozunguka kati ya hewa, mimea, na udongo", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbegu", "icon": "❌", "isCorrect": false}, {"text": "Bomba la maji", "icon": "❌", "isCorrect": false}, {"text": "Mfumo wa umwagiliaji", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mimea inachukua CO2 na udongo unahifadhi kaboni."},
    {"question": "Agroforestry ni nini?", "type": "multiple_choice", "options": [{"text": "Kupanda miti pamoja na mazao au mifugo", "icon": "🌍", "isCorrect": true}, {"text": "Kukata miti yote", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha maji", "icon": "❌", "isCorrect": false}, {"text": "Kutopanda chochote", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Agroforestry inaunganisha miti na kilimo kwa faida nyingi."},
    {"question": "Mmomonyoko wa udongo husababishwa na nini?", "type": "multiple_choice", "options": [{"text": "Mvua, upepo, na kukosekana kwa mimea", "icon": "🌍", "isCorrect": true}, {"text": "Mbolea nyingi", "icon": "❌", "isCorrect": false}, {"text": "Mimea mingi", "icon": "❌", "isCorrect": false}, {"text": "Maji kidogo", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Udongo unaohifadhiwa na mimea haupotei haraka."},
    {"question": "Cover crops ni nini?", "type": "multiple_choice", "options": [{"text": "Mimea inayopandwa kulinda udongo", "icon": "🌍", "isCorrect": true}, {"text": "Mazao ya kuuza tu", "icon": "❌", "isCorrect": false}, {"text": "Plastiki ya kufunika", "icon": "❌", "isCorrect": false}, {"text": "Majani yaliyokauka", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Cover crops zinalinda udongo na kuboresha virutubisho."},
    {"question": "Crop rotation ni nini?", "type": "multiple_choice", "options": [{"text": "Kubadilisha mazao yanayopandwa kila msimu", "icon": "🌍", "isCorrect": true}, {"text": "Kupanda zao moja tu daima", "icon": "❌", "isCorrect": false}, {"text": "Kuzungusha shamba", "icon": "❌", "isCorrect": false}, {"text": "Kupanda usiku tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Crop rotation inazuia magonjwa na kuboresha udongo."},
    {"question": "Composting ni nini?", "type": "multiple_choice", "options": [{"text": "Kuoza mabaki ya mimea na wanyama kutengeneza mbolea", "icon": "🌍", "isCorrect": true}, {"text": "Kuchoma takataka", "icon": "❌", "isCorrect": false}, {"text": "Kutupa takataka", "icon": "❌", "isCorrect": false}, {"text": "Kununua mbolea", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Compost ni mbolea bora ya asili."},
    {"question": "Integrated Pest Management (IPM) ni nini?", "type": "multiple_choice", "options": [{"text": "Kuchanganya mbinu mbalimbali kudhibiti wadudu", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia dawa nyingi tu", "icon": "❌", "isCorrect": false}, {"text": "Kuacha wadudu wote", "icon": "❌", "isCorrect": false}, {"text": "Hakuna udhibiti", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! IPM inapunguza matumizi ya kemikali."},
    {"question": "Beneficial insects ni nini?", "type": "multiple_choice", "options": [{"text": "Wadudu wanaosaidia kudhibiti wadudu waharibifu", "icon": "🌍", "isCorrect": true}, {"text": "Wadudu wanaoharibu mazao", "icon": "❌", "isCorrect": false}, {"text": "Wadudu wote", "icon": "❌", "isCorrect": false}, {"text": "Hakuna wadudu wa faida", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Ladybugs, lacewings wanakula wadudu waharibifu."},
    {"question": "Green manure ni nini?", "type": "multiple_choice", "options": [{"text": "Mimea inayolimwa ardhini kama mbolea", "icon": "🌍", "isCorrect": true}, {"text": "Mbolea ya kijani rangi", "icon": "❌", "isCorrect": false}, {"text": "Majani ya rangi ya kijani", "icon": "❌", "isCorrect": false}, {"text": "Maji ya kijani", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Green manure inaongeza virutubisho na organic matter."},
    {"question": "Mulching ni nini?", "type": "multiple_choice", "options": [{"text": "Kufunika udongo kwa majani au vifaa vingine", "icon": "🌍", "isCorrect": true}, {"text": "Kuondoa majani yote", "icon": "❌", "isCorrect": false}, {"text": "Kuchimba udongo", "icon": "❌", "isCorrect": false}, {"text": "Kumwagilia maji mengi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Mulching inahifadhi unyevu na kuzuia magugu."}
  ],
  "module6_level3": [
    {"question": "Carbon sequestration ni nini?", "type": "multiple_choice", "options": [{"text": "Kuhifadhi kaboni kwenye udongo na mimea", "icon": "🌍", "isCorrect": true}, {"text": "Kutoa kaboni hewani", "icon": "❌", "isCorrect": false}, {"text": "Kupoteza kaboni", "icon": "❌", "isCorrect": false}, {"text": "Kuuza kaboni", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Carbon sequestration inasaidia kupunguza mabadiliko ya hali ya hewa."},
    {"question": "Climate-smart agriculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo kinachostahimili na kupunguza athari za hali ya hewa", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo bila mpango", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha kemikali tu", "icon": "❌", "isCorrect": false}, {"text": "Kutolima kabisa", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! CSA inajiandaa kwa mabadiliko ya hali ya hewa."},
    {"question": "Ecosystem services ni nini?", "type": "multiple_choice", "options": [{"text": "Faida zinazotolewa na mazingira kwa binadamu", "icon": "🌍", "isCorrect": true}, {"text": "Huduma za duka", "icon": "❌", "isCorrect": false}, {"text": "Bei ya mazao", "icon": "❌", "isCorrect": false}, {"text": "Hakuna faida", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Ecosystem services zinajumuisha hewa safi, maji, na uchavushaji."},
    {"question": "Soil health indicators ni nini?", "type": "multiple_choice", "options": [{"text": "Vipimo vinavyoonyesha hali ya udongo", "icon": "🌍", "isCorrect": true}, {"text": "Rangi ya udongo tu", "icon": "❌", "isCorrect": false}, {"text": "Uzito wa udongo", "icon": "❌", "isCorrect": false}, {"text": "Bei ya udongo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Organic matter, pH, na viumbe vinaonyesha afya ya udongo."},
    {"question": "No-till farming ni nini?", "type": "multiple_choice", "options": [{"text": "Kupanda bila kulima udongo", "icon": "🌍", "isCorrect": true}, {"text": "Kulima sana", "icon": "❌", "isCorrect": false}, {"text": "Kutopanda kabisa", "icon": "❌", "isCorrect": false}, {"text": "Kutumia kemikali nyingi", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! No-till inahifadhi muundo wa udongo na kaboni."},
    {"question": "Biological nitrogen fixation ni nini?", "type": "multiple_choice", "options": [{"text": "Bakteria kubadilisha nitrojeni ya hewa kuwa mbolea", "icon": "🌍", "isCorrect": true}, {"text": "Kuongeza mbolea ya kemikali", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza nitrojeni", "icon": "❌", "isCorrect": false}, {"text": "Kutupa nitrojeni", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Legumes na bakteria zake zinarekebisha nitrojeni."},
    {"question": "Mycorrhizae ni nini?", "type": "multiple_choice", "options": [{"text": "Fangasi wanaosaidia mimea kupata virutubisho", "icon": "🌍", "isCorrect": true}, {"text": "Magonjwa ya mimea", "icon": "❌", "isCorrect": false}, {"text": "Wadudu waharibifu", "icon": "❌", "isCorrect": false}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Mycorrhizae zinaunganisha na mizizi kwa faida."},
    {"question": "Water retention capacity ya udongo inategemea nini?", "type": "multiple_choice", "options": [{"text": "Organic matter na muundo wa udongo", "icon": "🌍", "isCorrect": true}, {"text": "Rangi ya udongo tu", "icon": "❌", "isCorrect": false}, {"text": "Joto tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Udongo wenye organic matter unahifadhi maji vizuri."},
    {"question": "Biodiversity corridors ni nini?", "type": "multiple_choice", "options": [{"text": "Maeneo yanayounganisha habitats kwa wanyama", "icon": "🌍", "isCorrect": true}, {"text": "Barabara za magari", "icon": "❌", "isCorrect": false}, {"text": "Mifereji ya maji", "icon": "❌", "isCorrect": false}, {"text": "Sehemu za kuhifadhi mbegu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Corridors zinasaidia wanyama kusafiri kati ya maeneo."},
    {"question": "Riparian buffer ni nini?", "type": "multiple_choice", "options": [{"text": "Ukanda wa mimea kando ya mito kwa ulinzi", "icon": "🌍", "isCorrect": true}, {"text": "Bwawa la maji", "icon": "❌", "isCorrect": false}, {"text": "Daraja la mto", "icon": "❌", "isCorrect": false}, {"text": "Chombo cha kuosha", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Riparian buffers zinalinda mito kutokana na uchafuzi."}
  ],
  "module6_level4": [
    {"question": "Regenerative agriculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo kinachoboresha na kurudisha afya ya mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha kawaida", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha kuharibu", "icon": "❌", "isCorrect": false}, {"text": "Kutolima kabisa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Regenerative ag inaboresha udongo na mazingira kwa muda."},
    {"question": "Polyculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kupanda mazao mengi tofauti pamoja", "icon": "🌍", "isCorrect": true}, {"text": "Kupanda zao moja tu", "icon": "❌", "isCorrect": false}, {"text": "Kutopanda chochote", "icon": "❌", "isCorrect": false}, {"text": "Kupanda plastiki", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Polyculture inaiga mfumo wa asili na ina faida nyingi."},
    {"question": "Carbon farming ni nini?", "type": "multiple_choice", "options": [{"text": "Mbinu za kilimo zinazohifadhi kaboni kwenye udongo", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia makaa", "icon": "❌", "isCorrect": false}, {"text": "Kuchoma mabaki", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mimea", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Carbon farming inaweza kulipwa kwa kuhifadhi kaboni."},
    {"question": "Agroecology ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia kanuni za ikolojia kuboresha kilimo", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha kemikali", "icon": "❌", "isCorrect": false}, {"text": "Kilimo bila mpango", "icon": "❌", "isCorrect": false}, {"text": "Kuacha kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Agroecology inaunganisha sayansi ya ikolojia na kilimo."},
    {"question": "Silvopasture ni nini?", "type": "multiple_choice", "options": [{"text": "Kuchanganya miti na malisho ya mifugo", "icon": "🌍", "isCorrect": true}, {"text": "Kupanda miti tu", "icon": "❌", "isCorrect": false}, {"text": "Kufuga bila miti", "icon": "❌", "isCorrect": false}, {"text": "Kukata miti yote", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Silvopasture inatoa kivuli na chakula kwa mifugo."},
    {"question": "Soil organic carbon ni muhimu kwa nini?", "type": "multiple_choice", "options": [{"text": "Inaongeza rutuba na kuhifadhi maji", "icon": "🌍", "isCorrect": true}, {"text": "Inapunguza mavuno", "icon": "❌", "isCorrect": false}, {"text": "Haina umuhimu", "icon": "❌", "isCorrect": false}, {"text": "Inasababisha magonjwa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! SOC ni msingi wa udongo wenye afya."},
    {"question": "Biochar ni nini?", "type": "multiple_choice", "options": [{"text": "Mkaa wa hali ya juu unaoongezwa kwenye udongo", "icon": "🌍", "isCorrect": true}, {"text": "Mafuta ya kupikia", "icon": "❌", "isCorrect": false}, {"text": "Dawa ya wadudu", "icon": "❌", "isCorrect": false}, {"text": "Mbolea ya kemikali", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Biochar inahifadhi kaboni na kuboresha udongo."},
    {"question": "Permaculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kubuni mifumo ya kilimo inayoiga asili", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha msimu mmoja", "icon": "❌", "isCorrect": false}, {"text": "Kutumia kemikali nyingi", "icon": "❌", "isCorrect": false}, {"text": "Kilimo cha jangwani", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Permaculture inaunda mifumo inayojitegemea."},
    {"question": "Habitat farming ni nini?", "type": "multiple_choice", "options": [{"text": "Kuunda makazi ya viumbe kwenye shamba", "icon": "🌍", "isCorrect": true}, {"text": "Kuondoa viumbe vyote", "icon": "❌", "isCorrect": false}, {"text": "Kujenga nyumba tu", "icon": "❌", "isCorrect": false}, {"text": "Kupanda zao moja tu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Habitat farming inasaidia biodiversity shambani."},
    {"question": "Conservation tillage ni nini?", "type": "multiple_choice", "options": [{"text": "Kulima kwa njia inayopunguza uharibifu wa udongo", "icon": "🌍", "isCorrect": true}, {"text": "Kulima sana", "icon": "❌", "isCorrect": false}, {"text": "Kutumia kemikali nyingi", "icon": "❌", "isCorrect": false}, {"text": "Kuacha kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Conservation tillage inaiacha mabaki juu ya udongo."}
  ],
  "module6_level5": [
    {"question": "Greenhouse gas emissions kutoka kilimo ni nini?", "type": "multiple_choice", "options": [{"text": "Gesi kama methane na nitrous oxide zinazotoka shambani", "icon": "🌍", "isCorrect": true}, {"text": "Mvuke wa maji tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna gesi", "icon": "❌", "isCorrect": false}, {"text": "Oksijeni tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Kilimo kinachangia karibu 14% ya GHG za kimataifa."},
    {"question": "Enteric fermentation ni nini?", "type": "multiple_choice", "options": [{"text": "Mchakato wa usagaji wa ng'ombe unaotoa methane", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}, {"text": "Ugonjwa wa mimea", "icon": "❌", "isCorrect": false}, {"text": "Mfumo wa umwagiliaji", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Ng'ombe wanacheua methane kutoka tumboni."},
    {"question": "Nutrient runoff ni tatizo gani?", "type": "multiple_choice", "options": [{"text": "Virutubisho kusombwa na maji hadi kwenye mito", "icon": "🌍", "isCorrect": true}, {"text": "Virutubisho kuongezeka", "icon": "❌", "isCorrect": false}, {"text": "Virutubisho kubaki udongoni", "icon": "❌", "isCorrect": false}, {"text": "Hakuna tatizo", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Runoff inasababisha eutrophication ya maji."},
    {"question": "Eutrophication ni nini?", "type": "multiple_choice", "options": [{"text": "Maji kuwa na virutubisho vingi vinavyosababisha algae kuzidi", "icon": "🌍", "isCorrect": true}, {"text": "Maji kuwa safi", "icon": "❌", "isCorrect": false}, {"text": "Maji kupungua", "icon": "❌", "isCorrect": false}, {"text": "Maji kuwa baridi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Eutrophication inaondoa oksijeni na kuua viumbe vya maji."},
    {"question": "Land use change inaathiri mazingira vipi?", "type": "multiple_choice", "options": [{"text": "Kubadilisha misitu kuwa mashamba kunatoa kaboni", "icon": "🌍", "isCorrect": true}, {"text": "Hakuna athari", "icon": "❌", "isCorrect": false}, {"text": "Kunaboresha mazingira", "icon": "❌", "isCorrect": false}, {"text": "Kunapunguza kaboni", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Deforestation kwa kilimo ni chanzo kikubwa cha emissions."},
    {"question": "Sustainable intensification ni nini?", "type": "multiple_choice", "options": [{"text": "Kuongeza mavuno bila kuongeza athari za mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia kemikali zaidi", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mavuno", "icon": "❌", "isCorrect": false}, {"text": "Kuacha kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! SI inakuza mavuno kwa ufanisi wa rasilimali."},
    {"question": "Precision nutrient management ni nini?", "type": "multiple_choice", "options": [{"text": "Kutoa mbolea sahihi mahali na wakati sahihi", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia mbolea nyingi sana", "icon": "❌", "isCorrect": false}, {"text": "Kutotumia mbolea", "icon": "❌", "isCorrect": false}, {"text": "Kutupa mbolea", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Precision management inapunguza upotevu na uchafuzi."},
    {"question": "Water use efficiency ni nini?", "type": "multiple_choice", "options": [{"text": "Mavuno yanayopatikana kwa kiasi cha maji yaliyotumiwa", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia maji mengi", "icon": "❌", "isCorrect": false}, {"text": "Kupoteza maji", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! WUE ya juu inamaanisha maji yanatumika vizuri."},
    {"question": "Soil degradation ni nini?", "type": "multiple_choice", "options": [{"text": "Kupoteza ubora na rutuba ya udongo", "icon": "🌍", "isCorrect": true}, {"text": "Kuboresha udongo", "icon": "❌", "isCorrect": false}, {"text": "Kuongeza virutubisho", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Soil degradation ni tatizo kubwa la kimataifa."},
    {"question": "Desertification ni nini?", "type": "multiple_choice", "options": [{"text": "Ardhi kugeuka jangwa kwa sababu ya uharibifu", "icon": "🌍", "isCorrect": true}, {"text": "Ardhi kuwa na maji mengi", "icon": "❌", "isCorrect": false}, {"text": "Ardhi kuwa na mimea mingi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna mabadiliko", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Desertification inaathiri sehemu kubwa za Afrika."}
  ],
  "module6_level6": [
    {"question": "Life Cycle Assessment (LCA) katika kilimo ni nini?", "type": "multiple_choice", "options": [{"text": "Kupima athari za mazingira kutoka uzalishaji hadi mtumiaji", "icon": "🌍", "isCorrect": true}, {"text": "Kupima umri wa zao", "icon": "❌", "isCorrect": false}, {"text": "Kupima bei tu", "icon": "❌", "isCorrect": false}, {"text": "Kupima uzito tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! LCA inaonyesha footprint halisi ya bidhaa."},
    {"question": "Carbon footprint ya chakula ni nini?", "type": "multiple_choice", "options": [{"text": "Gesi chafu zinazotolewa kuzalisha na kusafirisha chakula", "icon": "🌍", "isCorrect": true}, {"text": "Alama ya miguu kwenye chakula", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya chakula", "icon": "❌", "isCorrect": false}, {"text": "Ladha ya chakula", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Carbon footprint inajumuisha hatua zote za uzalishaji."},
    {"question": "Environmental certification ya kilimo ni nini?", "type": "multiple_choice", "options": [{"text": "Uthibitisho kwamba kilimo kinafuata viwango vya mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Cheti cha biashara tu", "icon": "❌", "isCorrect": false}, {"text": "Leseni ya dereva", "icon": "❌", "isCorrect": false}, {"text": "Pasipoti", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Certifications kama Rainforest Alliance zinathibitisha sustainability."},
    {"question": "Payment for ecosystem services (PES) ni nini?", "type": "multiple_choice", "options": [{"text": "Kulipwa kwa kutoa huduma za mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Kununua vifaa", "icon": "❌", "isCorrect": false}, {"text": "Kuuza mazao", "icon": "❌", "isCorrect": false}, {"text": "Kukopa pesa", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Wakulima wanaweza kulipwa kwa kuhifadhi maji au kaboni."},
    {"question": "Biodiversity offsets ni nini?", "type": "multiple_choice", "options": [{"text": "Kufidia uharibifu wa biodiversity mahali pengine", "icon": "🌍", "isCorrect": true}, {"text": "Kuongeza uharibifu", "icon": "❌", "isCorrect": false}, {"text": "Kuuza wanyama", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Offsets zinasaidia kusawazisha athari za maendeleo."},
    {"question": "Green accounting ni nini?", "type": "multiple_choice", "options": [{"text": "Kujumuisha athari za mazingira kwenye hesabu za biashara", "icon": "🌍", "isCorrect": true}, {"text": "Kupaka rangi ya kijani", "icon": "❌", "isCorrect": false}, {"text": "Kuhesabu pesa tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Green accounting inaonyesha thamani ya mazingira."},
    {"question": "Natural capital ni nini?", "type": "multiple_choice", "options": [{"text": "Rasilimali za asili zinazotoa faida za kiuchumi", "icon": "🌍", "isCorrect": true}, {"text": "Pesa tu", "icon": "❌", "isCorrect": false}, {"text": "Majengo tu", "icon": "❌", "isCorrect": false}, {"text": "Mashine tu", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Natural capital inajumuisha udongo, maji, na biodiversity."},
    {"question": "Planetary boundaries ni nini?", "type": "multiple_choice", "options": [{"text": "Mipaka salama ya mazingira ambayo binadamu hawapaswi kuvuka", "icon": "🌍", "isCorrect": true}, {"text": "Mipaka ya nchi", "icon": "❌", "isCorrect": false}, {"text": "Mipaka ya mashamba", "icon": "❌", "isCorrect": false}, {"text": "Hakuna mipaka", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Kuvuka planetary boundaries kunasababisha hatari kubwa."},
    {"question": "Ecological footprint ni nini?", "type": "multiple_choice", "options": [{"text": "Ardhi inayohitajika kusaidia shughuli za binadamu", "icon": "🌍", "isCorrect": true}, {"text": "Alama ya miguu", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya udongo", "icon": "❌", "isCorrect": false}, {"text": "Ukubwa wa shamba", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Ecological footprint inaonyesha matumizi ya rasilimali."},
    {"question": "Circular bioeconomy ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia mabaki ya kilimo kama rasilimali mpya", "icon": "🌍", "isCorrect": true}, {"text": "Kutupa mabaki yote", "icon": "❌", "isCorrect": false}, {"text": "Kuchoma mabaki", "icon": "❌", "isCorrect": false}, {"text": "Kupoteza rasilimali", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Circular bioeconomy inapunguza upotevu na uchafuzi."}
  ],
  "module6_level7": [
    {"question": "IPCC ni nini na inafanya kazi gani?", "type": "multiple_choice", "options": [{"text": "Jopo la wanasayansi wanaochunguza mabadiliko ya hali ya hewa", "icon": "🌍", "isCorrect": true}, {"text": "Kampuni ya kilimo", "icon": "❌", "isCorrect": false}, {"text": "Serikali ya Kenya", "icon": "❌", "isCorrect": false}, {"text": "Benki ya dunia", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! IPCC inatoa ripoti za kisayansi kuhusu climate change."},
    {"question": "Paris Agreement inahusu nini?", "type": "multiple_choice", "options": [{"text": "Makubaliano ya kimataifa ya kupunguza emissions", "icon": "🌍", "isCorrect": true}, {"text": "Biashara ya mazao", "icon": "❌", "isCorrect": false}, {"text": "Utalii wa Paris", "icon": "❌", "isCorrect": false}, {"text": "Michezo ya Olympic", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Paris Agreement inalenga kuweka ongezeko la joto chini ya 2°C."},
    {"question": "Nationally Determined Contributions (NDCs) ni nini?", "type": "multiple_choice", "options": [{"text": "Ahadi za nchi kupunguza emissions", "icon": "🌍", "isCorrect": true}, {"text": "Fedha za serikali", "icon": "❌", "isCorrect": false}, {"text": "Bei ya mazao", "icon": "❌", "isCorrect": false}, {"text": "Mbegu za kisasa", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! NDCs zinaonyesha juhudi za kila nchi dhidi ya climate change."},
    {"question": "Sustainable Development Goals (SDGs) zinazohusiana na kilimo ni zipi?", "type": "multiple_choice", "options": [{"text": "SDG 2 (Njaa zero), SDG 12 (Uzalishaji endelevu), SDG 15 (Maisha ardhini)", "icon": "🌍", "isCorrect": true}, {"text": "Hakuna SDGs zinazohusiana", "icon": "❌", "isCorrect": false}, {"text": "SDG 1 tu", "icon": "❌", "isCorrect": false}, {"text": "SDG 17 tu", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! SDGs nyingi zinahusiana na kilimo endelevu."},
    {"question": "Convention on Biological Diversity (CBD) ni nini?", "type": "multiple_choice", "options": [{"text": "Mkataba wa kimataifa wa kuhifadhi biodiversity", "icon": "🌍", "isCorrect": true}, {"text": "Dawa ya wadudu", "icon": "❌", "isCorrect": false}, {"text": "Kampuni ya mbegu", "icon": "❌", "isCorrect": false}, {"text": "Mfumo wa umwagiliaji", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! CBD inalenga kuhifadhi anuwai ya viumbe hai."},
    {"question": "Aichi Biodiversity Targets ni nini?", "type": "multiple_choice", "options": [{"text": "Malengo ya kimataifa ya kuhifadhi biodiversity", "icon": "🌍", "isCorrect": true}, {"text": "Mbegu za Japan", "icon": "❌", "isCorrect": false}, {"text": "Mazao mapya", "icon": "❌", "isCorrect": false}, {"text": "Bei za soko", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Aichi targets ziliweka malengo hadi 2020."},
    {"question": "UNCCD ni nini?", "type": "multiple_choice", "options": [{"text": "Mkataba wa Umoja wa Mataifa wa kupambana na jangwa", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}, {"text": "Kampuni ya kilimo", "icon": "❌", "isCorrect": false}, {"text": "Mfumo wa umwagiliaji", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! UNCCD inalenga kuzuia na kurekebisha desertification."},
    {"question": "Land Degradation Neutrality (LDN) ni nini?", "type": "multiple_choice", "options": [{"text": "Lengo la kusawazisha uharibifu wa ardhi na uboreshaji", "icon": "🌍", "isCorrect": true}, {"text": "Kuharibu ardhi zaidi", "icon": "❌", "isCorrect": false}, {"text": "Kuacha kilimo", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! LDN inalenga kusawazisha kiwango cha uharibifu."},
    {"question": "Nature-based Solutions (NbS) ni nini?", "type": "multiple_choice", "options": [{"text": "Kutumia mazingira asilia kutatua changamoto", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia kemikali tu", "icon": "❌", "isCorrect": false}, {"text": "Kutumia mashine tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna suluhisho", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! NbS inatumia asili kwa faida za jamii na mazingira."},
    {"question": "Climate adaptation vs mitigation: tofauti ni ipi?", "type": "multiple_choice", "options": [{"text": "Adaptation ni kujiandaa, mitigation ni kupunguza emissions", "icon": "🌍", "isCorrect": true}, {"text": "Ni vitu vyote viwili", "icon": "❌", "isCorrect": false}, {"text": "Mitigation ni kujiandaa tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna tofauti", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Zote mbili zinahitajika kukabiliana na climate change."}
  ],
  "module6_level8": [
    {"question": "Soil microbiome ni nini?", "type": "multiple_choice", "options": [{"text": "Jumuiya ya viumbe vidogo kwenye udongo", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}, {"text": "Chombo cha kupima", "icon": "❌", "isCorrect": false}, {"text": "Mashine ya kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Microbiome inajumuisha bakteria, fangasi, na protozoa."},
    {"question": "Soil food web ni nini?", "type": "multiple_choice", "options": [{"text": "Uhusiano wa kulisha kati ya viumbe vya udongo", "icon": "🌍", "isCorrect": true}, {"text": "Website ya kilimo", "icon": "❌", "isCorrect": false}, {"text": "Duka la chakula", "icon": "❌", "isCorrect": false}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Soil food web inasaidia kubadilisha virutubisho."},
    {"question": "Glomalin ni nini?", "type": "multiple_choice", "options": [{"text": "Protini inayotolewa na mycorrhizae inayoshika udongo", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbolea", "icon": "❌", "isCorrect": false}, {"text": "Dawa ya wadudu", "icon": "❌", "isCorrect": false}, {"text": "Mbegu mpya", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Glomalin inashika chembe za udongo pamoja."},
    {"question": "Aggregate stability ni nini?", "type": "multiple_choice", "options": [{"text": "Uwezo wa udongo kushikilia muundo wake", "icon": "🌍", "isCorrect": true}, {"text": "Bei ya udongo", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya udongo", "icon": "❌", "isCorrect": false}, {"text": "Uzito wa udongo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Aggregate stability nzuri inazuia mmomonyoko."},
    {"question": "Humus ni nini?", "type": "multiple_choice", "options": [{"text": "Organic matter iliyooza kabisa kwenye udongo", "icon": "🌍", "isCorrect": true}, {"text": "Aina ya mbegu", "icon": "❌", "isCorrect": false}, {"text": "Dawa ya wadudu", "icon": "❌", "isCorrect": false}, {"text": "Mbolea ya kemikali", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Humus inahifadhi virutubisho na maji."},
    {"question": "Cation Exchange Capacity (CEC) ni nini?", "type": "multiple_choice", "options": [{"text": "Uwezo wa udongo kushikilia na kutoa virutubisho", "icon": "🌍", "isCorrect": true}, {"text": "Uzito wa udongo", "icon": "❌", "isCorrect": false}, {"text": "Rangi ya udongo", "icon": "❌", "isCorrect": false}, {"text": "Kina cha udongo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! CEC ya juu inamaanisha udongo unashikilia virutubisho vizuri."},
    {"question": "Soil compaction inaathiri vipi mimea?", "type": "multiple_choice", "options": [{"text": "Inazuia mizizi kupenya na maji kupita", "icon": "🌍", "isCorrect": true}, {"text": "Inasaidia mimea kukua", "icon": "❌", "isCorrect": false}, {"text": "Hakuna athari", "icon": "❌", "isCorrect": false}, {"text": "Inaongeza virutubisho", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Compaction inapunguza pores za hewa na maji."},
    {"question": "Cover crop termination methods ni zipi?", "type": "multiple_choice", "options": [{"text": "Kulima, roller crimper, au herbicide", "icon": "🌍", "isCorrect": true}, {"text": "Kuacha zikue", "icon": "❌", "isCorrect": false}, {"text": "Kuchoma tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna njia", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Njia tofauti zina faida na hasara tofauti."},
    {"question": "Decomposition rate inategemea nini?", "type": "multiple_choice", "options": [{"text": "Joto, unyevu, na uwiano wa kaboni na nitrojeni", "icon": "🌍", "isCorrect": true}, {"text": "Rangi ya mabaki", "icon": "❌", "isCorrect": false}, {"text": "Uzito tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Mazingira yanayofaa yanaharakisha decomposition."},
    {"question": "Soil respiration ni nini?", "type": "multiple_choice", "options": [{"text": "CO2 inayotolewa na viumbe vya udongo", "icon": "🌍", "isCorrect": true}, {"text": "Udongo kupumua hewa", "icon": "❌", "isCorrect": false}, {"text": "Mimea kutoa CO2", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Soil respiration inaonyesha shughuli za viumbe vya udongo."}
  ],
  "module6_level9": [
    {"question": "Gene drives zinaweza kutumika vipi kwa ikolojia?", "type": "multiple_choice", "options": [{"text": "Kudhibiti wadudu waharibifu kwa kueneza jeni", "icon": "🌍", "isCorrect": true}, {"text": "Kuendesha magari", "icon": "❌", "isCorrect": false}, {"text": "Kupanda mbegu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna matumizi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Gene drives zinaweza kupunguza wadudu au magonjwa."},
    {"question": "Synthetic biology katika kilimo ni nini?", "type": "multiple_choice", "options": [{"text": "Kuunda viumbe hai vipya kwa madhumuni ya kilimo", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia kemikali nyingi", "icon": "❌", "isCorrect": false}, {"text": "Kupanda plastiki", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kitu", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Synthetic biology inaweza kuunda microbes zinazoboresha udongo."},
    {"question": "Microbiome engineering ni nini?", "type": "multiple_choice", "options": [{"text": "Kubadilisha jumuiya ya viumbe vidogo kwa faida", "icon": "🌍", "isCorrect": true}, {"text": "Kujenga mashine", "icon": "❌", "isCorrect": false}, {"text": "Kupanda mbegu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Microbiome engineering inaweza kuboresha afya ya udongo."},
    {"question": "Carbon credit markets zinafanya kazi vipi?", "type": "multiple_choice", "options": [{"text": "Kuruhusu biashara ya haki za kutoa kaboni", "icon": "🌍", "isCorrect": true}, {"text": "Kuuza mazao tu", "icon": "❌", "isCorrect": false}, {"text": "Kununua mbolea tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kazi", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Carbon markets zinaunda motisha ya kupunguza emissions."},
    {"question": "Blue carbon ni nini?", "type": "multiple_choice", "options": [{"text": "Kaboni inayohifadhiwa na mazingira ya baharini", "icon": "🌍", "isCorrect": true}, {"text": "Kaboni ya rangi ya bluu", "icon": "❌", "isCorrect": false}, {"text": "Maji ya bahari", "icon": "❌", "isCorrect": false}, {"text": "Samaki", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Mangroves na seagrass zinahifadhi kaboni nyingi."},
    {"question": "Tipping points katika ikolojia ni nini?", "type": "multiple_choice", "options": [{"text": "Hatua ambapo mfumo unabadilika sana na harudi nyuma", "icon": "🌍", "isCorrect": true}, {"text": "Bei ya mazao", "icon": "❌", "isCorrect": false}, {"text": "Kilele cha mlima", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Tipping points zinaweza kusababisha mabadiliko ya kudumu."},
    {"question": "Ecosystem resilience ni nini?", "type": "multiple_choice", "options": [{"text": "Uwezo wa mfumo kurudi hali ya kawaida baada ya msongo", "icon": "🌍", "isCorrect": true}, {"text": "Kuharibu mazingira", "icon": "❌", "isCorrect": false}, {"text": "Kuongeza uchafuzi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna uwezo", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Mifumo yenye resilience inastahimili mabadiliko."},
    {"question": "Invasive species zinaathiri vipi biodiversity?", "type": "multiple_choice", "options": [{"text": "Zinashindana na kuondoa spishi za asili", "icon": "🌍", "isCorrect": true}, {"text": "Zinasaidia spishi za asili", "icon": "❌", "isCorrect": false}, {"text": "Hakuna athari", "icon": "❌", "isCorrect": false}, {"text": "Zinaongeza biodiversity", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Invasive species ni tishio kubwa kwa biodiversity."},
    {"question": "Rewilding ni nini?", "type": "multiple_choice", "options": [{"text": "Kurudisha hali ya asili kwa maeneo yaliyoathirika", "icon": "🌍", "isCorrect": true}, {"text": "Kujenga miji", "icon": "❌", "isCorrect": false}, {"text": "Kupanda mazao", "icon": "❌", "isCorrect": false}, {"text": "Kuchafua mazingira", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Rewilding inarudisha wanyama na mimea ya asili."},
    {"question": "Half-Earth concept ni nini?", "type": "multiple_choice", "options": [{"text": "Kuhifadhi nusu ya ardhi kwa asili", "icon": "🌍", "isCorrect": true}, {"text": "Kutumia nusu ya maji", "icon": "❌", "isCorrect": false}, {"text": "Kupanda nusu ya mbegu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Half-Earth inapendekeza kuhifadhi 50% ya uso wa dunia."}
  ],
  "module6_level10": [
    {"question": "Planetary health ni nini?", "type": "multiple_choice", "options": [{"text": "Uhusiano kati ya afya ya binadamu na mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Afya ya sayari zingine", "icon": "❌", "isCorrect": false}, {"text": "Dawa za mimea tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna uhusiano", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Planetary health inaonyesha uhusiano wa afya na mazingira."},
    {"question": "One Health approach ni nini?", "type": "multiple_choice", "options": [{"text": "Kuunganisha afya ya binadamu, wanyama, na mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Afya ya binadamu tu", "icon": "❌", "isCorrect": false}, {"text": "Afya ya wanyama tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna uhusiano", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! One Health inatambua uhusiano wa viumbe vyote."},
    {"question": "Doughnut economics ni nini?", "type": "multiple_choice", "options": [{"text": "Mfumo wa uchumi unaozingatia mipaka ya mazingira na jamii", "icon": "🌍", "isCorrect": true}, {"text": "Uchumi wa mikate", "icon": "❌", "isCorrect": false}, {"text": "Biashara ya chakula tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna maana", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! Doughnut economics inaonyesha nafasi salama kwa binadamu."},
    {"question": "Net-zero agriculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo kisichotoa emissions zaidi kuliko kinachochukua", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo bila mavuno", "icon": "❌", "isCorrect": false}, {"text": "Kilimo bila maji", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Net-zero inaweka usawa kati ya kutoa na kuchukua kaboni."},
    {"question": "Regenerative ocean farming ni nini?", "type": "multiple_choice", "options": [{"text": "Kulima baharini kwa njia inayoboresha mazingira", "icon": "🌍", "isCorrect": true}, {"text": "Kuvua samaki tu", "icon": "❌", "isCorrect": false}, {"text": "Kuchafua bahari", "icon": "❌", "isCorrect": false}, {"text": "Kukauka bahari", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Ocean farming inaweza kuzalisha chakula na kuhifadhi kaboni."},
    {"question": "Biosequestration potential ya kilimo ni nini?", "type": "multiple_choice", "options": [{"text": "Uwezo wa kilimo kuhifadhi kaboni kwenye udongo na mimea", "icon": "🌍", "isCorrect": true}, {"text": "Kuongeza emissions", "icon": "❌", "isCorrect": false}, {"text": "Kupoteza kaboni", "icon": "❌", "isCorrect": false}, {"text": "Hakuna uwezo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Kilimo kinaweza kuwa sehemu ya suluhisho la climate change."},
    {"question": "True cost of food ni nini?", "type": "multiple_choice", "options": [{"text": "Bei inayojumuisha athari za mazingira na jamii", "icon": "🌍", "isCorrect": true}, {"text": "Bei ya dukani tu", "icon": "❌", "isCorrect": false}, {"text": "Bei ya usafiri tu", "icon": "❌", "isCorrect": false}, {"text": "Hakuna gharama", "icon": "❌", "isCorrect": false}], "explanation": "Umefanya vizuri! True cost inaonyesha gharama halisi za chakula."},
    {"question": "Digital agriculture inaweza kusaidia vipi sustainability?", "type": "multiple_choice", "options": [{"text": "Kupunguza upotevu kwa usahihi na data", "icon": "🌍", "isCorrect": true}, {"text": "Kuongeza uchafuzi", "icon": "❌", "isCorrect": false}, {"text": "Hakuna msaada", "icon": "❌", "isCorrect": false}, {"text": "Kupunguza mavuno", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri! Digital tools zinapunguza matumizi ya pembejeo na upotevu."},
    {"question": "Food systems transformation ni nini?", "type": "multiple_choice", "options": [{"text": "Kubadilisha jinsi tunavyozalisha, kusindika, na kutumia chakula", "icon": "🌍", "isCorrect": true}, {"text": "Kubadilisha rangi ya chakula", "icon": "❌", "isCorrect": false}, {"text": "Kuacha kula", "icon": "❌", "isCorrect": false}, {"text": "Hakuna mabadiliko", "icon": "❌", "isCorrect": false}], "explanation": "Sawa kabisa! Transformation inahitajika kwa sustainability na afya."},
    {"question": "Multifunctional agriculture ni nini?", "type": "multiple_choice", "options": [{"text": "Kilimo kinachotoa faida za chakula, mazingira, na jamii", "icon": "🌍", "isCorrect": true}, {"text": "Kilimo cha chakula tu", "icon": "❌", "isCorrect": false}, {"text": "Kilimo bila faida", "icon": "❌", "isCorrect": false}, {"text": "Hakuna kilimo", "icon": "❌", "isCorrect": false}], "explanation": "Vizuri sana! Multifunctional ag inakidhi mahitaji mbalimbali ya jamii."}
  ]
};

window.MODULE6_QUESTIONS_SW = MODULE6_QUESTIONS_SW;
